/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
module

public import T3.ModelTheory.LocallyFinite.Universes
public import T3.ModelTheory.UniformLocalFiniteness

/-!
# Uniform local finiteness in arbitrary universes

The finite quantifier-free type cover constructed by compactness applies to tuples in all
models: each tuple belongs to a small elementary hull. The same finite cover consequently
supplies a uniform bound for generated substructures in every universe.

Paper-ID: model_theory.uniform_local_finiteness
TeX: T3_modelcompanion_v4.tex, Fact 2.5, lines 209–212; no label.
-/

@[expose] public section

open scoped FirstOrder

universe u v w

namespace FirstOrder.Language.Theory

variable {L : Language.{u, v}} {T : L.Theory}

/-- The finite quantifier-free type cover from the canonical semantic universe also covers
all tuples in models of arbitrary cardinality and universe.

Paper-ID: model_theory.uniform_local_finiteness
TeX: T3_modelcompanion_v4.tex, Fact 2.5, lines 209–212; no label.
-/
theorem IsLocallyFinite.exists_finite_qfType_cover_of_model [Finite L.Symbols]
    (hT : T.IsLocallyFinite) (n : ℕ) :
    ∃ P : Finset (Σ M : T.ModelType.{u, v, max u v}, Fin n → M),
      ∀ (M : Type w) [L.Structure M] [Nonempty M] [M ⊨ T] (a : Fin n → M),
        ∃ p ∈ P, ∀ φ : L.Formula (Fin n), φ.IsQF → (φ.Realize a ↔ φ.Realize p.2) := by
  classical
  obtain ⟨P, hP⟩ := hT.exists_finite_qfType_cover n
  refine ⟨P, ?_⟩
  intro M _ _ _ a
  obtain ⟨S, hS, hsmall⟩ := exists_small_elementarySubstructure_containing_finset
    (L := L) M (Finset.univ.image a)
  letI := hsmall
  let N : T.ModelType.{u, v, max u v} := (ModelType.of T S).shrink
  let e : S ≃[L] N := (equivShrink S).inducedStructureEquiv
  let a' : Fin n → S := fun i => ⟨a i, hS (by simp)⟩
  obtain ⟨p, hp, htype⟩ := hP N (e ∘ a')
  refine ⟨p, hp, fun φ hφ => ?_⟩
  have heφ := e.toElementaryEmbedding.map_formula φ a'
  simp only [Equiv.coe_toElementaryEmbedding] at heφ
  exact (S.subtype.map_formula φ a').trans (heφ.symm.trans (htype φ hφ))

/-- A single natural-number bound applies to all substructures generated by tuples of a
fixed length in arbitrary nonempty models.

Paper-ID: model_theory.uniform_local_finiteness
TeX: T3_modelcompanion_v4.tex, Fact 2.5, lines 209–212; no label.
-/
theorem IsLocallyFinite.exists_card_closure_range_le_of_model [Finite L.Symbols]
    (hT : T.IsLocallyFinite) (n : ℕ) :
    ∃ m : ℕ, ∀ (M : Type w) [L.Structure M] [Nonempty M] [M ⊨ T] (a : Fin n → M),
      Nat.card (Substructure.closure L (Set.range a)) ≤ m := by
  classical
  obtain ⟨P, hP⟩ := IsLocallyFinite.exists_finite_qfType_cover_of_model.{u, v, w} hT n
  let size (p : Σ M : T.ModelType.{u, v, max u v}, Fin n → M) : ℕ :=
    Nat.card (Substructure.closure L (Set.range p.2))
  refine ⟨P.sup size, ?_⟩
  intro N _ _ _ b
  obtain ⟨⟨M, a⟩, hp, hpb⟩ := hP N b
  letI := hT.finite_closure_range M a
  have hb : Nat.card (Substructure.closure L (Set.range b)) ≤ size ⟨M, a⟩ :=
    Substructure.card_closure_range_le_of_qfType a b hpb
  exact hb.trans (Finset.le_sup (f := size) hp)

/-- For each `n`, one bound applies to every substructure generated by at most `n` elements
of an arbitrary model of a locally finite theory in a finite language.

Paper-ID: model_theory.uniform_local_finiteness
TeX: T3_modelcompanion_v4.tex, Fact 2.5, lines 209–212; no label.
-/
theorem exists_card_closure_le_of_isLocallyFinite_of_model [Finite L.Symbols]
    (hT : T.IsLocallyFinite) (n : ℕ) :
    ∃ m : ℕ, ∀ (M : Type w) [L.Structure M] [Nonempty M] [M ⊨ T] (s : Finset M),
      s.card ≤ n → Nat.card (Substructure.closure L (s : Set M)) ≤ m := by
  classical
  obtain ⟨m, hm⟩ := IsLocallyFinite.exists_card_closure_range_le_of_model.{u, v, w} hT n
  refine ⟨m, ?_⟩
  intro M _ _ _ s hs
  have hc : Fintype.card s ≤ Fintype.card (Fin n) := by simpa using hs
  obtain ⟨e⟩ := Function.Embedding.nonempty_of_card_le hc
  let b : Fin n → M := Function.extend e ((↑) : s → M)
    (fun _ => Classical.choice (inferInstance : Nonempty M))
  have hsrange : (s : Set M) ⊆ Set.range b := by
    intro x hx
    exact ⟨e ⟨x, hx⟩, e.injective.extend_apply ((↑) : s → M)
      (fun _ => Classical.choice (inferInstance : Nonempty M)) ⟨x, hx⟩⟩
  letI := hT.finite_closure M (Set.range b) (Set.finite_range b)
  let f := Substructure.inclusion (Substructure.closure_mono (L := L) hsrange)
  exact (Nat.card_le_card_of_injective f f.injective).trans (hm M b)

/-- A finite tuple's full quantifier-free diagram in an arbitrary model has a finite
subset of representatives modulo the theory.

Paper-ID: model_theory.basic_definitions
TeX: T3_modelcompanion_v4.tex, Definition 2.2, item 6, lines 185–193; no label.
-/
theorem IsLocallyFinite.exists_finite_tupleQfDiagram_representatives_of_model
    [Finite L.Symbols] (hT : T.IsLocallyFinite) (M : Type w)
    [L.Structure M] [Nonempty M] [M ⊨ T] {n : ℕ} (a : Fin n → M) :
    ∃ Δ : Finset (L.Formula (Fin n)), (Δ : Set (L.Formula (Fin n))) ⊆ tupleQfDiagram (L := L) a ∧
      ∀ φ ∈ tupleQfDiagram (L := L) a, ∃ ψ ∈ Δ, φ ⇔[T] ψ := by
  classical
  obtain ⟨R, hR, hrepresentative⟩ := hT.exists_finite_qf_representatives n
  refine ⟨R.filter (fun ψ => ψ.Realize a), ?_, ?_⟩
  · intro ψ hψ
    have h := Finset.mem_filter.mp hψ
    exact ⟨hR ψ h.1, h.2⟩
  · intro φ hφ
    obtain ⟨ψ, hψ, heq⟩ := hrepresentative φ hφ.1
    refine ⟨ψ, Finset.mem_filter.mpr ⟨hψ, ?_⟩, heq⟩
    exact heq.realize_iff.mp hφ.2

end FirstOrder.Language.Theory
