/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
module

public import T3.GroupTheory.Roots.CommutatorRelations
public import T3.GroupTheory.Coproduct.GradedEquiv
public import T3.GroupTheory.Free.ExteriorBracket

/-!
# Simultaneous commutator roots

Given a finite family in the derived subgroup of an arbitrary exponent-three group, form the
coproduct with the free group on two new generators per family member and quotient by all root
relations at once. The canonical base map is injective. The proof follows the paper's three
claims: simultaneous normal words, independence of the new second-layer classes, and the mixed
third-layer tensor projection. Integer exponents in normal words are reduced modulo three;
the singleton normal-closure formula is also stated with coefficients in `ZMod 3`.

No finiteness, rank, or nontriviality assumption is imposed on the base group. Empty families
and prescribed identity elements are included.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`.
-/

@[expose] public section

open scoped commutatorElement TensorProduct IsMulCommutative
open Module T3.AssociatedGraded

namespace T3.CommutatorRoots

variable {G : Type*} [Group G] {n : ℕ}

/-- The two consecutive free-generator indices for one simultaneous root.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
def index (i : Fin n) (j : Fin 2) : Fin (2 * n) :=
  ⟨2 * i.val + j.val, by have := i.isLt; have := j.isLt; omega⟩

private theorem index_lt (i : Fin n) : index i 0 < index i 1 := by
  simp [index, Fin.lt_def]

/-- The increasing pair attached to one root block.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
def pair (i : Fin n) : IncreasingPair (Fin (2 * n)) := ⟨index i 0, index i 1, by exact index_lt i⟩

private theorem pair_injective : Function.Injective (pair (n := n)) := by
  intro i j h
  have hv := congrArg (fun p => p.first.val) h
  simp only [pair, index, Fin.val_zero, Nat.add_zero] at hv
  exact Fin.ext (by omega)

/-- The free commutator whose image becomes the prescribed root.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
def witness (i : Fin n) : Free (Fin (2 * n)) := ⁅Free.of (index i 0), Free.of (index i 1)⁆

/-- The ambient coproduct in which all roots are adjoined together.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
abbrev Ambient (G : Type*) [Group G] (n : ℕ) := Coproduct G (Free (Fin (2 * n)))

/-- The simultaneous relator in the paper's order.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
def relator (g : Fin n → G) (i : Fin n) : Ambient G n :=
  (Coproduct.inl (H := Free (Fin (2 * n))) (g i))⁻¹ * Coproduct.inr (witness i)

/-- The ordinary subgroup generated by the relators.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
def relationSubgroup (g : Fin n → G) : Subgroup (Ambient G n) :=
  Subgroup.closure (Set.range (relator g))

/-- The normal subgroup generated by the simultaneous relators.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
def kernel (g : Fin n → G) : Subgroup (Ambient G n) :=
  Subgroup.normalClosure (Set.range (relator g))

instance kernel_normal (g : Fin n → G) : (kernel g).Normal := Subgroup.normalClosure_normal

/-- Every relator belongs to the ambient derived subgroup.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
theorem relator_mem_commutator (g : Fin n → G) (hg : ∀ i, g i ∈ commutator G) (i : Fin n) :
    relator g i ∈ commutator (Ambient G n) := by
  apply Subgroup.mul_mem
  · exact (commutator _).inv_mem
      (termMap (Coproduct.inl (H := Free (Fin (2 * n)))) 2 ⟨g i, hg i⟩).property
  · simpa only [witness, map_commutatorElement, _root_.commutator_def] using
      Subgroup.commutator_mem_commutator
        (Subgroup.mem_top (Coproduct.inr (Free.of (index i 0)) : Ambient G n))
        (Subgroup.mem_top (Coproduct.inr (Free.of (index i 1)) : Ambient G n))

/-- The derived-subgroup version of the simultaneous relator.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
def bundledRelator (g : Fin n → G) (hg : ∀ i, g i ∈ commutator G) (i : Fin n) :
    commutator (Ambient G n) := ⟨relator g i, relator_mem_commutator g hg i⟩

/-- The simultaneous relation subgroup is contained in the ambient derived subgroup.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
theorem relationSubgroup_le_commutator (g : Fin n → G) (hg : ∀ i, g i ∈ commutator G) :
    relationSubgroup g ≤ commutator (Ambient G n) :=
  (Subgroup.closure_le _).mpr (by rintro _ ⟨i, rfl⟩; exact relator_mem_commutator g hg i)

/-- Claim A identifies the normal closure with `K[K,H₀]`, as a subgroup join.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
theorem kernel_eq_sup_commutator (g : Fin n → G) (hg : ∀ i, g i ∈ commutator G) :
    kernel g = relationSubgroup g ⊔ ⁅relationSubgroup g, (⊤ : Subgroup (Ambient G n))⁆ := by
  rw [kernel, ← Subgroup.normalClosure_closure_eq_normalClosure]
  exact normalClosure_eq_sup_commutator Fact.out (relationSubgroup_le_commutator g hg)

/-- The kernel remains in the ambient derived subgroup.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
theorem kernel_le_commutator (g : Fin n → G) (hg : ∀ i, g i ∈ commutator G) :
    kernel g ≤ commutator (Ambient G n) :=
  Subgroup.normalClosure_le_normal (by rintro _ ⟨i, rfl⟩; exact relator_mem_commutator g hg i)

/-- The concrete quotient from the paper.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
abbrev Extension (g : Fin n → G) := Ambient G n ⧸ kernel g

/-- The canonical base homomorphism.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
def baseMap (g : Fin n → G) : G →* Extension g :=
  (QuotientGroup.mk' (kernel g)).comp Coproduct.inl

/-- The designated new generators in the quotient.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
def generator (g : Fin n → G) (i : Fin n) (j : Fin 2) : Extension g :=
  (QuotientGroup.mk' (kernel g)) (Coproduct.inr (Free.of (index i j)))

/-- The simultaneous quotient satisfies the exponent-three law.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
theorem hasExponentThree_extension (g : Fin n → G) : HasExponentThree (Extension g) := Fact.out

/-- Each prescribed element is the commutator of its designated pair of generators.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
theorem baseMap_root (g : Fin n → G) (i : Fin n) :
    baseMap g (g i) = ⁅generator g i 0, generator g i 1⁆ := by
  have h : (QuotientGroup.mk' (kernel g)) (relator g i) = 1 :=
    (QuotientGroup.eq_one_iff _).mpr (Subgroup.subset_normalClosure ⟨i, rfl⟩)
  simpa only [relator, witness, map_mul, map_inv, map_commutatorElement, inv_mul_eq_one,
    baseMap, MonoidHom.comp_apply, generator] using h

private theorem mk_two_derivedBracketHom {A : Type*} [Group A] [Fact (HasExponentThree A)]
    (r : commutator A) (h : A) : mk A 2 (derivedBracketHom r h) = 0 := by
  apply (mk_eq_zero A 2 _).mpr
  exact commutator_top_le_term_three (le_refl (commutator A))
    (Subgroup.commutator_mem_commutator r.property (Subgroup.mem_top h))

private theorem mk_two_normalWord {A : Type*} [Group A] [Fact (HasExponentThree A)]
    (r : Fin n → commutator A) (m : Fin n → ℤ) (h : Fin n → A) :
    mk A 2 (normalWord r m h) = ∑ i, (m i : ZMod 3) • mk A 2 (r i) := by
  let : IsMulCommutative (commutator A) := isMulCommutative_commutator Fact.out
  let f : commutator A →* MulLayer A 2 := QuotientGroup.mk' (relation A 2)
  change Additive.ofMul (f (normalWord r m h)) = _
  rw [normalWord, map_prod, ofMul_prod]
  apply Finset.sum_congr rfl
  intro i _
  simp only [map_mul, map_zpow, ofMul_mul, ofMul_zpow]
  change m i • mk A 2 (r i) + mk A 2 (derivedBracketHom (r i) (h i)) = _
  rw [mk_two_derivedBracketHom, add_zero]
  exact (Int.cast_smul_eq_zsmul (ZMod 3) (m i) (mk A 2 (r i))).symm

/-- The independent second-layer vector attached to a root block.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
noncomputable def freeInitial (i : Fin n) : Layer (Free (Fin (2 * n))) 2 :=
  Free.layerTwoBasis (pair i)

/-- Distinct root blocks give linearly independent actual second-layer classes.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
theorem freeInitial_linearIndependent : LinearIndependent (ZMod 3) (freeInitial (n := n)) :=
  Free.layerTwoBasis.linearIndependent.comp pair pair_injective

private theorem mapLayer_snd_relator (g : Fin n → G) (hg : ∀ i, g i ∈ commutator G)
    (i : Fin n) :
    mapLayer (Coproduct.snd (G := G) Free.pow_three) 2
      (mk (Ambient G n) 2 (bundledRelator g hg i)) = freeInitial i := by
  rw [mapLayer_mk (Coproduct.snd (G := G) Free.pow_three) 2 (bundledRelator g hg i),
    freeInitial, Free.layerTwoBasis_apply]
  apply congrArg (mk (Free (Fin (2 * n))) 2)
  apply Subtype.ext
  change Coproduct.snd Free.pow_three (relator g i) = witness i
  simp [relator, Coproduct.snd_inl Free.pow_three (g i),
    Coproduct.snd_inr Free.pow_three (witness i)]

/-- Claim B: all exponent coefficients vanish in the coefficient field.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
theorem coefficients_eq_zero (g : Fin n → G) (hg : ∀ i, g i ∈ commutator G)
    (m : Fin n → ℤ) (h : Fin n → Ambient G n) {a : G}
    (ha : (normalWord (bundledRelator g hg) m h : Ambient G n) = Coproduct.inl a) :
    ∀ i, (m i : ZMod 3) = 0 := by
  have hz : mapLayer (Coproduct.snd (G := G) Free.pow_three) 2
      (mk (Ambient G n) 2 (normalWord (bundledRelator g hg) m h)) = 0 := by
    rw [mapLayer_mk (Coproduct.snd (G := G) Free.pow_three) 2
      (normalWord (bundledRelator g hg) m h), mk_eq_zero]
    change Coproduct.snd Free.pow_three
      (normalWord (bundledRelator g hg) m h : Ambient G n) ∈
        (⊤ : Subgroup (Free (Fin (2 * n)))).lowerCentralSeries 2
    rw [ha, Coproduct.snd_inl Free.pow_three a]
    exact Subgroup.one_mem _
  rw [mk_two_normalWord, map_sum] at hz
  simp only [map_smul, mapLayer_snd_relator] at hz
  exact Fintype.linearIndependent_iff.mp freeInitial_linearIndependent _ hz

private instance termThreeIsMulCommutative {A : Type*} [Group A] [Fact (HasExponentThree A)] :
    IsMulCommutative (term A 3) :=
  ⟨⟨fun a b => Subtype.ext (Subgroup.mem_center_iff.mp
    (lowerCentralSeries_two_le_center Fact.out b.property) a)⟩⟩

private def centralWord {A : Type*} [Group A] [Fact (HasExponentThree A)]
    (r : Fin n → commutator A) (h : Fin n → A) : term A 3 :=
  ∏ i, termCommutator (i := 2) (j := 1) (by decide) (by decide) (r i) ⟨h i, Subgroup.mem_top _⟩

private theorem normalWord_zero_eq {A : Type*} [Group A] [Fact (HasExponentThree A)]
    (r : Fin n → commutator A) (h : Fin n → A) :
    (normalWord r 0 h : A) = (centralWord r h : A) := by
  let : IsMulCommutative (commutator A) := isMulCommutative_commutator Fact.out
  have hle : term A 3 ≤ commutator A :=
    (⊤ : Subgroup A).lowerCentralSeries_antitone (show 1 ≤ 2 by decide)
  have he : Subgroup.inclusion hle (centralWord r h) = normalWord r 0 h := by
    simp only [centralWord, map_prod, normalWord, Pi.zero_apply, zpow_zero, one_mul]
    apply Finset.prod_congr rfl
    intro i _
    rfl
  exact congrArg Subtype.val he.symm

private theorem mk_three_centralWord {A : Type*} [Group A] [Fact (HasExponentThree A)]
    (r : Fin n → commutator A) (h : Fin n → A) :
    mk A 3 (centralWord r h) = ∑ i,
      bracketLayer (i := 2) (j := 1) (by decide) (by decide)
        (mk A 2 (r i)) (mk A 1 ⟨h i, Subgroup.mem_top _⟩) := by
  unfold centralWord AssociatedGraded.mk
  rw [map_prod, ofMul_prod]
  rfl

private theorem zpow_eq_one_of_cast_eq_zero {A : Type*} [Group A]
    [Fact (HasExponentThree A)] (r : A) (m : ℤ) (hm : (m : ZMod 3) = 0) : r ^ m = 1 := by
  obtain ⟨k, hk⟩ := (ZMod.intCast_zmod_eq_zero_iff_dvd m 3).mp hm
  norm_num at hk
  rw [hk, zpow_mul]
  have hc : r ^ (3 : ℤ) = 1 := by
    change r ^ ((3 : ℕ) : ℤ) = 1
    rw [zpow_natCast]
    exact (Fact.out : HasExponentThree A) r
  rw [hc, one_zpow]

private theorem normalWord_eq_zero_coefficients {A : Type*} [Group A]
    [Fact (HasExponentThree A)] (r : Fin n → commutator A) (m : Fin n → ℤ)
    (h : Fin n → A) (hm : ∀ i, (m i : ZMod 3) = 0) :
    normalWord r m h = normalWord r 0 h := by
  let : IsMulCommutative (commutator A) := isMulCommutative_commutator Fact.out
  unfold normalWord
  apply Finset.prod_congr rfl
  intro i _
  have he : r i ^ m i = 1 := Subtype.ext (zpow_eq_one_of_cast_eq_zero (r i : A) (m i) (hm i))
  simp only [he, Pi.zero_apply, zpow_zero, one_mul]

private theorem sum_tmul_freeInitial_eq_zero {V : Type*} [AddCommGroup V]
    [Module (ZMod 3) V] (s : Fin n → V)
    (hz : ∑ i, s i ⊗ₜ[ZMod 3] freeInitial i = 0) : ∀ i, s i = 0 := by
  intro i
  let e := TensorProduct.equivFinsuppOfBasisRight (M := V)
    (Free.layerTwoBasis (I := Fin (2 * n)))
  have he := congrArg (fun z => e z (pair i)) hz
  simp only [map_sum, map_zero, Finsupp.coe_finsetSum, Finset.sum_apply,
    Finsupp.coe_zero, Pi.zero_apply] at he
  simpa only [e, freeInitial, TensorProduct.equivFinsuppOfBasisRight_apply_tmul_apply,
    Basis.repr_self, Finsupp.single_apply, pair_injective.eq_iff, ite_smul,
    one_smul, zero_smul, Finset.sum_ite_eq', Finset.mem_univ, ite_true] using he

private theorem zpow_eq_pow_cast {A : Type*} [Group A] [Fact (HasExponentThree A)]
    (r : A) (m : ℤ) : r ^ m = r ^ (m : ZMod 3).val := by
  have hz : ((m - ((m : ZMod 3).val : ℤ) : ℤ) : ZMod 3) = 0 := by simp
  have he := zpow_eq_one_of_cast_eq_zero r (m - ((m : ZMod 3).val : ℤ)) hz
  rw [zpow_sub, mul_inv_eq_one] at he
  simpa only [zpow_natCast] using he

/-- Claim A's singleton normal closure consists exactly of `rᵐ [r,h]`, with `m ∈ 𝔽₃`.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
theorem mem_normalClosure_singleton_iff {A : Type*} [Group A] [Fact (HasExponentThree A)]
    (r : commutator A) (a : A) :
    a ∈ Subgroup.normalClosure ({(r : A)} : Set A) ↔
      ∃ m : ZMod 3, ∃ h : A, (r : A) ^ m.val * ⁅(r : A), h⁆ = a := by
  constructor
  · intro ha
    have hs : Set.range (fun _ : Fin 1 => (r : A)) = {(r : A)} := by ext; simp
    rw [← hs] at ha
    obtain ⟨m, h, hm⟩ := exists_normalWord (fun _ : Fin 1 => r) ha
    refine ⟨m 0, h 0, ?_⟩
    have he : (normalWord (fun _ : Fin 1 => r) m h : A) =
        (r : A) ^ m 0 * ⁅(r : A), h 0⁆ := by
      simp only [normalWord, Fin.prod_univ_succ, Fin.prod_univ_zero, mul_one]
      rfl
    rw [he, zpow_eq_pow_cast] at hm
    exact hm
  · rintro ⟨m, h, rfl⟩
    have hr : (r : A) ∈ Subgroup.normalClosure ({(r : A)} : Set A) :=
      Subgroup.subset_normalClosure (Set.mem_singleton _)
    exact Subgroup.mul_mem _ (Subgroup.pow_mem _ hr _)
      (Subgroup.commutator_le_left _ _
        (Subgroup.commutator_mem_commutator hr (Subgroup.mem_top h)))

/-- Claim A's product `K[K,H₀]` is an actual product of subgroup elements.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
theorem mem_kernel_iff_mul_commutator (g : Fin n → G) (hg : ∀ i, g i ∈ commutator G)
    (a : Ambient G n) :
    a ∈ kernel g ↔ ∃ k ∈ relationSubgroup g,
      ∃ p ∈ ⁅relationSubgroup g, (⊤ : Subgroup (Ambient G n))⁆, k * p = a := by
  rw [kernel, ← Subgroup.normalClosure_closure_eq_normalClosure]
  exact mem_normalClosure_iff_mul_commutator Fact.out (relationSubgroup_le_commutator g hg) a

section ExponentThree
variable [Fact (HasExponentThree G)]

private theorem relator_initial (g : Fin n → G) (hg : ∀ i, g i ∈ commutator G)
    (i : Fin n) :
    mk (Ambient G n) 2 (bundledRelator g hg i) =
      -mapLayer Coproduct.inl 2 (mk G 2 ⟨g i, hg i⟩) +
        mapLayer Coproduct.inr 2 (freeInitial i) := by
  rw [freeInitial, Free.layerTwoBasis_apply]
  rfl

private theorem bracket_inr_inl {H : Type*} [Group H] [Fact (HasExponentThree H)]
    (q : Layer H 2) (s : Layer G 1) :
    bracketLayer (i := 2) (j := 1) (by decide) (by decide)
      (mapLayer Coproduct.inr 2 q) (mapLayer Coproduct.inl 1 s) =
      -Coproduct.mixedMap (i := 1) (j := 2) (by decide) (by decide)
        (s ⊗ₜ[ZMod 3] q) := by
  rw [Coproduct.mixedMap_tmul, bracketLayer_one_two, neg_neg]

private theorem relator_bracket_blocks {H : Type*} [Group H] [Fact (HasExponentThree H)]
    (u : Layer G 2) (q : Layer H 2) (s : Layer G 1) (t : Layer H 1) :
    (Coproduct.layerThreeEquiv (G := G) (H := H)).symm
      (bracketLayer (i := 2) (j := 1) (by decide) (by decide)
        (-mapLayer Coproduct.inl 2 u + mapLayer Coproduct.inr 2 q)
        (mapLayer Coproduct.inl 1 s + mapLayer Coproduct.inr 1 t)) =
      (-bracketLayer (by decide) (by decide) u s,
        -(u ⊗ₜ[ZMod 3] t), -(s ⊗ₜ[ZMod 3] q),
        bracketLayer (by decide) (by decide) q t) := by
  simp only [map_add, map_neg, LinearMap.add_apply, LinearMap.neg_apply]
  rw [← mapLayer_bracketLayer (i := 2) (j := 1),
    ← mapLayer_bracketLayer (i := 2) (j := 1),
    ← Coproduct.mixedMap_tmul (i := 2) (j := 1), bracket_inr_inl]
  simp

private def firstLeft (h : Ambient G n) : Layer G 1 :=
  mapLayer (Coproduct.fst Fact.out) 1 (mk (Ambient G n) 1 ⟨h, Subgroup.mem_top _⟩)

private def firstRight (h : Ambient G n) : Layer (Free (Fin (2 * n))) 1 :=
  mapLayer (Coproduct.snd Fact.out) 1 (mk (Ambient G n) 1 ⟨h, Subgroup.mem_top _⟩)

private theorem first_decomposition (h : Ambient G n) :
    mk (Ambient G n) 1 ⟨h, Subgroup.mem_top _⟩ =
      mapLayer Coproduct.inl 1 (firstLeft h) + mapLayer Coproduct.inr 1 (firstRight h) :=
  (Coproduct.layerOneEquiv.apply_symm_apply
    (mk (Ambient G n) 1 ⟨h, Subgroup.mem_top _⟩)).symm

private theorem centralWord_blocks (g : Fin n → G) (hg : ∀ i, g i ∈ commutator G)
    (h : Fin n → Ambient G n) :
    (Coproduct.layerThreeEquiv (G := G) (H := Free (Fin (2 * n)))).symm
      (mk (Ambient G n) 3 (centralWord (bundledRelator g hg) h)) =
      ∑ i, (-bracketLayer (by decide) (by decide) (mk G 2 ⟨g i, hg i⟩) (firstLeft (h i)),
        -(mk G 2 ⟨g i, hg i⟩ ⊗ₜ[ZMod 3] firstRight (h i)),
        -(firstLeft (h i) ⊗ₜ[ZMod 3] freeInitial i),
        bracketLayer (by decide) (by decide) (freeInitial i) (firstRight (h i))) := by
  rw [mk_three_centralWord, map_sum]
  apply Finset.sum_congr rfl
  intro i _
  rw [relator_initial, first_decomposition]
  exact relator_bracket_blocks _ _ _ _

/-- Claim C: a product of central relator commutators cannot be a nontrivial base element.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
theorem centralWord_eq_one (g : Fin n → G) (hg : ∀ i, g i ∈ commutator G)
    (h : Fin n → Ambient G n) {a : G}
    (ha : (normalWord (bundledRelator g hg) 0 h : Ambient G n) = Coproduct.inl a) :
    a = 1 := by
  let c := centralWord (bundledRelator g hg) h
  have hc : (c : Ambient G n) = Coproduct.inl a := (normalWord_zero_eq _ _).symm.trans ha
  have ha3 : a ∈ term G 3 := by
    have hm := (termMap (Coproduct.fst (H := Free (Fin (2 * n))) Fact.out) 3 c).property
    change Coproduct.fst Fact.out (c : Ambient G n) ∈ term G 3 at hm
    simpa only [hc, Coproduct.fst_inl] using hm
  have hmk : mk (Ambient G n) 3 c = mapLayer Coproduct.inl 3 (mk G 3 ⟨a, ha3⟩) := by
    rw [mapLayer_mk]
    apply congrArg (mk (Ambient G n) 3)
    exact Subtype.ext hc
  have he := centralWord_blocks g hg h
  change (Coproduct.layerThreeEquiv (G := G) (H := Free (Fin (2 * n)))).symm
    (mk (Ambient G n) 3 c) = _ at he
  rw [hmk, Coproduct.layerThreeEquiv_symm_inl] at he
  have hmixed := congrArg (fun z : Coproduct.LayerThreeBlocks (G := G) (H := Free (Fin (2 * n))) =>
    z.2.2.1) he
  have hz : ∑ i, firstLeft (h i) ⊗ₜ[ZMod 3] freeInitial i = 0 := by
    simpa [Prod.fst_sum, Prod.snd_sum] using hmixed.symm
  have hs : ∀ i, firstLeft (h i) = 0 := sum_tmul_freeInitial_eq_zero _ hz
  have hpure := congrArg
    (fun z : Coproduct.LayerThreeBlocks (G := G) (H := Free (Fin (2 * n))) => z.1) he
  have hzero : mk G 3 ⟨a, ha3⟩ = 0 := by simpa [hs, Prod.fst_sum] using hpure
  have hmem := (mk_eq_zero G 3 ⟨a, ha3⟩).mp hzero
  simpa only [lowerCentralSeries_three_eq_bot Fact.out, Subgroup.mem_bot] using hmem

/-- The relation kernel has trivial intersection with the canonical copy of the base group.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
theorem eq_one_of_inl_mem_kernel (g : Fin n → G) (hg : ∀ i, g i ∈ commutator G)
    {a : G} (ha : Coproduct.inl a ∈ kernel g) : a = 1 := by
  obtain ⟨m, h, he⟩ := exists_normalWord (bundledRelator g hg) ha
  have hm := coefficients_eq_zero g hg m h he
  rw [normalWord_eq_zero_coefficients _ _ _ hm] at he
  exact centralWord_eq_one g hg h he

end ExponentThree

/-- The canonical map to the simultaneous root quotient has trivial kernel.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
theorem baseMap_ker (hG : HasExponentThree G) (g : Fin n → G)
    (hg : ∀ i, g i ∈ commutator G) : (baseMap g).ker = ⊥ := by
  let : Fact (HasExponentThree G) := ⟨hG⟩
  apply le_antisymm _ bot_le
  intro a ha
  apply Subgroup.mem_bot.mpr
  apply eq_one_of_inl_mem_kernel g hg
  exact (QuotientGroup.eq_one_iff _).mp ha

/-- All prescribed commutator roots can be adjoined simultaneously without collapsing the base.

Paper-ID: structure.simultaneous_commutator_roots
TeX: T3_modelcompanion_v9.tex, `lemma:basic commutator root`, v9 Lemma 4.7.
-/
theorem baseMap_injective (hG : HasExponentThree G) (g : Fin n → G)
    (hg : ∀ i, g i ∈ commutator G) : Function.Injective (baseMap g) :=
  (MonoidHom.ker_eq_bot_iff _).mp (baseMap_ker hG g hg)

end T3.CommutatorRoots
