/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
module

public import T3.GroupTheory.Subgroup
public import T3.GroupTheory.Roots.DefectBasis
public import T3.GroupTheory.Roots.Triple

/-!
# Strictification by simultaneous triple commutator roots

The enlarged subgroup is the image of `C × Free(Fin(3*n))` in the paper's simultaneous
quotient of `G × Free(Fin(3*n))`. Intersections and lower central terms are computed through
this same quotient. The defect generators become triple commutators in the enlarged subgroup.

The construction adjoins all roots simultaneously and chooses a basis of the defect, as in
the source.

Paper-ID: structure.lcs_strictification
TeX: T3_modelcompanion_v4.tex, `lemma:number of generators for triple commutator roots`,
v4 Lemma 4.9, lines 1133–1175.
-/

@[expose] public section

open scoped commutatorElement

universe u

namespace T3.LowerCentralStrictification

open AssociatedGraded

variable {G : Type u} [Group G] {n : ℕ} (C : Subgroup G) (g : Fin n → C)

/-- The free factor's map into the simultaneous quotient.

Paper-ID: structure.lcs_strictification
TeX: T3_modelcompanion_v4.tex, `lemma:number of generators for triple commutator roots`.
-/
def freeMap : Free (Fin (3 * n)) →* TripleRoots.Extension (fun i => (g i : G)) :=
  (QuotientGroup.mk' (TripleRoots.kernel (fun i => (g i : G)))).comp (MonoidHom.inr G _)

/-- The image of `C × Free(Fin(3*n))` in the paper's simultaneous quotient.

Paper-ID: structure.lcs_strictification
TeX: T3_modelcompanion_v4.tex, `lemma:number of generators for triple commutator roots`,
line 1147, the subgroup D.
-/
def enlargedSubgroup : Subgroup (TripleRoots.Extension (fun i => (g i : G))) :=
  (C.prod ⊤).map (QuotientGroup.mk' (TripleRoots.kernel (fun i => (g i : G))))

/-- The new free generators, before grouping them into triples.

Paper-ID: structure.lcs_strictification
TeX: T3_modelcompanion_v4.tex, `lemma:number of generators for triple commutator roots`.
-/
def newGenerator (i : Fin (3 * n)) : TripleRoots.Extension (fun i => (g i : G)) :=
  freeMap C g (Free.of i)

private theorem prod_eq_sup_map {K : Type*} [Group K] (A : Subgroup G) (B : Subgroup K) :
    A.prod B = A.map (MonoidHom.inl G K) ⊔ B.map (MonoidHom.inr G K) := by
  refine le_antisymm ?_ (sup_le ?_ ?_)
  · rintro ⟨x, y⟩ ⟨hx, hy⟩
    have hsplit : ((x, y) : G × K) = (x, 1) * (1, y) := by simp
    rw [hsplit]
    exact Subgroup.mul_mem _ (Subgroup.mem_sup_left ⟨x, hx, rfl⟩)
      (Subgroup.mem_sup_right ⟨y, hy, rfl⟩)
  · rintro _ ⟨x, hx, rfl⟩
    exact ⟨hx, Subgroup.one_mem _⟩
  · rintro _ ⟨y, hy, rfl⟩
    exact ⟨Subgroup.one_mem _, hy⟩

/-- The enlarged subgroup is generated by the original subgroup and the `3*n` free generators.

Paper-ID: structure.lcs_strictification
TeX: T3_modelcompanion_v4.tex, `lemma:number of generators for triple commutator roots`,
line 1147, `D = ⟨C,xᵢ,yᵢ,zᵢ⟩`.
-/
theorem enlargedSubgroup_eq_sup :
    enlargedSubgroup C g = C.map (TripleRoots.baseMap (fun i => (g i : G))) ⊔
      Subgroup.closure (Set.range (newGenerator C g)) := by
  rw [enlargedSubgroup, prod_eq_sup_map, Subgroup.map_sup, Subgroup.map_map,
    Subgroup.map_map, ← Free.closure_range_of, MonoidHom.map_closure, ← Set.range_comp]
  rfl

private theorem newGenerator_mem (i : Fin (3 * n)) :
    newGenerator C g i ∈ enlargedSubgroup C g := by
  exact Subgroup.mem_map_of_mem _ ⟨C.one_mem, Subgroup.mem_top _⟩

private theorem baseMap_mem (c : C) :
    TripleRoots.baseMap (fun i => (g i : G)) c ∈ enlargedSubgroup C g := by
  exact Subgroup.mem_map_of_mem _ ⟨c.property, Subgroup.mem_top _⟩

private theorem kernel_le_product (hg : ∀ i, (g i : G) ∈ Subgroup.center G) :
    TripleRoots.kernel (fun i => (g i : G)) ≤ C.prod ⊤ := by
  rw [TripleRoots.kernel_eq_closure _ hg]
  apply (Subgroup.closure_le _).mpr
  rintro x ⟨i, rfl⟩
  exact ⟨C.inv_mem (g i).property, Subgroup.mem_top _⟩

/-- The simultaneous relation subgroup lies in the third lower central term of the product.

Paper-ID: structure.lcs_strictification
TeX: T3_modelcompanion_v4.tex, `lemma:number of generators for triple commutator roots`,
line 1165, `L ≤ γ₃(G × F)`.
-/
theorem kernel_le_lowerCentralSeries (hg : ∀ i, (g i : G) ∈ term G 3) :
    TripleRoots.kernel (fun i => (g i : G)) ≤ term (G × Free (Fin (3 * n))) 3 := by
  apply Subgroup.normalClosure_le_normal
  rintro x ⟨i, rfl⟩
  rw [term, Subgroup.top_lowerCentralSeries_prod]
  refine ⟨(term G 3).inv_mem (hg i), ?_⟩
  exact Subgroup.commutator_mem_commutator
    (Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _))
    (Subgroup.mem_top _)

/-- The relation subgroup also lies in the intrinsic derived subgroup of `C × F`.

Paper-ID: structure.lcs_strictification
TeX: T3_modelcompanion_v4.tex, `lemma:number of generators for triple commutator roots`,
line 1151, `L ≤ γ₂(C × F)`.
-/
theorem kernel_le_product_derived (hg : ∀ i, (g i : G) ∈ Subgroup.center G)
    (hgC : ∀ i, g i ∈ commutator C) :
    TripleRoots.kernel (fun i => (g i : G)) ≤ (C.prod ⊤).lowerCentralSeries 1 := by
  rw [TripleRoots.kernel_eq_closure _ hg, Subgroup.lowerCentralSeries_prod]
  apply (Subgroup.closure_le _).mpr
  rintro x ⟨i, rfl⟩
  constructor
  · apply (C.lowerCentralSeries 1).inv_mem
    rw [← Subgroup.top_subtype_lowerCentralSeries]
    exact Subgroup.mem_map_of_mem _ (hgC i)
  · exact Subgroup.commutator_mem_commutator
      (Subgroup.mem_top _) (Subgroup.mem_top _)

private theorem lowerCentralSeries_enlargedSubgroup (k : ℕ) :
    (enlargedSubgroup C g).lowerCentralSeries k =
      ((C.lowerCentralSeries k).prod ((⊤ : Subgroup (Free (Fin (3 * n)))).lowerCentralSeries k)).map
        (QuotientGroup.mk' (TripleRoots.kernel (fun i => (g i : G)))) := by
  rw [enlargedSubgroup, ← Subgroup.map_lowerCentralSeries, Subgroup.lowerCentralSeries_prod]

private theorem intersection_enlargedSubgroup
    (hg : ∀ i, (g i : G) ∈ Subgroup.center G) (k : ℕ) :
    (⊤ : Subgroup (TripleRoots.Extension (fun i => (g i : G)))).lowerCentralSeries k ⊓
        enlargedSubgroup C g =
      (((⊤ : Subgroup G).lowerCentralSeries k ⊓ C).prod
        ((⊤ : Subgroup (Free (Fin (3 * n)))).lowerCentralSeries k)).map
          (QuotientGroup.mk' (TripleRoots.kernel (fun i => (g i : G)))) := by
  let q := QuotientGroup.mk' (TripleRoots.kernel (fun i => (g i : G)))
  have hq : Function.Surjective q := QuotientGroup.mk'_surjective _
  have hker : q.ker ≤ C.prod ⊤ := by
    rw [QuotientGroup.ker_mk']
    exact kernel_le_product C g hg
  have hmap : ((⊤ : Subgroup (G × Free (Fin (3 * n)))).lowerCentralSeries k).map q =
      (⊤ : Subgroup (TripleRoots.Extension (fun i => (g i : G)))).lowerCentralSeries k := by
    rw [Subgroup.map_lowerCentralSeries, Subgroup.map_top_of_surjective q hq]
  rw [← hmap, enlargedSubgroup, ← Subgroup.map_inf_of_ker_le hker,
    Subgroup.top_lowerCentralSeries_prod]
  congr 1
  ext x
  simp only [Subgroup.mem_inf, Subgroup.mem_prod, Subgroup.mem_top, and_true]
  tauto

private theorem baseMap_generator_mem_lowerCentralSeries (i : Fin n) :
    TripleRoots.baseMap (fun j => (g j : G)) (g i) ∈
      (enlargedSubgroup C g).lowerCentralSeries 2 := by
  rw [TripleRoots.baseMap_root]
  exact Subgroup.commutator_mem_commutator
    (Subgroup.commutator_mem_commutator (newGenerator_mem C g _) (newGenerator_mem C g _))
    (newGenerator_mem C g _)

/-- The simultaneous product quotient preserves the first strictness equality and removes
the third-layer defect. No finiteness or nontriviality assumption on the ambient group is used.

Paper-ID: structure.lcs_strictification
TeX: T3_modelcompanion_v4.tex, `lemma:number of generators for triple commutator roots`,
the two intersection claims in lines 1148–1174.
-/
theorem isStrict_enlargedSubgroup (hG : HasExponentThree G)
    (hg : ∀ i, (g i : G) ∈ term G 3)
    (hfirst : (commutator G).comap C.subtype = commutator C)
    (hdefect : (term G 3).comap C.subtype =
      term C 3 ⊔ Subgroup.closure (Set.range g)) : IsStrict (enlargedSubgroup C g) := by
  have hcentral (i : Fin n) : (g i : G) ∈ Subgroup.center G :=
    lowerCentralSeries_two_le_center hG (hg i)
  have hfirst' : C.lowerCentralSeries 1 = (⊤ : Subgroup G).lowerCentralSeries 1 ⊓ C := by
    rw [← Subgroup.top_subtype_lowerCentralSeries, Subgroup.top_lowerCentralSeries_one,
      ← hfirst, Subgroup.map_comap_eq, Subgroup.range_subtype]
    exact inf_comm _ _
  constructor
  · rw [lowerCentralSeries_enlargedSubgroup, intersection_enlargedSubgroup C g hcentral,
      hfirst']
  · apply le_antisymm
    · exact le_inf (Subgroup.lowerCentralSeries_mono 2 le_top)
        (Subgroup.lowerCentralSeries_le_self _ _)
    · rw [intersection_enlargedSubgroup C g hcentral]
      rintro x ⟨⟨a, b⟩, ⟨ha, hb⟩, rfl⟩
      let q := QuotientGroup.mk' (TripleRoots.kernel (fun i => (g i : G)))
      let D := enlargedSubgroup C g
      let f : C →* TripleRoots.Extension (fun i => (g i : G)) :=
        (TripleRoots.baseMap (fun i => (g i : G))).comp C.subtype
      have hbase : f.range ≤ D := by
        rintro y ⟨c, rfl⟩
        exact baseMap_mem C g c
      have hclosure : Subgroup.closure (Set.range g) ≤ (D.lowerCentralSeries 2).comap f := by
        apply (Subgroup.closure_le _).mpr
        rintro y ⟨i, rfl⟩
        exact baseMap_generator_mem_lowerCentralSeries C g i
      have hintrinsic : term C 3 ≤ (D.lowerCentralSeries 2).comap f := by
        rw [← Subgroup.map_le_iff_le_comap]
        change ((⊤ : Subgroup C).lowerCentralSeries 2).map f ≤ D.lowerCentralSeries 2
        rw [Subgroup.map_lowerCentralSeries, ← MonoidHom.range_eq_map]
        exact Subgroup.lowerCentralSeries_mono 2 hbase
      have hca : (⟨a, ha.2⟩ : C) ∈ term C 3 ⊔ Subgroup.closure (Set.range g) := by
        rw [← hdefect]
        exact ha.1
      have hleft : q (a, 1) ∈ D.lowerCentralSeries 2 :=
        (sup_le hintrinsic hclosure) hca
      have hright : q (1, b) ∈ D.lowerCentralSeries 2 := by
        rw [lowerCentralSeries_enlargedSubgroup]
        exact Subgroup.mem_map_of_mem _ ⟨(C.lowerCentralSeries 2).one_mem, hb⟩
      have hprod : q (a, b) = q (a, 1) * q (1, b) := by rw [← map_mul]; simp
      rw [hprod]
      exact (D.lowerCentralSeries 2).mul_mem hleft hright

/-- The finite set of new generators has cardinality at most `3*n`.

Paper-ID: structure.lcs_strictification
TeX: T3_modelcompanion_v4.tex, `lemma:number of generators for triple commutator roots`, item 1.
-/
theorem exists_generating_finset :
    ∃ Y : Finset (TripleRoots.Extension (fun i => (g i : G))), Y.card ≤ 3 * n ∧
      enlargedSubgroup C g = C.map (TripleRoots.baseMap (fun i => (g i : G))) ⊔
        Subgroup.closure (Y : Set (TripleRoots.Extension (fun i => (g i : G)))) := by
  classical
  refine ⟨Finset.univ.image (newGenerator C g), ?_, ?_⟩
  · exact Finset.card_image_le.trans (by simp)
  · simpa only [Finset.coe_image, Finset.coe_univ, Set.image_univ] using
      enlargedSubgroup_eq_sup C g

/-- The simultaneous enlargement of a finitely generated subgroup is finitely generated.

Paper-ID: structure.lcs_strictification
TeX: T3_modelcompanion_v4.tex, `lemma:number of generators for triple commutator roots`, item 1.
-/
instance enlargedSubgroup_fg [Group.FG C] : Group.FG (enlargedSubgroup C g) := by
  obtain ⟨Y, _, hY⟩ := exists_generating_finset C g
  apply (Group.fg_iff_subgroup_fg _).mpr
  rw [hY]
  apply Subgroup.FG.sup
  · have h : Group.FG ((TripleRoots.baseMap (fun i => (g i : G))).comp C.subtype).range :=
      inferInstance
    rw [MonoidHom.range_comp, Subgroup.range_subtype] at h
    exact (Group.fg_iff_subgroup_fg _).mp h
  · exact ⟨Y, rfl⟩

/-- The total number of generators increases by at most three per defect basis element.

Paper-ID: structure.lcs_strictification
TeX: T3_modelcompanion_v4.tex, `lemma:number of generators for triple commutator roots`, item 1.
-/
theorem rank_enlargedSubgroup_le [Group.FG C] :
    Group.rank (enlargedSubgroup C g) ≤ Group.rank C + 3 * n := by
  classical
  obtain ⟨s, hcard, hs⟩ := Group.rank_spec C
  obtain ⟨Y, hY, hgen⟩ := exists_generating_finset C g
  let f : C →* TripleRoots.Extension (fun i => (g i : G)) :=
    (TripleRoots.baseMap (fun i => (g i : G))).comp C.subtype
  let S := s.image f
  have hS : Subgroup.closure (S : Set (TripleRoots.Extension (fun i => (g i : G)))) =
      C.map (TripleRoots.baseMap (fun i => (g i : G))) := by
    change Subgroup.closure (↑(s.image f) : Set (TripleRoots.Extension (fun i => (g i : G)))) = _
    rw [Finset.coe_image, ← MonoidHom.map_closure, hs]
    change (⊤ : Subgroup C).map ((TripleRoots.baseMap (fun i => (g i : G))).comp C.subtype) = _
    rw [← Subgroup.map_map, ← MonoidHom.range_eq_map, Subgroup.range_subtype]
  have hgen' : Subgroup.closure (↑(S ∪ Y) : Set (TripleRoots.Extension (fun i => (g i : G)))) =
      enlargedSubgroup C g := by
    rw [Finset.coe_union, Subgroup.closure_union, hS, hgen]
  calc
    Group.rank (enlargedSubgroup C g) = Group.rank
        (Subgroup.closure (↑(S ∪ Y) : Set (TripleRoots.Extension (fun i => (g i : G))))) :=
      (Subgroup.rank_congr hgen').symm
    _ ≤ (S ∪ Y).card := Subgroup.rank_closure_finset_le_card _
    _ ≤ S.card + Y.card := Finset.card_union_le _ _
    _ ≤ Group.rank C + 3 * n := Nat.add_le_add (Finset.card_image_le.trans_eq hcard) hY

/-- Adjoining at most `3 * binom(m,2)` elements makes an `m`-generated subgroup strict,
provided the first lower-central intersection already agrees. The extension is the simultaneous
product quotient, using a basis of the second-layer defect.

Paper-ID: structure.lcs_strictification
TeX: T3_modelcompanion_v4.tex, `lemma:number of generators for triple commutator roots`,
v4 Lemma 4.9, both conclusions.
-/
theorem exists_strict_extension (hG : HasExponentThree G) [Group.FG C]
    (hfirst : (commutator G).comap C.subtype = commutator C)
    {m : ℕ} (hC : Group.rank C ≤ m) :
    ∃ (H : Type u) (_ : Group H), HasExponentThree H ∧
      ∃ f : G →* H, Function.Injective f ∧ ∃ (D : Subgroup H) (hD : Group.FG D),
        letI := hD
        C.map f ≤ D ∧ ∃ Y : Finset H, Y.card ≤ 3 * m.choose 2 ∧
          D = C.map f ⊔ Subgroup.closure (Y : Set H) ∧
          Group.rank D ≤ m + 3 * m.choose 2 ∧ IsStrict D := by
  let : Fact (HasExponentThree G) := ⟨hG⟩
  let : Fact (HasExponentThree C) := ⟨fun c => Subtype.ext (hG c)⟩
  obtain ⟨d, hd, a, _, ha, hdefect⟩ := exists_lowerCentral_defect_generators C.subtype hfirst
  obtain ⟨Y, hY, hgen⟩ := exists_generating_finset C a
  have hdm : d ≤ m.choose 2 := hd.trans (Nat.choose_mono 2 hC)
  refine ⟨TripleRoots.Extension (fun i => (a i : G)), inferInstance,
    TripleRoots.hasExponentThree_extension hG _, TripleRoots.baseMap _, ?_,
    enlargedSubgroup C a, inferInstance, ?_, Y, ?_, hgen, ?_,
    isStrict_enlargedSubgroup C a hG ha hfirst hdefect⟩
  · exact TripleRoots.baseMap_injective hG _ fun i =>
      lowerCentralSeries_two_le_center hG (ha i)
  · rw [enlargedSubgroup_eq_sup]
    exact le_sup_left
  · exact hY.trans (Nat.mul_le_mul_left 3 hdm)
  · exact (rank_enlargedSubgroup_le C a).trans (Nat.add_le_add hC (Nat.mul_le_mul_left 3 hdm))

end T3.LowerCentralStrictification
