/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
module

public import T3.GroupTheory.Subgroup
public import T3.GroupTheory.Roots.SharedCommutator
public import T3.GroupTheory.Roots.DefectBasis

/-!
# Derived strictification with three shared commutator roots

The three increasing pairs on the same three free generators remove a three-generator defect
in the derived-subgroup intersection. The construction uses the coproduct quotient from the
shared commutator-root construction and its canonical injective base map. The enlargement is
generated by the given subgroup and at most three new generators, rather than six.

The quotient and intersection calculations adapt `Roots.DerivedStrictification` and implement
the last sentence of Remark 4.11 with an actual improvement of Lemma 4.8's generator bound.

Paper-ID: structure.shared_triple_roots
TeX: T3_modelcompanion_v9.tex, Remark 4.11, line 1277.
-/

@[expose] public section

namespace T3.SharedDerivedStrictification

open AssociatedGraded
open scoped commutatorElement

universe u

variable {G : Type u} [Group G] {C : Subgroup G}

/-- The paper's simultaneous commutator-root extension.

Paper-ID: structure.shared_triple_roots
TeX: T3_modelcompanion_v9.tex, Remark 4.11, last sentence, applying Lemma 4.8.
-/
abbrev Extension (g : Fin 3 → C) := SharedCommutatorRoots.Extension (fun i => (g i : G))

/-- The canonical map of the ambient group into the simultaneous extension.

Paper-ID: structure.shared_triple_roots
TeX: T3_modelcompanion_v9.tex, Remark 4.11, last sentence, applying Lemma 4.8.
-/
def baseMap (g : Fin 3 → C) : G →* Extension g :=
  SharedCommutatorRoots.baseMap (fun i => (g i : G))

/-- The map of the new free factor into the simultaneous extension.

Paper-ID: structure.shared_triple_roots
TeX: T3_modelcompanion_v9.tex, Remark 4.11, last sentence, applying Lemma 4.8.
-/
def freeMap (g : Fin 3 → C) : Free (Fin 3) →* Extension g :=
  (QuotientGroup.mk' (SharedCommutatorRoots.kernel (fun i => (g i : G)))).comp Coproduct.inr

/-- The designated enlarged subgroup.

Paper-ID: structure.shared_triple_roots
TeX: T3_modelcompanion_v9.tex, Remark 4.11, last sentence, applying Lemma 4.8.
-/
def enlarged (g : Fin 3 → C) : Subgroup (Extension g) :=
  C.map (baseMap g) ⊔ (freeMap g).range

/-- The image of the original subgroup is contained in the enlargement.

Paper-ID: structure.shared_triple_roots
TeX: T3_modelcompanion_v9.tex, Remark 4.11, last sentence, applying Lemma 4.8.
-/
theorem map_le_enlarged (g : Fin 3 → C) : C.map (baseMap g) ≤ enlarged g := le_sup_left

/-- The new free factor is contained in the enlargement.

Paper-ID: structure.shared_triple_roots
TeX: T3_modelcompanion_v9.tex, Remark 4.11, last sentence, applying Lemma 4.8.
-/
theorem range_freeMap_le_enlarged (g : Fin 3 → C) : (freeMap g).range ≤ enlarged g := le_sup_right

/-- The new free generators.

Paper-ID: structure.shared_triple_roots
TeX: T3_modelcompanion_v9.tex, Remark 4.11, last sentence, applying Lemma 4.8.
-/
def newGenerator (g : Fin 3 → C) (i : Fin 3) : Extension g := freeMap g (Free.of i)

/-- The finite set of newly adjoined generators.

Paper-ID: structure.shared_triple_roots
TeX: T3_modelcompanion_v9.tex, Remark 4.11, last sentence, applying Lemma 4.8.
-/
noncomputable def newGenerators (g : Fin 3 → C) : Finset (Extension g) := by
  classical
  exact Finset.univ.image (newGenerator g)

/-- The enlargement uses at most three new generators for the three specified defects.

Paper-ID: structure.shared_triple_roots
TeX: T3_modelcompanion_v9.tex, Remark 4.11, last sentence, applying Lemma 4.8.
-/
theorem newGenerators_card_le (g : Fin 3 → C) : (newGenerators g).card ≤ 3 := by
  classical
  exact Finset.card_image_le.trans (by simp)

/-- The enlargement is generated by the image of `C` and the indicated finite new set.

Paper-ID: structure.shared_triple_roots
TeX: T3_modelcompanion_v9.tex, Remark 4.11, last sentence, applying Lemma 4.8.
-/
theorem enlarged_eq_closure (g : Fin 3 → C) :
    enlarged g =
      Subgroup.closure ((C.map (baseMap g) : Set (Extension g)) ∪ ↑(newGenerators g)) := by
  classical
  rw [enlarged, Subgroup.closure_union, Subgroup.closure_eq]
  congr 1
  rw [MonoidHom.range_eq_map, ← Free.closure_range_of (I := Fin 3),
    MonoidHom.map_closure]
  congr 1
  simp only [newGenerators, Finset.coe_image, Finset.coe_univ, ← Set.image_univ,
    Set.image_image]
  rfl

private theorem map_commutator_le_of_range_le {A B : Type*} [Group A] [Group B]
    (f : A →* B) (S : Subgroup B) (hf : f.range ≤ S) :
    (commutator A).map f ≤ ⁅S, S⁆ := by
  rw [commutator_def, Subgroup.map_commutator, ← MonoidHom.range_eq_map]
  exact Subgroup.commutator_mono hf hf

private theorem map_mem_commutator {A B : Type*} [Group A] [Group B]
    (f : A →* B) {a : A} (ha : a ∈ commutator A) : f a ∈ commutator B :=
  (termMap f 2 ⟨a, ha⟩).property

/-- Quotienting by these derived relators leaves the ambient abelianization unchanged.

Paper-ID: structure.shared_triple_roots
TeX: T3_modelcompanion_v9.tex, Remark 4.11, last sentence, applying Lemma 4.8.
-/
theorem comap_commutator_quotientMap (g : Fin 3 → C)
    (hg : ∀ i, (g i : G) ∈ commutator G) :
    (commutator (Extension g)).comap
      (QuotientGroup.mk' (SharedCommutatorRoots.kernel (fun i => (g i : G)))) =
      commutator (SharedCommutatorRoots.Ambient G) := by
  let q := QuotientGroup.mk' (SharedCommutatorRoots.kernel (fun i => (g i : G)))
  have hmap : (commutator (SharedCommutatorRoots.Ambient G)).map q = commutator (Extension g) := by
    rw [commutator_def, Subgroup.map_commutator,
      Subgroup.map_top_of_surjective q (QuotientGroup.mk'_surjective _), commutator_def]
  change (commutator (Extension g)).comap q = _
  rw [← hmap]
  apply Subgroup.comap_map_eq_self
  change (QuotientGroup.mk' (SharedCommutatorRoots.kernel (fun i => (g i : G)))).ker ≤ _
  rw [QuotientGroup.ker_mk']
  exact SharedCommutatorRoots.kernel_le_commutator _ hg

private theorem root_generator_mem_enlarged (g : Fin 3 → C) (i : Fin 3) (j : Fin 2) :
    SharedCommutatorRoots.generator (fun i => (g i : G)) i j ∈ enlarged g :=
  range_freeMap_le_enlarged g ⟨Free.of (SharedCommutatorRoots.index i j), rfl⟩

private theorem image_defect_le_commutator (g : Fin 3 → C)
    (hdefect : (commutator G).comap C.subtype = commutator C ⊔ Subgroup.closure (Set.range g)) :
    (commutator G).comap C.subtype ≤
      ⁅enlarged g, enlarged g⁆.comap ((baseMap g).comp C.subtype) := by
  rw [hdefect]
  apply sup_le
  · apply Subgroup.map_le_iff_le_comap.mp
    apply map_commutator_le_of_range_le
    rintro _ ⟨c, rfl⟩
    exact map_le_enlarged g ⟨c, c.property, rfl⟩
  · apply (Subgroup.closure_le _).mpr
    rintro _ ⟨i, rfl⟩
    change SharedCommutatorRoots.baseMap (fun i => (g i : G)) (g i : G) ∈
      ⁅enlarged g, enlarged g⁆
    rw [SharedCommutatorRoots.baseMap_root]
    exact Subgroup.commutator_mem_commutator
      (root_generator_mem_enlarged g i 0) (root_generator_mem_enlarged g i 1)

/-- The enlarged subgroup meets the ambient derived subgroup in its own derived subgroup.

Paper-ID: structure.shared_triple_roots
TeX: T3_modelcompanion_v9.tex, Remark 4.11, last sentence, applying Lemma 4.8.
-/
theorem inf_commutator_eq (hG : HasExponentThree G) (g : Fin 3 → C)
    (hg : ∀ i, (g i : G) ∈ commutator G)
    (hdefect : (commutator G).comap C.subtype = commutator C ⊔ Subgroup.closure (Set.range g)) :
    enlarged g ⊓ commutator (Extension g) = ⁅enlarged g, enlarged g⁆ := by
  apply le_antisymm
  · rintro a ⟨haD, ha⟩
    obtain ⟨u, hu, v, hv, k, hk, rfl⟩ := Subgroup.exists_mul_mul_commutator_of_mem_sup
      (C.map (baseMap g)) (freeMap g).range haD
    obtain ⟨c, hc, rfl⟩ := Subgroup.mem_map.mp hu
    obtain ⟨w, rfl⟩ := hv
    have hkD : k ∈ ⁅enlarged g, enlarged g⁆ := hk
    have hkH : k ∈ commutator (Extension g) :=
      Subgroup.commutator_mono le_top le_top hkD
    have hprod : baseMap g c * freeMap g w ∈ commutator (Extension g) := by
      have hm := (commutator (Extension g)).mul_mem ha ((commutator _).inv_mem hkH)
      simpa only [mul_inv_cancel_right] using hm
    have hamb : Coproduct.inl c * Coproduct.inr w ∈
        commutator (SharedCommutatorRoots.Ambient G) := by
      rw [← comap_commutator_quotientMap g hg]
      change (QuotientGroup.mk' (SharedCommutatorRoots.kernel (fun i => (g i : G))))
        (Coproduct.inl c * Coproduct.inr w) ∈ commutator (Extension g)
      simpa only [baseMap, SharedCommutatorRoots.baseMap, freeMap, MonoidHom.comp_apply, map_mul]
        using hprod
    have hcder : c ∈ commutator G := by
      have hm := map_mem_commutator (Coproduct.fst hG) hamb
      simpa only [map_mul, Coproduct.fst_inl, Coproduct.fst_inr, mul_one] using hm
    have hwder : w ∈ commutator (Free (Fin 3)) := by
      have hm := map_mem_commutator (Coproduct.snd Free.pow_three) hamb
      simpa only [map_mul, Coproduct.snd_inl Free.pow_three c,
        Coproduct.snd_inr Free.pow_three w, one_mul] using hm
    have hcD : baseMap g c ∈ ⁅enlarged g, enlarged g⁆ :=
      image_defect_le_commutator g hdefect (show (⟨c, hc⟩ : C) ∈
        (commutator G).comap C.subtype from hcder)
    have hwD : freeMap g w ∈ ⁅enlarged g, enlarged g⁆ :=
      map_commutator_le_of_range_le (freeMap g) (enlarged g) (range_freeMap_le_enlarged g)
        (Subgroup.mem_map_of_mem _ hwder)
    exact Subgroup.mul_mem _ (Subgroup.mul_mem _ hcD hwD) hkD
  · exact le_inf
      ((Subgroup.commutator_le_sup (H₁ := enlarged g) (H₂ := enlarged g)).trans (sup_idem _).le)
      (Subgroup.commutator_mono le_top le_top)

/-- The simultaneous extension has exponent dividing three.

Paper-ID: structure.shared_triple_roots
TeX: T3_modelcompanion_v9.tex, Remark 4.11, last sentence, applying Lemma 4.8.
-/
theorem hasExponentThree_extension (g : Fin 3 → C) : HasExponentThree (Extension g) :=
  SharedCommutatorRoots.hasExponentThree_extension _

/-- The ambient base group embeds into the simultaneous extension.

Paper-ID: structure.shared_triple_roots
TeX: T3_modelcompanion_v9.tex, Remark 4.11, last sentence, applying Lemma 4.8.
-/
theorem baseMap_injective (hG : HasExponentThree G) (g : Fin 3 → C)
    (hg : ∀ i, (g i : G) ∈ commutator G) : Function.Injective (baseMap g) :=
  SharedCommutatorRoots.baseMap_injective hG _ hg

/-- The first strictness equality in lower-central-series notation.

Paper-ID: structure.shared_triple_roots
TeX: T3_modelcompanion_v9.tex, Remark 4.11, last sentence, applying Lemma 4.8.
-/
theorem derived_strict (hG : HasExponentThree G) (g : Fin 3 → C)
    (hg : ∀ i, (g i : G) ∈ commutator G)
    (hdefect : (commutator G).comap C.subtype = commutator C ⊔ Subgroup.closure (Set.range g)) :
    (enlarged g).lowerCentralSeries 1 =
      (⊤ : Subgroup (Extension g)).lowerCentralSeries 1 ⊓ enlarged g := by
  simpa only [Subgroup.lowerCentralSeries_succ, Subgroup.lowerCentralSeries_zero,
    ← commutator_def, inf_comm] using (inf_commutator_eq hG g hg hdefect).symm

/-- Finite generation of the base subgroup passes to the indicated enlargement.

Paper-ID: structure.shared_triple_roots
TeX: T3_modelcompanion_v9.tex, Remark 4.11, last sentence, applying Lemma 4.8.
-/
instance enlarged_fg [Group.FG C] (g : Fin 3 → C) : Group.FG (enlarged g) := by
  apply (Group.fg_iff_subgroup_fg _).mpr
  apply Subgroup.FG.sup
  · have h : Group.FG ((baseMap g).comp C.subtype).range := inferInstance
    rw [MonoidHom.range_comp, Subgroup.range_subtype] at h
    exact (Group.fg_iff_subgroup_fg _).mp h
  · let : Group.FG (Free (Fin 3)) :=
      Group.fg_of_generating_family Free.of Free.closure_range_of
    exact (Group.fg_iff_subgroup_fg _).mp inferInstance

/-- The total generator rank increases by at most three for the three specified defects.

Paper-ID: structure.shared_triple_roots
TeX: T3_modelcompanion_v9.tex, Remark 4.11, last sentence, applying Lemma 4.8.
-/
theorem rank_enlarged_le [Group.FG C] (g : Fin 3 → C) :
    Group.rank (enlarged g) ≤ Group.rank C + 3 := by
  classical
  obtain ⟨s, hcard, hs⟩ := Group.rank_spec C
  let f := (baseMap g).comp C.subtype
  let S := s.image f
  have hS : Subgroup.closure (↑S : Set (Extension g)) = C.map (baseMap g) := by
    change Subgroup.closure (↑(s.image f) : Set (Extension g)) = _
    rw [Finset.coe_image, ← MonoidHom.map_closure, hs]
    change (⊤ : Subgroup C).map ((baseMap g).comp C.subtype) = _
    rw [← Subgroup.map_map, ← MonoidHom.range_eq_map, Subgroup.range_subtype]
  let Z := S ∪ newGenerators g
  have hZ : Subgroup.closure (↑Z : Set (Extension g)) = enlarged g := by
    change Subgroup.closure (↑(S ∪ newGenerators g) : Set (Extension g)) = _
    rw [Finset.coe_union, Subgroup.closure_union, hS, enlarged_eq_closure,
      Subgroup.closure_union, Subgroup.closure_eq]
  calc
    Group.rank (enlarged g) = Group.rank (Subgroup.closure (↑Z : Set (Extension g))) :=
      (Subgroup.rank_congr hZ).symm
    _ ≤ Z.card := Subgroup.rank_closure_finset_le_card _
    _ ≤ S.card + (newGenerators g).card := Finset.card_union_le _ _
    _ ≤ Group.rank C + 3 := Nat.add_le_add
      (Finset.card_image_le.trans_eq hcard) (newGenerators_card_le g)

/-- Three specified derived-intersection defect generators can be removed with only three
additional generators. The extension preserves the original ambient group in the same universe.

Paper-ID: structure.shared_triple_roots
TeX: T3_modelcompanion_v9.tex, Remark 4.11, last sentence, applying Lemma 4.8.
-/
theorem exists_shared_derived_strictification (hG : HasExponentThree G) [Group.FG C]
    (g : Fin 3 → C) (hg : ∀ i, (g i : G) ∈ commutator G)
    (hdefect : (commutator G).comap C.subtype = commutator C ⊔ Subgroup.closure (Set.range g)) :
    ∃ (H : Type u) (hH : Group H),
      letI := hH
      HasExponentThree H ∧ ∃ f : G →* H, Function.Injective f ∧
        ∃ (D : Subgroup H) (hD : Group.FG D),
          letI := hD
          C.map f ≤ D ∧ ∃ Y : Finset H, Y.card ≤ 3 ∧
            D = Subgroup.closure ((C.map f : Set H) ∪ ↑Y) ∧
            Group.rank D ≤ Group.rank C + 3 ∧
            D.lowerCentralSeries 1 = (⊤ : Subgroup H).lowerCentralSeries 1 ⊓ D := by
  exact ⟨Extension g, inferInstance, hasExponentThree_extension g, baseMap g,
    baseMap_injective hG g hg, enlarged g, inferInstance, map_le_enlarged g,
    newGenerators g, newGenerators_card_le g, enlarged_eq_closure g,
    rank_enlarged_le g, derived_strict hG g hg hdefect⟩

end T3.SharedDerivedStrictification
