/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
module

public import T3.GroupTheory.Free.NormalForm
public import T3.GroupTheory.AssociatedGraded.Product
public import T3.GroupTheory.GradedQuotient

/-!
# Simultaneous triple commutator roots

For a central family `z : Fin n → G`, the paper adjoins all roots at once in the quotient
of `G × Free (Fin (3 * n))` by the normal closure of `(z i)⁻¹ * [x i, y i, w i]`.
The relators are central, so their normal closure is their generated subgroup. Their distinct
triple coordinates recover the exponents in a product of relators. An element of this subgroup
whose free-group component is one therefore has trivial `G` component.

The simultaneous independence proof uses the coordinate calculations of
`T3.GroupTheory.Free.NormalForm`.

Paper-ID: structure.simultaneous_triple_roots
TeX: T3_modelcompanion_v4.tex, `lemma:triple commutator root`, v4 Lemma 4.8.
-/

@[expose] public section

open scoped commutatorElement

namespace T3.TripleRoots

variable {G : Type*} [Group G] {n : ℕ}

/-- The three generator indices in the `i`-th root block.

Paper-ID: structure.simultaneous_triple_roots
TeX: T3_modelcompanion_v4.tex, `lemma:triple commutator root`, v4 Lemma 4.8. -/
def index (i : Fin n) (j : Fin 3) : Fin (3 * n) :=
  ⟨3 * i.val + j.val, by have := i.isLt; have := j.isLt; omega⟩

private theorem index_lt (i : Fin n) {j k : Fin 3} (h : j < k) : index i j < index i k := by
  simpa only [index, Fin.mk_lt_mk, Nat.add_lt_add_iff_left] using (show j.val < k.val from h)

private theorem index_zero_injective : Function.Injective (fun i : Fin n => index i 0) := by
  intro i j h
  apply Fin.ext
  have := congrArg Fin.val h
  simp only [index, Fin.val_zero, Nat.add_zero] at this
  omega

/-- The central triple commutator on the `i`-th block of free generators.

Paper-ID: structure.simultaneous_triple_roots
TeX: T3_modelcompanion_v4.tex, `lemma:triple commutator root`, v4 Lemma 4.8. -/
def witness (i : Fin n) : Free (Fin (3 * n)) :=
  ⁅⁅Free.of (index i 0), Free.of (index i 1)⁆, Free.of (index i 2)⁆

/-- Every triple root witness is central in the free exponent-three group.

Paper-ID: structure.simultaneous_triple_roots
TeX: T3_modelcompanion_v4.tex, `lemma:triple commutator root`, v4 Lemma 4.8. -/
theorem witness_mem_center (i : Fin n) : witness i ∈ Subgroup.center (Free (Fin (3 * n))) :=
  T3.commutator_mem_center_of_mem_commutator Free.pow_three
    (Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _)) _

/-- The paper's simultaneous identification relator, with the displayed inverse on `z i`.

Paper-ID: structure.simultaneous_triple_roots
TeX: T3_modelcompanion_v4.tex, `lemma:triple commutator root`, v4 Lemma 4.8. -/
def relator (z : Fin n → G) (i : Fin n) : G × Free (Fin (3 * n)) :=
  ((z i)⁻¹, witness i)

/-- The normal subgroup generated by all simultaneous triple root relations.

Paper-ID: structure.simultaneous_triple_roots
TeX: T3_modelcompanion_v4.tex, `lemma:triple commutator root`, v4 Lemma 4.8. -/
def kernel (z : Fin n → G) : Subgroup (G × Free (Fin (3 * n))) :=
  Subgroup.normalClosure (Set.range (relator z))

instance kernel_normal (z : Fin n → G) : (kernel z).Normal :=
  Subgroup.normalClosure_normal

/-- Each relator is central when the specified base elements are central.

Paper-ID: structure.simultaneous_triple_roots
TeX: T3_modelcompanion_v4.tex, `lemma:triple commutator root`, v4 Lemma 4.8. -/
theorem relator_mem_center (z : Fin n → G) (hz : ∀ i, z i ∈ Subgroup.center G) (i : Fin n) :
    relator z i ∈ Subgroup.center (G × Free (Fin (3 * n))) := by
  rw [Subgroup.mem_center_iff]
  intro a
  exact Prod.ext (Subgroup.mem_center_iff.mp ((Subgroup.center G).inv_mem (hz i)) a.1)
    (Subgroup.mem_center_iff.mp (witness_mem_center i) a.2)

/-- Since all simultaneous relations are central, normal closure equals ordinary closure.

Paper-ID: structure.simultaneous_triple_roots
TeX: T3_modelcompanion_v4.tex, `lemma:triple commutator root`, v4 Lemma 4.8. -/
theorem kernel_eq_closure (z : Fin n → G) (hz : ∀ i, z i ∈ Subgroup.center G) :
    kernel z = Subgroup.closure (Set.range (relator z)) := by
  have hc : Subgroup.closure (Set.range (relator z)) ≤ Subgroup.center _ :=
    (Subgroup.closure_le _).2 (by rintro _ ⟨i, rfl⟩; exact relator_mem_center z hz i)
  have : (Subgroup.closure (Set.range (relator z))).Normal := by
    constructor
    intro a ha g
    rw [Subgroup.mem_center_iff.mp (hc ha) g, mul_assoc, mul_inv_cancel, mul_one]
    exact ha
  exact le_antisymm (Subgroup.normalClosure_le_normal Subgroup.subset_closure)
    Subgroup.closure_le_normalClosure

private def relationAmbient (G : Type*) [Group G] (n : ℕ) :
    Subgroup (G × Free (Fin (3 * n))) :=
  Subgroup.center _ ⊓ (Free.genReadout.comp (MonoidHom.snd G _)).ker

private instance relationAmbientCommGroup : CommGroup (relationAmbient G n) :=
  { (inferInstance : Group (relationAmbient G n)) with
    mul_comm a b := Subtype.ext (Subgroup.mem_center_iff.mp b.property.1 a) }

private def bundledRelator (z : Fin n → G) (hz : ∀ i, z i ∈ Subgroup.center G) (i : Fin n) :
    relationAmbient G n :=
  ⟨relator z i, relator_mem_center z hz i, Free.commutator_mem_genReadout_ker _ _⟩

private def relationWord (z : Fin n → G) (hz : ∀ i, z i ∈ Subgroup.center G)
    (m : Fin n → ℤ) : relationAmbient G n :=
  ∏ i, bundledRelator z hz i ^ m i

private theorem exists_relationWord (z : Fin n → G) (hz : ∀ i, z i ∈ Subgroup.center G)
    {a : G × Free (Fin (3 * n))} (ha : a ∈ kernel z) :
    ∃ m : Fin n → ℤ, (relationWord z hz m : G × Free (Fin (3 * n))) = a := by
  rw [kernel_eq_closure z hz] at ha
  induction ha using Subgroup.closure_induction with
  | mem a ha =>
    obtain ⟨i, rfl⟩ := ha
    refine ⟨Pi.single i 1, ?_⟩
    simp [relationWord, Pi.single_apply, bundledRelator]
  | one => exact ⟨0, by simp [relationWord]⟩
  | mul a b _ _ ha hb =>
    obtain ⟨m, rfl⟩ := ha
    obtain ⟨k, rfl⟩ := hb
    refine ⟨m + k, ?_⟩
    simp only [relationWord, Pi.add_apply, zpow_add, Finset.prod_mul_distrib, Subgroup.coe_mul]
  | inv a _ ha =>
    obtain ⟨m, rfl⟩ := ha
    refine ⟨-m, ?_⟩
    simp only [relationWord, Pi.neg_apply, zpow_neg, Finset.prod_inv_distrib, Subgroup.coe_inv]

private def coordinate (i : Fin n) : relationAmbient G n →* Multiplicative (ZMod 3) where
  toFun a := Multiplicative.ofAdd
    ((Free.toLvdW a.val.2).triple (index i 0) (index i 1) (index i 2))
  map_one' := rfl
  map_mul' a b := by
    have hb : ∀ j, (Free.toLvdW b.val.2).gen j = 0 := by
      have hb := b.property.2
      change Free.genReadout b.val.2 = 1 at hb
      rw [Free.genReadout_apply, ofAdd_eq_one] at hb
      exact congrFun hb
    apply (Multiplicative.toAdd).injective
    change (Free.toLvdW (a.val.2 * b.val.2)).triple _ _ _ =
      (Free.toLvdW a.val.2).triple _ _ _ + (Free.toLvdW b.val.2).triple _ _ _
    rw [map_mul, LvdW.mul_triple, hb, hb, hb]
    simp

private theorem coordinate_bundledRelator (z : Fin n → G)
    (hz : ∀ i, z i ∈ Subgroup.center G) (i j : Fin n) :
    coordinate i (bundledRelator z hz j) = Multiplicative.ofAdd (if i = j then 1 else 0) := by
  change Multiplicative.ofAdd ((Free.toLvdW (witness j)).triple _ _ _) = _
  rw [witness, map_commutatorElement, map_commutatorElement,
    Free.toLvdW_of, Free.toLvdW_of, Free.toLvdW_of,
    LvdW.triple_commutator_of_triple_of_lt (index_lt j (by decide)) (index_lt j (by decide))
      (index_lt i (by decide)) (index_lt i (by decide))]
  have h : (index i 0 = index j 0 ∧ index i 1 = index j 1 ∧
      index i 2 = index j 2) ↔ i = j :=
    ⟨fun h => index_zero_injective h.1, fun h => by subst j; simp⟩
  simp only [h]

private theorem coordinate_relationWord (z : Fin n → G)
    (hz : ∀ i, z i ∈ Subgroup.center G) (m : Fin n → ℤ) (i : Fin n) :
    coordinate i (relationWord z hz m) = Multiplicative.ofAdd (m i : ZMod 3) := by
  rw [relationWord, map_prod]
  simp only [map_zpow, coordinate_bundledRelator]
  rw [Finset.prod_eq_single i]
  · simp [← ofAdd_zsmul, zsmul_eq_mul]
  · intro b _ hbi
    simp [Ne.symm hbi]
  · simp

/-- The simultaneous relation subgroup intersects the base factor trivially.

Paper-ID: structure.simultaneous_triple_roots
TeX: T3_modelcompanion_v4.tex, `lemma:triple commutator root`, v4 Lemma 4.8. -/
theorem eq_one_of_inl_mem_kernel (hG : HasExponentThree G) (z : Fin n → G)
    (hz : ∀ i, z i ∈ Subgroup.center G) {g : G}
    (hg : MonoidHom.inl G (Free (Fin (3 * n))) g ∈ kernel z) : g = 1 := by
  obtain ⟨m, hm⟩ := exists_relationWord z hz hg
  have hcoeff (i : Fin n) : (m i : ZMod 3) = 0 := by
    have hc : coordinate i (relationWord z hz m) = 1 := by
      change Multiplicative.ofAdd
        ((Free.toLvdW ((relationWord z hz m : G × Free (Fin (3 * n))).2)).triple
          (index i 0) (index i 1) (index i 2)) = 1
      rw [hm]
      rfl
    simpa only [coordinate_relationWord, ofAdd_eq_one] using hc
  have hword : relationWord z hz m = 1 := by
    apply Finset.prod_eq_one
    intro i _
    obtain ⟨k, hk⟩ := (ZMod.intCast_zmod_eq_zero_iff_dvd (m i) 3).mp (hcoeff i)
    norm_num at hk
    rw [hk, zpow_mul]
    have hcube : bundledRelator z hz i ^ (3 : ℤ) = 1 := by
      apply Subtype.ext
      change ((z i)⁻¹, witness i) ^ (3 : ℤ) = (1 : G × Free (Fin (3 * n)))
      rw [show (3 : ℤ) = ((3 : ℕ) : ℤ) from rfl, zpow_natCast]
      exact Prod.ext (by change ((z i)⁻¹) ^ 3 = 1; rw [inv_pow, hG (z i), inv_one])
        (Free.pow_three _)
    rw [hcube, one_zpow]
  have h := congrArg Prod.fst hm
  simpa only [hword, Subgroup.coe_one, Prod.fst_one, MonoidHom.inl_apply] using h.symm

/-- The paper's quotient of the direct product by the simultaneous triple root relations.

Paper-ID: structure.simultaneous_triple_roots
TeX: T3_modelcompanion_v4.tex, `lemma:triple commutator root`, v4 Lemma 4.8. -/
abbrev Extension (z : Fin n → G) :=
  (G × Free (Fin (3 * n))) ⧸ kernel z

/-- The canonical map from the original group to the simultaneous root extension.

Paper-ID: structure.simultaneous_triple_roots
TeX: T3_modelcompanion_v4.tex, `lemma:triple commutator root`, v4 Lemma 4.8. -/
def baseMap (z : Fin n → G) : G →* Extension z :=
  (QuotientGroup.mk' (kernel z)).comp (MonoidHom.inl G _)

/-- The free generators, indexed by their root block and their position within that block.

Paper-ID: structure.simultaneous_triple_roots
TeX: T3_modelcompanion_v4.tex, `lemma:triple commutator root`, v4 Lemma 4.8. -/
def generator (z : Fin n → G) (i : Fin n) (j : Fin 3) : Extension z :=
  (QuotientGroup.mk' (kernel z)) (MonoidHom.inr G _ (Free.of (index i j)))

/-- The simultaneous root extension again has exponent dividing three.

Paper-ID: structure.simultaneous_triple_roots
TeX: T3_modelcompanion_v4.tex, `lemma:triple commutator root`, v4 Lemma 4.8. -/
theorem hasExponentThree_extension (hG : HasExponentThree G) (z : Fin n → G) :
    HasExponentThree (Extension z) := by
  let : Fact (HasExponentThree G) := ⟨hG⟩
  exact Fact.out

/-- The natural map into the paper's concrete simultaneous root quotient has trivial kernel.

Paper-ID: structure.simultaneous_triple_roots
TeX: T3_modelcompanion_v4.tex, `lemma:triple commutator root`, v4 Lemma 4.8. -/
theorem baseMap_ker (hG : HasExponentThree G) (z : Fin n → G)
    (hz : ∀ i, z i ∈ Subgroup.center G) : (baseMap z).ker = ⊥ := by
  apply le_antisymm _ bot_le
  intro g hg
  apply Subgroup.mem_bot.mpr
  apply eq_one_of_inl_mem_kernel hG z hz
  exact (QuotientGroup.eq_one_iff _).mp hg

/-- Adjoining the finite central family of triple roots simultaneously preserves the base group.

There is no nontriviality or rank assumption on `G`, and `n = 0` is included.

Paper-ID: structure.simultaneous_triple_roots
TeX: T3_modelcompanion_v4.tex, `lemma:triple commutator root`, v4 Lemma 4.8. -/
theorem baseMap_injective (hG : HasExponentThree G) (z : Fin n → G)
    (hz : ∀ i, z i ∈ Subgroup.center G) : Function.Injective (baseMap z) :=
  (MonoidHom.ker_eq_bot_iff _).mp (baseMap_ker hG z hz)

/-- Each designated base element becomes its prescribed triple commutator in the quotient.

Paper-ID: structure.simultaneous_triple_roots
TeX: T3_modelcompanion_v4.tex, `lemma:triple commutator root`, v4 Lemma 4.8. -/
theorem baseMap_root (z : Fin n → G) (i : Fin n) :
    baseMap z (z i) = ⁅⁅generator z i 0, generator z i 1⁆, generator z i 2⁆ := by
  change (QuotientGroup.mk' (kernel z)) (MonoidHom.inl G _ (z i)) =
    ⁅⁅(QuotientGroup.mk' (kernel z)) (MonoidHom.inr G _ (Free.of (index i 0))),
      (QuotientGroup.mk' (kernel z)) (MonoidHom.inr G _ (Free.of (index i 1)))⁆,
      (QuotientGroup.mk' (kernel z)) (MonoidHom.inr G _ (Free.of (index i 2)))⁆
  rw [← map_commutatorElement, ← map_commutatorElement, ← map_commutatorElement,
    ← map_commutatorElement]
  rw [QuotientGroup.mk'_apply, QuotientGroup.mk'_apply, QuotientGroup.eq]
  have h : (MonoidHom.inl G (Free (Fin (3 * n))) (z i))⁻¹ *
      MonoidHom.inr G _ (witness i) = relator z i := by
    simp only [MonoidHom.inl_apply, MonoidHom.inr_apply, Prod.inv_mk,
      Prod.mk_mul_mk, inv_one, mul_one, one_mul, relator]
  change (MonoidHom.inl G (Free (Fin (3 * n))) (z i))⁻¹ *
    MonoidHom.inr G _ (witness i) ∈ kernel z
  rw [h]
  exact Subgroup.subset_normalClosure ⟨i, rfl⟩

end T3.TripleRoots
