name = "T3"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["T3", "Solution"]
lintDriver = "batteries/runLinter"
fixedToolchain = true

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
maxSynthPendingDepth = 3
weak.linter.mathlibStandardSet = true
weak.linter.style.header = true
weak.linter.style.longFile = 1500

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "5ed2965256430c3649e86755f9576b54eca72435"

[[lean_lib]]
name = "T3"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"
