module  -- shake: keep-all --deprecated_module: ignore

public import T3.ForMathlib.DirectSum
public import T3.ForMathlib.LinearMapQuotient
public import T3.ForMathlib.PowersetCardSum
public import T3.ForMathlib.Subgroup
public import T3.ForMathlib.TensorProduct
public import T3.GroupTheory.Amalgamation
public import T3.GroupTheory.AssociatedGraded
public import T3.GroupTheory.AssociatedGraded.Bracket
public import T3.GroupTheory.AssociatedGraded.Generation
public import T3.GroupTheory.AssociatedGraded.Lie
public import T3.GroupTheory.AssociatedGraded.Product
public import T3.GroupTheory.AssociatedGraded.Subgroup
public import T3.GroupTheory.AssociatedGraded.Truncation
public import T3.GroupTheory.Basic
public import T3.GroupTheory.CentralSeries
public import T3.GroupTheory.ConjugateWidth
public import T3.GroupTheory.Coproduct.Basic
public import T3.GroupTheory.Coproduct.BlockBracket
public import T3.GroupTheory.Coproduct.CentralSeries
public import T3.GroupTheory.Coproduct.CentralSeriesCriterion
public import T3.GroupTheory.Coproduct.FreeGraded
public import T3.GroupTheory.Coproduct.FreeTwo
public import T3.GroupTheory.Coproduct.FreeTwoSeparation
public import T3.GroupTheory.Coproduct.Generation
public import T3.GroupTheory.Coproduct.Graded
public import T3.GroupTheory.Coproduct.GradedEquiv
public import T3.GroupTheory.Coproduct.Presentation
public import T3.GroupTheory.Coproduct.QuotientMaps
public import T3.GroupTheory.Coproduct.Relations
public import T3.GroupTheory.Coproduct.Strict
public import T3.GroupTheory.Coproduct.Support
public import T3.GroupTheory.Free.Basic
public import T3.GroupTheory.Free.Collection
public import T3.GroupTheory.Free.Examples
public import T3.GroupTheory.Free.Exterior
public import T3.GroupTheory.Free.ExteriorBracket
public import T3.GroupTheory.Free.ExteriorLie
public import T3.GroupTheory.Free.ExteriorNaturality
public import T3.GroupTheory.Free.FiniteSupport
public import T3.GroupTheory.Free.Graded
public import T3.GroupTheory.Free.InfiniteNormalForm
public import T3.GroupTheory.Free.Model
public import T3.GroupTheory.Free.ModelComparison
public import T3.GroupTheory.Free.NormalForm
public import T3.GroupTheory.Generation
public import T3.GroupTheory.GeneratorRank
public import T3.GroupTheory.GeneratorRank.Cardinality
public import T3.GroupTheory.GradedNormalClosure
public import T3.GroupTheory.GradedQuotient
public import T3.GroupTheory.Identities
public import T3.GroupTheory.Presentation
public import T3.GroupTheory.Roots.Commutator
public import T3.GroupTheory.Roots.CommutatorRelations
public import T3.GroupTheory.Roots.DefectBasis
public import T3.GroupTheory.Roots.DerivedStrictification
public import T3.GroupTheory.Roots.LowerCentralStrictification
public import T3.GroupTheory.Roots.Triple
public import T3.GroupTheory.Support
public import T3.GroupTheory.Support.Collection
public import T3.GroupTheory.Support.Conjugator
public import T3.GroupTheory.Support.Transport
public import T3.LinearAlgebra.BlockDecomposition
public import T3.LinearAlgebra.ExteriorLowDegree
public import T3.LinearAlgebra.ExteriorSum
public import T3.LinearAlgebra.ExteriorTensor
public import T3.LinearAlgebra.GradedLie
public import T3.LinearAlgebra.TruncatedExterior
public import T3.LinearAlgebra.Wedge
public import T3.Main.BoundedWitness
public import T3.Main.ModelCompanion
public import T3.ModelTheory.Amalgamation
public import T3.ModelTheory.BoundedAmalgamation
public import T3.ModelTheory.BoundedAmalgamationCriterion
public import T3.ModelTheory.ElementaryChain
public import T3.ModelTheory.ExistentialWitness
public import T3.ModelTheory.ExistentiallyClosedExtension
public import T3.ModelTheory.ExistentiallyClosedGroups
public import T3.ModelTheory.ExponentThree
public import T3.ModelTheory.ExtensionAxioms
public import T3.ModelTheory.FiniteDiagram
public import T3.ModelTheory.FiniteObstructions
public import T3.ModelTheory.GroupAmalgamation
public import T3.ModelTheory.GroupLanguage
public import T3.ModelTheory.Inductive
public import T3.ModelTheory.LocallyFinite
public import T3.ModelTheory.ModelCompanion
public import T3.ModelTheory.ModelCompanionCriterion
public import T3.ModelTheory.ModelCompleteness
public import T3.ModelTheory.PiTwoDirectLimit
public import T3.ModelTheory.RobinsonTest
public import T3.ModelTheory.StrictEnvelope
public import T3.ModelTheory.UniformLocalFiniteness
public import T3.Paper
