/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
module

public import T3.GroupTheory.AssociatedGraded.Lie

/-!
# Generation of the associated graded Lie algebra in degree one

The image of degree one generates the associated graded as a Lie algebra. The proof follows
the lower central series: each next term is generated as a subgroup by commutators of the
previous term with the whole group. Their initial forms are Lie brackets, while products and
inverses become sums and negatives in the degree quotient.

Paper-ID: preliminaries.associated_graded_properties
TeX: T3_modelcompanion_v9.tex, v9 Lemma 2.19, item 3, lines 511–512; no label.
-/

@[expose] public section

open scoped DirectSum commutatorElement

namespace T3.AssociatedGraded

variable {G : Type*} [Group G] [Fact (HasExponentThree G)]

private theorem lof_mk_mem_of_degree_one
    (K : LieSubalgebra (ZMod 3) (GradedModule G))
    (hK : Set.range (DirectSum.lof (ZMod 3) ℕ (Layer G) 1) ⊆ K) :
    ∀ (n : ℕ) (x : term G (n + 1)),
      DirectSum.lof (ZMod 3) ℕ (Layer G) (n + 1) (mk G (n + 1) x) ∈ K := by
  intro n
  induction n with
  | zero =>
    intro x
    exact hK ⟨mk G 1 x, rfl⟩
  | succ n ih =>
    rintro ⟨x, hx⟩
    change x ∈ (⊤ : Subgroup G).lowerCentralSeries (n + 1) at hx
    induction hx using Subgroup.closure_induction with
    | mem x hx =>
      obtain ⟨a, ha, b, hb, rfl⟩ := hx
      have hbracket := K.lie_mem (ih ⟨a, ha⟩) (hK ⟨mk G 1 ⟨b, hb⟩, rfl⟩)
      rw [bracket_lof (Nat.succ_pos n) (by decide), bracketLayer_mk] at hbracket
      exact hbracket
    | one =>
      change DirectSum.lof (ZMod 3) ℕ (Layer G) (n + 1 + 1) 0 ∈ K
      simpa only [map_zero] using K.zero_mem
    | mul a b ha hb hia hib =>
      change DirectSum.lof (ZMod 3) ℕ (Layer G) (n + 1 + 1)
        (mk G (n + 1 + 1) (⟨a, ha⟩ * ⟨b, hb⟩)) ∈ K
      rw [mk_mul, map_add]
      exact K.add_mem hia hib
    | inv a ha hia =>
      change DirectSum.lof (ZMod 3) ℕ (Layer G) (n + 1 + 1)
        (-mk G (n + 1 + 1) ⟨a, ha⟩) ∈ K
      rw [map_neg]
      exact K.neg_mem hia

/-- A Lie subalgebra containing the entire degree-one component is the associated graded Lie
algebra. No finite generation or rank assumption is needed.

Paper-ID: preliminaries.associated_graded_properties
TeX: T3_modelcompanion_v9.tex, v9 Lemma 2.19, item 3, lines 511–512; no label.
-/
theorem lieSubalgebra_eq_top_of_degree_one
    (K : LieSubalgebra (ZMod 3) (GradedModule G))
    (hK : Set.range (DirectSum.lof (ZMod 3) ℕ (Layer G) 1) ⊆ K) : K = ⊤ := by
  apply top_unique
  intro x hx
  clear hx
  induction x using DirectSum.induction_on with
  | zero => exact K.zero_mem
  | of n x =>
    change DirectSum.lof (ZMod 3) ℕ (Layer G) n x ∈ K
    cases n with
    | zero =>
      have hx : x = 0 := Subsingleton.elim _ _
      rw [hx, map_zero]
      exact K.zero_mem
    | succ n =>
      obtain ⟨x, rfl⟩ := mk_surjective G (n + 1) x
      exact lof_mk_mem_of_degree_one K hK n x
  | add x y hx hy => exact K.add_mem hx hy

/-- The associated graded Lie algebra of an exponent-three group is generated by its
degree-one component over `ZMod 3`.

Paper-ID: preliminaries.associated_graded_properties
TeX: T3_modelcompanion_v9.tex, v9 Lemma 2.19, item 3, lines 511–512; no label.
-/
theorem lieSpan_range_lof_one_eq_top :
    LieSubalgebra.lieSpan (ZMod 3) (GradedModule G)
      (Set.range (DirectSum.lof (ZMod 3) ℕ (Layer G) 1)) = ⊤ :=
  lieSubalgebra_eq_top_of_degree_one _ LieSubalgebra.subset_lieSpan

end T3.AssociatedGraded
