/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
module

public import T3.GroupTheory.Coproduct.Basic
public import Mathlib.GroupTheory.QuotientGroup.Basic

/-!
# The quotient presentation of an amalgam

The actual coproduct quotient identifies the two images of each element of the base group.
It maps to every exponent-three group receiving compatible maps from the factors. Thus an
amalgam exists precisely when both canonical factor maps to this quotient are injective.
A failure is witnessed by a nontrivial factor element in the normal closure of the relators.
For any generating family of the base, its relators already generate this normal subgroup.

The witness argument adapts earlier proofs by Yawara Ishida.
No finite generation or strong-amalgamation condition is imposed.
The universal target may have an arbitrary universe.

Paper-ID: main.bounded_witness
TeX: T3_modelcompanion_v4.tex, `thm:main`, lines 717–738.
-/

@[expose] public section

universe u v w z

namespace T3.Amalgamation

variable {A : Type u} {G : Type v} {H : Type w} [Group A] [Group G] [Group H]
  (f : A →* G) (g : A →* H)

/-- The paper's identification relator, with the right factor inverted.

Paper-ID: main.bounded_witness
TeX: T3_modelcompanion_v4.tex, `thm:main`, the definition of `δₐ`.
-/
def relator (a : A) : Coproduct G H := Coproduct.inl (f a) * (Coproduct.inr (g a))⁻¹

/-- The actual normal subgroup generated by all identification relators.

Paper-ID: main.bounded_witness
TeX: T3_modelcompanion_v4.tex, `thm:main`, the normal closure of the identification relations.
-/
def relations : Subgroup (Coproduct G H) := Subgroup.normalClosure (Set.range (relator f g))

/-- The identification relations form a normal subgroup.

Paper-ID: main.bounded_witness
TeX: T3_modelcompanion_v4.tex, `thm:main`, the quotient by the normal closure.
-/
instance relations_normal : (relations f g).Normal := Subgroup.normalClosure_normal

/-- The canonical coproduct quotient identifying the two maps from the base group.

Paper-ID: main.bounded_witness
TeX: T3_modelcompanion_v4.tex, `thm:main`, the quotient `H / ⟪Δ⟫`.
-/
abbrev Pushout := Coproduct G H ⧸ relations f g

/-- The left canonical homomorphism into the quotient.

Paper-ID: main.bounded_witness
TeX: T3_modelcompanion_v4.tex, `thm:main`, the canonical map from the left factor.
-/
def leftMap : G →* Pushout f g := (QuotientGroup.mk' (relations f g)).comp Coproduct.inl

/-- The right canonical homomorphism into the quotient.

Paper-ID: main.bounded_witness
TeX: T3_modelcompanion_v4.tex, `thm:main`, the canonical map from the right factor.
-/
def rightMap : H →* Pushout f g := (QuotientGroup.mk' (relations f g)).comp Coproduct.inr

/-- Killing a relator is exactly equality of the two corresponding quotient images.

Paper-ID: main.bounded_witness
TeX: T3_modelcompanion_v4.tex, `thm:main`, identification of the base in the quotient.
-/
theorem relator_mem_iff (N : Subgroup (Coproduct G H)) [N.Normal] (a : A) :
    relator f g a ∈ N ↔
      (QuotientGroup.mk' N) (Coproduct.inl (f a)) =
        (QuotientGroup.mk' N) (Coproduct.inr (g a)) := by
  simpa only [relator, div_eq_mul_inv, QuotientGroup.mk'_apply] using
    (QuotientGroup.eq_iff_div_mem (N := N)
      (x := Coproduct.inl (f a)) (y := Coproduct.inr (g a))).symm

/-- The canonical maps agree on every element of the base group.

Paper-ID: main.bounded_witness
TeX: T3_modelcompanion_v4.tex, `thm:main`, the amalgam diagram.
-/
theorem leftMap_comp_eq_rightMap_comp : (leftMap f g).comp f = (rightMap f g).comp g := by
  ext a
  exact (relator_mem_iff f g (relations f g) a).mp (Subgroup.subset_normalClosure ⟨a, rfl⟩)

/-- The canonical quotient satisfies the exponent-three law.

Paper-ID: main.bounded_witness
TeX: T3_modelcompanion_v4.tex, `thm:main`, the quotient as a candidate amalgam in `𝒱₃`.
-/
theorem hasExponentThree_pushout : HasExponentThree (Pushout f g) := by
  intro x
  obtain ⟨y, rfl⟩ := QuotientGroup.mk'_surjective (relations f g) x
  rw [← map_pow, Coproduct.pow_three, map_one]

variable {K : Type z} [Group K]

/-- Compatible factor maps kill all identification relations in any exponent-three target.

Paper-ID: main.bounded_witness
TeX: T3_modelcompanion_v4.tex, `thm:main`, the universal quotient argument.
-/
theorem relations_le_ker_lift (hK : HasExponentThree K) (i : G →* K) (j : H →* K)
    (hij : i.comp f = j.comp g) : relations f g ≤ (Coproduct.lift hK i j).ker := by
  apply Subgroup.normalClosure_le_normal
  rintro _ ⟨a, rfl⟩
  change Coproduct.lift hK i j (relator f g a) = 1
  simp only [relator, map_mul, map_inv, Coproduct.lift_inl, Coproduct.lift_inr]
  exact mul_inv_eq_one.mpr (DFunLike.congr_fun hij a)

/-- The universal homomorphism into an arbitrary exponent-three target.

Paper-ID: main.bounded_witness
TeX: T3_modelcompanion_v4.tex, `thm:main`, the quotient's universal property.
-/
def lift (hK : HasExponentThree K) (i : G →* K) (j : H →* K)
    (hij : i.comp f = j.comp g) : Pushout f g →* K :=
  QuotientGroup.lift (relations f g) (Coproduct.lift hK i j) (relations_le_ker_lift f g hK i j hij)

/-- The universal homomorphism restricts to the prescribed left factor map.

Paper-ID: main.bounded_witness
TeX: T3_modelcompanion_v4.tex, `thm:main`, the left universal triangle.
-/
@[simp]
theorem lift_leftMap (hK : HasExponentThree K) (i : G →* K) (j : H →* K)
    (hij : i.comp f = j.comp g) (x : G) : lift f g hK i j hij (leftMap f g x) = i x := rfl

/-- The universal homomorphism restricts to the prescribed right factor map.

Paper-ID: main.bounded_witness
TeX: T3_modelcompanion_v4.tex, `thm:main`, the right universal triangle.
-/
@[simp]
theorem lift_rightMap (hK : HasExponentThree K) (i : G →* K) (j : H →* K)
    (hij : i.comp f = j.comp g) (x : H) : lift f g hK i j hij (rightMap f g x) = j x := rfl

/-- Homomorphisms out of the canonical quotient are determined by the two factor maps.

Paper-ID: main.bounded_witness
TeX: T3_modelcompanion_v4.tex, `thm:main`, uniqueness in the universal property.
-/
theorem hom_ext {i j : Pushout f g →* K}
    (hl : i.comp (leftMap f g) = j.comp (leftMap f g))
    (hr : i.comp (rightMap f g) = j.comp (rightMap f g)) : i = j := by
  have hq : i.comp (QuotientGroup.mk' (relations f g)) =
      j.comp (QuotientGroup.mk' (relations f g)) :=
    Coproduct.hom_ext (DFunLike.congr_fun hl) (DFunLike.congr_fun hr)
  refine MonoidHom.ext fun x => ?_
  obtain ⟨y, rfl⟩ := QuotientGroup.mk'_surjective (relations f g) x
  exact DFunLike.congr_fun hq y

/-- Any amalgam, in any target universe, forces both canonical quotient maps to be injective.

Paper-ID: main.bounded_witness
TeX: T3_modelcompanion_v4.tex, `thm:main`, the canonical quotient criterion.
-/
theorem canonicalMaps_injective_of_amalgam (hK : HasExponentThree K)
    (i : G →* K) (j : H →* K) (hi : Function.Injective i) (hj : Function.Injective j)
    (hij : i.comp f = j.comp g) :
    Function.Injective (leftMap f g) ∧ Function.Injective (rightMap f g) := by
  constructor
  · intro x y h
    exact hi (by simpa only [lift_leftMap] using congrArg (lift f g hK i j hij) h)
  · intro x y h
    exact hj (by simpa only [lift_rightMap] using congrArg (lift f g hK i j hij) h)

/-- Ordinary amalgamation in the exponent-three variety. The target uses the canonical
universe of the coproduct; `canonicalMaps_injective_of_amalgam` also accepts larger targets.
No intersection condition is imposed on the two factor images.

Paper-ID: main.bounded_witness
TeX: T3_modelcompanion_v4.tex, `thm:main`, existence of an amalgam over the base.
-/
def AmalgamableOver : Prop :=
  ∃ (K : Type (max v w)) (hK : Group K),
    letI := hK
    HasExponentThree K ∧ ∃ (i : G →* K) (j : H →* K),
      Function.Injective i ∧ Function.Injective j ∧ i.comp f = j.comp g

/-- An amalgam exists exactly when both maps into the canonical quotient are injective.

Paper-ID: main.bounded_witness
TeX: T3_modelcompanion_v4.tex, `thm:main`, the first quotient criterion.
-/
theorem amalgamableOver_iff : AmalgamableOver f g ↔
    Function.Injective (leftMap f g) ∧ Function.Injective (rightMap f g) := by
  constructor
  · rintro ⟨K, hK, hpow, i, j, hi, hj, hij⟩
    letI : Group K := hK
    exact canonicalMaps_injective_of_amalgam f g hpow i j hi hj hij
  · rintro ⟨hl, hr⟩
    exact ⟨Pushout f g, inferInstance, hasExponentThree_pushout f g,
      leftMap f g, rightMap f g, hl, hr, leftMap_comp_eq_rightMap_comp f g⟩

/-- An amalgam in an arbitrary universe supplies one in the canonical coproduct universe.

Paper-ID: main.bounded_witness
TeX: T3_modelcompanion_v4.tex, `thm:main`, the universe-independent quotient criterion.
-/
theorem amalgamableOver_of_amalgam (hK : HasExponentThree K)
    (i : G →* K) (j : H →* K) (hi : Function.Injective i) (hj : Function.Injective j)
    (hij : i.comp f = j.comp g) : AmalgamableOver f g :=
  (amalgamableOver_iff f g).mpr (canonicalMaps_injective_of_amalgam f g hK i j hi hj hij)

/-- A left factor element dies in the quotient exactly when its coproduct image is a relation.

Paper-ID: main.bounded_witness
TeX: T3_modelcompanion_v4.tex, `thm:main`, the first nontrivial witness alternative.
-/
theorem leftMap_eq_one_iff (x : G) : leftMap f g x = 1 ↔ Coproduct.inl x ∈ relations f g :=
  QuotientGroup.eq_one_iff _

/-- A right factor element dies in the quotient exactly when its coproduct image is a relation.

Paper-ID: main.bounded_witness
TeX: T3_modelcompanion_v4.tex, `thm:main`, the second nontrivial witness alternative.
-/
theorem rightMap_eq_one_iff (x : H) : rightMap f g x = 1 ↔ Coproduct.inr x ∈ relations f g :=
  QuotientGroup.eq_one_iff _

/-- A failure of amalgamation is witnessed by a nontrivial element of one factor in the
normal closure of the identification relations.

Paper-ID: main.bounded_witness
TeX: T3_modelcompanion_v4.tex, `thm:main`, the two witness alternatives on lines 723–726.
-/
theorem exists_witness_of_not_amalgamableOver (h : ¬ AmalgamableOver f g) :
    (∃ x : G, x ≠ 1 ∧ Coproduct.inl x ∈ relations f g) ∨
      ∃ x : H, x ≠ 1 ∧ Coproduct.inr x ∈ relations f g := by
  classical
  by_contra! hn
  apply h
  apply (amalgamableOver_iff f g).mpr
  constructor
  · rw [injective_iff_map_eq_one]
    intro x hx
    by_contra hne
    exact hn.1 x hne ((leftMap_eq_one_iff f g x).mp hx)
  · rw [injective_iff_map_eq_one]
    intro x hx
    by_contra hne
    exact hn.2 x hne ((rightMap_eq_one_iff f g x).mp hx)

/-- Relators of any generating family of the base group generate all identification
relations as a normal subgroup. The index type need not be finite.

Paper-ID: main.bounded_witness
TeX: T3_modelcompanion_v4.tex, `thm:main`, replacing all base relations by `Δ`.
-/
theorem normalClosure_relators_eq_of_closure_range_eq_top {I : Type*} (a : I → A)
    (ha : Subgroup.closure (Set.range a) = ⊤) :
    Subgroup.normalClosure (Set.range fun i => relator f g (a i)) = relations f g := by
  let N := Subgroup.normalClosure (Set.range fun i => relator f g (a i))
  let q := QuotientGroup.mk' N
  have hagree : (q.comp Coproduct.inl).comp f = (q.comp Coproduct.inr).comp g := by
    apply MonoidHom.eq_of_eqOn_dense ha
    rintro x ⟨i, rfl⟩
    exact (relator_mem_iff f g N (a i)).mp (Subgroup.subset_normalClosure ⟨i, rfl⟩)
  apply le_antisymm
  · apply Subgroup.normalClosure_mono
    rintro x ⟨i, rfl⟩
    exact ⟨a i, rfl⟩
  · apply Subgroup.normalClosure_le_normal
    rintro x ⟨x, rfl⟩
    exact (relator_mem_iff f g N x).mpr (DFunLike.congr_fun hagree x)

/-- The nontrivial witness may be taken in the normal closure of the prescribed generating
family's relators, exactly as in the paper's finite set `Δ`.

Paper-ID: main.bounded_witness
TeX: T3_modelcompanion_v4.tex, `thm:main`, lines 720–726.
-/
theorem exists_witness_of_generating_family {I : Type*} (a : I → A)
    (ha : Subgroup.closure (Set.range a) = ⊤) (h : ¬ AmalgamableOver f g) :
    (∃ x : G, x ≠ 1 ∧ Coproduct.inl x ∈
      Subgroup.normalClosure (Set.range fun i => relator f g (a i))) ∨
    ∃ x : H, x ≠ 1 ∧ Coproduct.inr x ∈
      Subgroup.normalClosure (Set.range fun i => relator f g (a i)) := by
  rw [normalClosure_relators_eq_of_closure_range_eq_top f g a ha]
  exact exists_witness_of_not_amalgamableOver f g h

/-- Precomposing the common base maps preserves any existing amalgam.

Paper-ID: main.model_companion
TeX: T3_modelcompanion_v4.tex, applying `thm:main` to an embedded copy of the finite base.
-/
theorem AmalgamableOver.precomp {A' : Type*} [Group A'] (e : A' →* A)
    (h : AmalgamableOver f g) : AmalgamableOver (f.comp e) (g.comp e) := by
  obtain ⟨K, hK, hpow, i, j, hi, hj, hij⟩ := h
  refine ⟨K, hK, hpow, i, j, hi, hj, ?_⟩
  exact congrArg (fun k : A →* K => k.comp e) hij

/-- Replacing the common base by a surjective parametrization preserves amalgamability.
In particular this applies to the isomorphism onto the base's image in a model.

Paper-ID: main.model_companion
TeX: T3_modelcompanion_v4.tex, applying `thm:main` to an embedded copy of the finite base.
-/
theorem amalgamableOver_precomp_iff {A' : Type*} [Group A'] (e : A' →* A)
    (he : Function.Surjective e) :
    AmalgamableOver (f.comp e) (g.comp e) ↔ AmalgamableOver f g := by
  refine ⟨?_, AmalgamableOver.precomp f g e⟩
  rintro ⟨K, hK, hpow, i, j, hi, hj, hij⟩
  refine ⟨K, hK, hpow, i, j, hi, hj, ?_⟩
  ext a
  obtain ⟨b, rfl⟩ := he a
  exact DFunLike.congr_fun hij b

end T3.Amalgamation
