/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
module

public import Mathlib.GroupTheory.Commutator.Basic
public import Mathlib.GroupTheory.Exponent

/-!
# Groups of exponent dividing three

The paper calls a group an exponent-three group when every element has cube one. In particular,
the trivial group satisfies the condition. This file connects that convention to mathlib's
`Monoid.exponent`. It also defines the subgroup generated by commutators of two sets,
as in the notation preceding the paper's group identities.

Paper-ID: preliminaries.exponent_three
TeX: T3_modelcompanion_v9.tex, unnumbered opening of Section 2, lines 230–236.
-/

@[expose] public section

namespace T3

/-- Every element of the group has cube one; the trivial group is included.

Paper-ID: preliminaries.exponent_three
TeX: T3_modelcompanion_v9.tex, unnumbered opening of Section 2, lines 230–236.
-/
def HasExponentThree (G : Type*) [Group G] : Prop := ∀ g : G, g ^ 3 = 1

/-- The paper's exponent-three condition says that the group exponent divides three.

Paper-ID: preliminaries.exponent_three
TeX: T3_modelcompanion_v9.tex, unnumbered opening of Section 2, lines 230–236.
-/
theorem hasExponentThree_iff_exponent_dvd {G : Type*} [Group G] :
    HasExponentThree G ↔ Monoid.exponent G ∣ 3 :=
  Monoid.exponent_dvd_iff_forall_pow_eq_one.symm

/-- A trivial group satisfies the exponent-three condition.

Paper-ID: preliminaries.exponent_three
TeX: T3_modelcompanion_v9.tex, unnumbered opening of Section 2, lines 230–236.
-/
theorem hasExponentThree_of_subsingleton (G : Type*) [Group G] [Subsingleton G] :
    HasExponentThree G := fun _ => Subsingleton.elim _ _

open scoped commutatorElement

/-- The subgroup generated by commutators of elements from two specified sets.

Paper-ID: preliminaries.set_commutator
TeX: T3_modelcompanion_v9.tex, lines 418–419; the set notation used in
`fact:elementary equations`, v9 Fact 2.15, items 10 and 11.
-/
def commutatorOfSets {G : Type*} [Group G] (A B : Set G) : Subgroup G :=
  Subgroup.closure {g : G | ∃ a ∈ A, ∃ b ∈ B, ⁅a, b⁆ = g}

/-- A commutator with arguments in the specified sets belongs to their generated subgroup.

Paper-ID: preliminaries.set_commutator
TeX: T3_modelcompanion_v9.tex, lines 418–419; the set notation used in
`fact:elementary equations`, v9 Fact 2.15, items 10 and 11.
-/
theorem commutator_mem_commutatorOfSets {G : Type*} [Group G] {A B : Set G}
    {a b : G} (ha : a ∈ A) (hb : b ∈ B) : ⁅a, b⁆ ∈ commutatorOfSets A B :=
  Subgroup.subset_closure ⟨a, ha, b, hb, rfl⟩

/-- The commutator subgroup generated by any two sets lies in the derived subgroup.

Paper-ID: preliminaries.elementary_identities
TeX: T3_modelcompanion_v9.tex, `fact:elementary equations`,
v9 Fact 2.15, supporting lemma for items 10 and 11.
-/
theorem commutatorOfSets_le_commutator {G : Type*} [Group G] (A B : Set G) :
    commutatorOfSets A B ≤ commutator G := by
  apply (commutator G).closure_le.mpr
  rintro _ ⟨a, _, b, _, rfl⟩
  exact Subgroup.commutator_mem_commutator (Subgroup.mem_top a) (Subgroup.mem_top b)

end T3
