/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
module

public import T3.GroupTheory.Amalgamation
public import T3.GroupTheory.Presentation
public import T3.GroupTheory.Free.ModelComparison
public import Mathlib.GroupTheory.SpecificGroups.Cyclic
public import Mathlib.LinearAlgebra.Dual.Lemmas
public import Mathlib.Algebra.Field.ZMod

/-!
# Amalgamation over a cyclic subgroup

A nontrivial cyclic subgroup generated by `a` can be identified with the first free
factor of a free group of rank three precisely when `a` survives abelianization.
The positive direction constructs a linear functional on the first graded layer,
a retraction onto the cyclic subgroup, and the paper's direct-product amalgam.

Paper-ID: examples.cyclic_amalgamation
TeX: T3_modelcompanion_v7.tex, `lemma:amalgam over the cyclic group`, Lemma 5.4.
-/

@[expose] public section

open scoped commutatorElement

namespace T3.Amalgamation

variable {G : Type*} [Group G]

/-- The distinguished generator of the cyclic subgroup generated by `a`.

Paper-ID: examples.cyclic_amalgamation
TeX: T3_modelcompanion_v7.tex, `lemma:amalgam over the cyclic group`, Lemma 5.4.
-/
def cyclicGenerator (a : G) : Subgroup.zpowers a := ⟨a, Subgroup.mem_zpowers a⟩

/-- The distinguished element generates its cyclic subgroup.

Paper-ID: examples.cyclic_amalgamation
TeX: T3_modelcompanion_v7.tex, `lemma:amalgam over the cyclic group`, Lemma 5.4.
-/
theorem cyclicGenerator_generates (a : G) (x : Subgroup.zpowers a) :
    x ∈ Subgroup.zpowers (cyclicGenerator a) := by
  obtain ⟨n, hn⟩ := x.property
  exact ⟨n, Subtype.ext hn⟩

/-- Every nontrivial element of an exponent-three group has order three.

Paper-ID: examples.cyclic_amalgamation
TeX: T3_modelcompanion_v7.tex, `lemma:amalgam over the cyclic group`, Lemma 5.4.
-/
theorem orderOf_eq_three (hG : HasExponentThree G) {a : G} (ha : a ≠ 1) :
    orderOf a = 3 := by
  have hd := orderOf_dvd_of_pow_eq_one (hG a)
  rcases (Nat.dvd_prime (by decide : Nat.Prime 3)).mp hd with h | h
  · exact (ha (orderOf_eq_one_iff.mp h)).elim
  · exact h

/-- Identification of the cyclic subgroup with the first free generator.

Paper-ID: examples.cyclic_amalgamation
TeX: T3_modelcompanion_v7.tex, `lemma:amalgam over the cyclic group`, Lemma 5.4.
-/
noncomputable def cyclicToFreeThree (hG : HasExponentThree G) (a : G) (ha : a ≠ 1) :
    Subgroup.zpowers a →* Free (Fin 3) :=
  monoidHomOfForallMemZpowers (cyclicGenerator_generates a) (g' := Free.of 0) (by
    rw [← orderOf_injective (Subgroup.zpowers a).subtype Subtype.val_injective,
      show ((Subgroup.zpowers a).subtype (cyclicGenerator a)) = a from rfl,
      orderOf_eq_three hG ha]
    exact orderOf_dvd_of_pow_eq_one (Free.pow_three _))

/-- The cyclic identification sends `a` to the prescribed generator.

Paper-ID: examples.cyclic_amalgamation
TeX: T3_modelcompanion_v7.tex, `lemma:amalgam over the cyclic group`, Lemma 5.4.
-/
@[simp]
theorem cyclicToFreeThree_generator (hG : HasExponentThree G) (a : G) (ha : a ≠ 1) :
    cyclicToFreeThree hG a ha (cyclicGenerator a) = Free.of 0 :=
  monoidHomOfForallMemZpowers_apply_gen _ _

/-- The canonical identification embeds the cyclic subgroup into the free group.

Paper-ID: examples.cyclic_amalgamation
TeX: T3_modelcompanion_v7.tex, `lemma:amalgam over the cyclic group`, Lemma 5.4.
-/
theorem cyclicToFreeThree_injective (hG : HasExponentThree G) (a : G) (ha : a ≠ 1) :
    Function.Injective (cyclicToFreeThree hG a ha) := by
  let r : Free (Fin 3) →* Subgroup.zpowers a :=
    Free.lift (fun x => Subtype.ext (hG x))
      (fun k => if k = 0 then cyclicGenerator a else 1)
  have hr : r.comp (cyclicToFreeThree hG a ha) = MonoidHom.id _ := by
    apply (MonoidHom.eq_iff_eq_on_generator (cyclicGenerator_generates a) _ _).mpr
    simp [r]
  exact (show Function.LeftInverse r (cyclicToFreeThree hG a ha) from
    fun x => DFunLike.congr_fun hr x).injective

/-- An element surviving abelianization generates a retract, obtained from a linear
functional on the first graded layer.

Paper-ID: examples.cyclic_amalgamation
TeX: T3_modelcompanion_v7.tex, `lemma:amalgam over the cyclic group`, Lemma 5.4.
-/
theorem exists_cyclic_retraction (hG : HasExponentThree G) (a : G)
    (ha : a ∉ commutator G) :
    ∃ r : G →* Subgroup.zpowers a, r.comp (Subgroup.zpowers a).subtype = MonoidHom.id _ := by
  let : Fact (HasExponentThree G) := ⟨hG⟩
  let : Fact (Nat.Prime 3) := ⟨by decide⟩
  have ha' : AssociatedGraded.mk G 1 ⟨a, Subgroup.mem_top _⟩ ≠ 0 := by
    simpa only [ne_eq, AssociatedGraded.mk_eq_zero, Subgroup.top_lowerCentralSeries_one] using ha
  obtain ⟨l, hl⟩ := Module.Projective.exists_dual_eq_one (ZMod 3) ha'
  have ha1 : a ≠ 1 := fun h => ha (h ▸ (commutator G).one_mem)
  have hc : Nat.card (Subgroup.zpowers a) = 3 := by
    rw [Nat.card_zpowers, orderOf_eq_three hG ha1]
  let e : Multiplicative (ZMod 3) ≃* Subgroup.zpowers a :=
    zmodMulEquivOfGenerator (cyclicGenerator_generates a) hc
  let q : G →* Multiplicative (ZMod 3) :=
    l.toAddMonoidHom.toMultiplicative.comp (AssociatedGraded.quotientOne G)
  refine ⟨e.toMonoidHom.comp q, ?_⟩
  apply (MonoidHom.eq_iff_eq_on_generator (cyclicGenerator_generates a) _ _).mpr
  change e (Multiplicative.ofAdd (l (AssociatedGraded.mk G 1 ⟨a, Subgroup.mem_top _⟩))) = _
  rw [hl]
  exact zmodMulEquivOfGenerator_apply_ofAdd_one _ _

/-- Two retractions onto a common group give the direct-product amalgam used in the paper.

Paper-ID: examples.cyclic_amalgamation
TeX: T3_modelcompanion_v7.tex, `lemma:amalgam over the cyclic group`, Lemma 5.4.
-/
theorem amalgamableOver_of_retractions {A H : Type*} [Group A] [Group H]
    (hG : HasExponentThree G) (hH : HasExponentThree H)
    (f : A →* G) (g : A →* H) (rG : G →* A) (rH : H →* A)
    (hGret : rG.comp f = MonoidHom.id _) (hHret : rH.comp g = MonoidHom.id _) :
    AmalgamableOver f g := by
  let i : G →* G × H := (MonoidHom.id G).prod (g.comp rG)
  let j : H →* G × H := (f.comp rH).prod (MonoidHom.id H)
  apply amalgamableOver_of_amalgam f g (K := G × H)
    (fun x => Prod.ext (hG x.1) (hH x.2)) i j
  · exact fun x y h => congrArg Prod.fst h
  · exact fun x y h => congrArg Prod.snd h
  · apply MonoidHom.ext
    intro x
    apply Prod.ext
    · exact (congrArg f (DFunLike.congr_fun hHret x)).symm
    · exact congrArg g (DFunLike.congr_fun hGret x)

/-- A derived element has trivial triple commutators in every exponent-three extension.

Paper-ID: examples.cyclic_amalgamation
TeX: T3_modelcompanion_v7.tex, `lemma:amalgam over the cyclic group`, Lemma 5.4.
-/
theorem triple_eq_one_of_mem_commutator (hG : HasExponentThree G) {a : G}
    (ha : a ∈ commutator G) (b c : G) : ⁅⁅a, b⁆, c⁆ = 1 := by
  exact (Subgroup.mem_center_iff.mp (commutator_mem_center_of_mem_commutator hG ha b) c).symm
    |> commutatorElement_eq_one_iff_mul_comm.mpr

/-- The cyclic amalgamation criterion with an explicitly specified identification.

Paper-ID: examples.cyclic_amalgamation
TeX: T3_modelcompanion_v7.tex, `lemma:amalgam over the cyclic group`, Lemma 5.4.
-/
theorem cyclic_amalgamableOver_iff (hG : HasExponentThree G) (a : G)
    (f : Subgroup.zpowers a →* Free (Fin 3))
    (hf : f (cyclicGenerator a) = Free.of 0) :
    AmalgamableOver (Subgroup.zpowers a).subtype f ↔ a ∉ commutator G := by
  constructor
  · rintro ⟨K, hK, hpow, i, j, hi, hj, hij⟩ ha
    let : Group K := hK
    have hia : i a = j (Free.of 0) := by
      have h := DFunLike.congr_fun hij (cyclicGenerator a)
      change i a = j (f (cyclicGenerator a)) at h
      exact h.trans (congrArg j hf)
    have hmap : (commutator G).map i ≤ commutator K := by
      rw [commutator_def, Subgroup.map_commutator, commutator_def]
      exact Subgroup.commutator_mono le_top le_top
    have ham : i a ∈ commutator K := hmap (Subgroup.mem_map_of_mem i ha)
    have ht := triple_eq_one_of_mem_commutator hpow ham (j (Free.of 1)) (j (Free.of 2))
    rw [hia, ← map_commutatorElement, ← map_commutatorElement, ← map_one j] at ht
    exact Free.triple_commutator_of_ne_one (by decide : (0 : Fin 3) ≠ 1)
      (by decide : (0 : Fin 3) ≠ 2) (by decide : (1 : Fin 3) ≠ 2) (hj ht)
  · intro ha
    obtain ⟨r, hr⟩ := exists_cyclic_retraction hG a ha
    let s : Free (Fin 3) →* Subgroup.zpowers a :=
      Free.lift (fun x => Subtype.ext (hG x)) (fun k => if k = 0 then cyclicGenerator a else 1)
    apply amalgamableOver_of_retractions hG Free.pow_three _ f r s hr
    apply (MonoidHom.eq_iff_eq_on_generator (cyclicGenerator_generates a) _ _).mpr
    simp [s, hf]

/-- A nontrivial cyclic subgroup amalgamates with the indicated free group exactly when its
nontrivial generator does not belong to the derived subgroup.

Paper-ID: examples.cyclic_amalgamation
TeX: T3_modelcompanion_v7.tex, `lemma:amalgam over the cyclic group`, Lemma 5.4.
-/
theorem cyclicToFreeThree_amalgamableOver_iff (hG : HasExponentThree G) (a : G) (ha : a ≠ 1) :
    AmalgamableOver (Subgroup.zpowers a).subtype (cyclicToFreeThree hG a ha) ↔
      a ∉ commutator G :=
  cyclic_amalgamableOver_iff hG a _ (cyclicToFreeThree_generator hG a ha)

/-- The cyclic criterion with the base subgroup kept in a fixed ambient group.

Paper-ID: examples.cyclic_amalgamation
TeX: T3_modelcompanion_v7.tex, `lemma:amalgam over the cyclic group`, Lemma 5.4.
-/
theorem cyclic_subgroup_amalgamableOver_iff (hG : HasExponentThree G) (a : G)
    (D : Subgroup G) (haD : a ∈ D) (f : Subgroup.zpowers a →* Free (Fin 3))
    (hf : f (cyclicGenerator a) = Free.of 0) :
    AmalgamableOver (Subgroup.inclusion (Subgroup.zpowers_le.mpr haD)) f ↔
      (⟨a, haD⟩ : D) ∉ commutator D := by
  let d : D := ⟨a, haD⟩
  let e : Subgroup.zpowers d →* Subgroup.zpowers a :=
    (D.subtype.comp (Subgroup.zpowers d).subtype).codRestrict _ (fun x => by
      obtain ⟨n, hn⟩ := x.property
      exact ⟨n, congrArg Subtype.val hn⟩)
  let q : Subgroup.zpowers a →* Subgroup.zpowers d :=
    (Subgroup.inclusion (Subgroup.zpowers_le.mpr haD)).codRestrict _ (fun x => by
      obtain ⟨n, hn⟩ := x.property
      exact ⟨n, Subtype.ext hn⟩)
  have heq : e.comp q = MonoidHom.id _ := by ext x; rfl
  have hq : (Subgroup.zpowers d).subtype.comp q =
      Subgroup.inclusion (Subgroup.zpowers_le.mpr haD) := by ext x; rfl
  have hD : HasExponentThree D := fun x => Subtype.ext (hG x)
  have hc := cyclic_amalgamableOver_iff hD d (f.comp e) hf
  constructor
  · rintro ⟨K, hK, hpow, i, j, hi, hj, hij⟩
    apply hc.mp
    let : Group K := hK
    apply amalgamableOver_of_amalgam _ _ hpow i j hi hj
    exact congrArg (fun p => p.comp e) hij
  · intro ha
    obtain ⟨K, hK, hpow, i, j, hi, hj, hij⟩ := hc.mpr ha
    let : Group K := hK
    apply amalgamableOver_of_amalgam _ _ hpow i j hi hj
    have hh := congrArg (fun p => p.comp q) hij
    simpa only [MonoidHom.comp_assoc, heq, hq, MonoidHom.comp_id] using hh

end T3.Amalgamation
