/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
module

public import T3.ModelTheory.Amalgamation
public import T3.ModelTheory.ExistentialWitness
public import T3.ModelTheory.LocallyFinite
public import T3.ModelTheory.ModelCompanionCriterion

/-!
# The necessary bounded-amalgamation condition for a model companion

For each finite inclusion, syntactic model completeness rewrites the negation of its extension
formula as an existential formula. Its fixed witness bound, plus the size of the base, bounds
the total number of generators of an obstruction inside any existentially closed model.
The obstruction is finite when the original theory is locally finite.

This proves the necessity direction of Fact 2.6 for arbitrary Pi-two theories in finite
languages. The finite structures need not be models of the theory and may be empty. Bounds are
chosen before the existentially closed model and its marking. The converse criterion is not
asserted here.

Paper-ID: model_theory.bounded_amalgamation_criterion
TeX: T3_modelcompanion_v9.tex, `fact:locally finiteness and model companion`, lines 308–337.
-/

@[expose] public section

open scoped FirstOrder

universe u v w w'

namespace FirstOrder.Language

variable {L : Language.{u, v}}

namespace Substructure

/-- A substructure is generated by at most `n` elements of its ambient structure.
The closure equality implies that every chosen generator belongs to the substructure.
This counts all generators, including those needed for a marked base.

Paper-ID: model_theory.bounded_amalgamation_criterion
TeX: T3_modelcompanion_v9.tex, `fact:locally finiteness and model companion`, line 318.
-/
def GeneratedByAtMost {M : Type w} [L.Structure M] (C : L.Substructure M) (n : ℕ) : Prop :=
  ∃ s : Finset M, s.card ≤ n ∧ closure L (s : Set M) = C

/-- A substructure with finitely many generators in a model of a locally finite theory is
finite. No model assumption on the substructure is needed.

Paper-ID: model_theory.bounded_amalgamation_criterion
TeX: T3_modelcompanion_v9.tex, `fact:locally finiteness and model companion`, lines 334, 332–335.
-/
theorem GeneratedByAtMost.finite {T : L.Theory} (hT : T.IsLocallyFinite)
    {M : T.ModelType.{u, v, max u v}} {C : L.Substructure M} {n : ℕ}
    (hC : C.GeneratedByAtMost n) : Finite C := by
  obtain ⟨s, _, rfl⟩ := hC
  exact hT M _ s.finite_toSet

end Substructure

namespace Theory

/-- A finite inclusion which occurs inside a model of the theory. Neither finite structure
is required to satisfy the theory or to be nonempty.

Paper-ID: model_theory.bounded_amalgamation_criterion
TeX: T3_modelcompanion_v9.tex, `fact:locally finiteness and model companion`, line 314.
-/
structure FiniteInclusion (T : L.Theory) where
  /-- The finite base structure. -/
  base : Type (max u v)
  /-- The language structure on the base. -/
  [baseStructure : L.Structure base]
  /-- Finiteness of the base. -/
  [finiteBase : Finite base]
  /-- The finite extension structure. -/
  ext : Type (max u v)
  /-- The language structure on the extension. -/
  [extStructure : L.Structure ext]
  /-- Finiteness of the extension. -/
  [finiteExt : Finite ext]
  /-- The embedding of the base in the extension. -/
  incl : base ↪[L] ext
  /-- The extension is a substructure of some model, up to isomorphism. -/
  embeddable : T.Embeddable ext

attribute [instance] FiniteInclusion.baseStructure FiniteInclusion.finiteBase
  FiniteInclusion.extStructure FiniteInclusion.finiteExt

/-- Each finite inclusion has one bound on the total number of generators of obstructions
inside all existentially closed models and over all embeddings of its base.

Paper-ID: model_theory.bounded_amalgamation_criterion
TeX: T3_modelcompanion_v9.tex, `fact:locally finiteness and model companion`, item 2, lines 314–319.
-/
def BoundedAmalgamationObstructions (T : L.Theory) : Prop :=
  ∀ d : FiniteInclusion T, ∃ n : ℕ,
    ∀ (M : T.ModelType.{u, v, max u v}), T.IsExistentiallyClosed M →
      ∀ j : d.base ↪[L] M, ¬ T.AmalgamableOver d.incl j →
        ∃ (C : L.Substructure M) (hj : ∀ a, j a ∈ C), C.GeneratedByAtMost n ∧
          ¬ T.AmalgamableOver d.incl (j.codRestrict C hj)

variable {T Tstar : L.Theory}

/-- A model companion gives one generator bound for every fixed finite inclusion. The bound
is the existential witness bound of the negated extension formula plus the size of the base.
Local finiteness is not needed for this generator bound; it makes the resulting obstruction
finite in the subsequent corollary.

Paper-ID: model_theory.bounded_amalgamation_criterion
TeX: T3_modelcompanion_v9.tex, `fact:locally finiteness and model companion`, lines 327–337.
-/
theorem IsModelCompanionOf.exists_bounded_nonamalgamation_obstruction [Finite L.Symbols]
    (hPi : T.IsPiTwo) (hMC : Tstar.IsModelCompanionOf T)
    {A : Type w} {B : Type w'} [L.Structure A] [L.Structure B] [Finite A] [Finite B]
    (i : A ↪[L] B) :
    ∃ n : ℕ, ∀ (M : T.ModelType.{u, v, max u v}), T.IsExistentiallyClosed M →
      ∀ j : A ↪[L] M, ¬ T.AmalgamableOver i j →
        ∃ (C : L.Substructure M) (hj : ∀ a, j a ∈ C), C.GeneratedByAtMost n ∧
          ¬ T.AmalgamableOver i (j.codRestrict C hj) := by
  classical
  let : Fintype A := Fintype.ofFinite A
  let a := Fintype.card A
  let eA : A ≃ Fin a := Fintype.equivFin A
  let δ : L.Formula (Fin a) := (extensionFormula (L := L) (i : A → B)).relabel eA
  obtain ⟨ψ, hψ, hiff⟩ := hMC.isModelComplete δ.not
  obtain ⟨k, hk⟩ := hψ.exists_bounded_finite_witnesses_formula
  refine ⟨k + a, ?_⟩
  intro M hM j hbad
  let : M ⊨ Tstar := (hMC.models_iff_isExistentiallyClosed hPi M).mpr hM
  let vA : Fin a → M := j ∘ eA.symm
  have hvA : vA ∘ eA = j := by
    funext x
    exact congrArg j (eA.symm_apply_apply x)
  have hnotδ : ¬ δ.Realize vA := by
    intro hδ
    change ((extensionFormula (L := L) (i : A → B)).relabel eA).Realize vA at hδ
    rw [Formula.realize_relabel, hvA] at hδ
    exact hbad ((hM.amalgamableOver_iff_realize_extensionFormula i j).mpr hδ)
  have hψM : ψ.Realize vA := hiff.realize_iff.mp (Formula.realize_not.mpr hnotδ)
  obtain ⟨s, hs, htransfer⟩ := hk M vA hψM
  let t : Finset M := s ∪ Finset.univ.image j
  let C : L.Substructure M := Substructure.closure L (t : Set M)
  have hj : ∀ x, j x ∈ C := fun x =>
    Substructure.subset_closure (Finset.mem_union_right _ (Finset.mem_image_of_mem _
      (Finset.mem_univ x)))
  refine ⟨C, hj, ⟨t, ?_, rfl⟩, ?_⟩
  · exact (Finset.card_union_le _ _).trans (add_le_add hs
      (Finset.card_image_le.trans (by simp [a])))
  · intro hbadC
    obtain ⟨N₀, f, g, hcomm⟩ := hbadC
    obtain ⟨N, ⟨e⟩⟩ := hMC.isCompanion.2 N₀
    let vC : Fin a → C := j.codRestrict C hj ∘ eA.symm
    have hvC : vC ∘ eA = j.codRestrict C hj := by
      funext x
      exact congrArg (j.codRestrict C hj) (eA.symm_apply_apply x)
    have hsC : (s : Set M) ⊆ Set.range C.subtype := fun x hx =>
      ⟨⟨x, Substructure.subset_closure (Finset.mem_union_left _ hx)⟩, rfl⟩
    have hψC : ψ.Realize vC := htransfer C C.subtype hsC vC rfl
    have hψN : ψ.Realize ((e.comp g) ∘ vC) :=
      hψ.realize_formula_embedding (e.comp g) hψC
    have hδN : δ.Realize ((e.comp g) ∘ vC) := by
      change ((extensionFormula (L := L) (i : A → B)).relabel eA).Realize _
      rw [Formula.realize_relabel, Function.comp_assoc, hvC]
      apply (realize_extensionFormula_iff _ _).mpr
      refine ⟨e.comp f, ?_⟩
      funext x
      exact congrArg e (DFunLike.congr_fun hcomm x)
    exact (Formula.realize_not.mp (hiff.realize_iff.mpr hψN)) hδN

/-- **Fact 2.6, necessity.** A model companion of a Pi-two theory in a finite language supplies
the bounded-obstruction condition. The obstruction is generated by a bounded total number of
elements, rather than by a bounded number of elements in addition to the base.

Paper-ID: model_theory.bounded_amalgamation_criterion
TeX: T3_modelcompanion_v9.tex, `fact:locally finiteness and model companion`, implication 1 → 2.
-/
theorem HasModelCompanion.boundedAmalgamationObstructions [Finite L.Symbols]
    (hPi : T.IsPiTwo) (h : T.HasModelCompanion) : T.BoundedAmalgamationObstructions := by
  obtain ⟨Tstar, hMC⟩ := h
  intro d
  exact hMC.exists_bounded_nonamalgamation_obstruction hPi d.incl

/-- In a locally finite theory, the uniformly generated obstructions supplied by a model
companion are finite structures. They are not required to satisfy the theory.

Paper-ID: model_theory.bounded_amalgamation_criterion
TeX: T3_modelcompanion_v9.tex, `fact:locally finiteness and model companion`, lines 314–337.
-/
theorem HasModelCompanion.exists_finite_bounded_nonamalgamation_obstruction [Finite L.Symbols]
    (hPi : T.IsPiTwo) (hLF : T.IsLocallyFinite) (h : T.HasModelCompanion)
    (d : FiniteInclusion T) :
    ∃ n : ℕ, ∀ (M : T.ModelType.{u, v, max u v}), T.IsExistentiallyClosed M →
      ∀ j : d.base ↪[L] M, ¬ T.AmalgamableOver d.incl j →
        ∃ (C : L.Substructure M) (hj : ∀ a, j a ∈ C), Finite C ∧ C.GeneratedByAtMost n ∧
          ¬ T.AmalgamableOver d.incl (j.codRestrict C hj) := by
  obtain ⟨n, hn⟩ := h.boundedAmalgamationObstructions hPi d
  refine ⟨n, ?_⟩
  intro M hM j hj
  obtain ⟨C, hC, hgen, hbad⟩ := hn M hM j hj
  exact ⟨C, hC, hgen.finite hLF, hgen, hbad⟩

end Theory

end FirstOrder.Language
