/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
module

public import T3.ModelTheory.GroupLanguage
public import T3.ModelTheory.BoundedAmalgamationCriterion
public import T3.GroupTheory.Free.Collection

/-!
# The first-order theory of groups of exponent three

The paper's `Tₙ` is the group theory together with the single universal law `xⁿ = 1`.
In particular `T₃` includes the trivial group. The group language is finite and all these
theories are universal, hence Pi-two.

For local finiteness, the free exponent-three group on a finite generating set is finite by
the collected normal-form bound. Its image is the subgroup generated by that set. The group
language identifies this subgroup with the first-order generated substructure. No finiteness
assumption is made on the ambient group, and the algebraic result holds in arbitrary universes.

The final theorem specializes Fact 2.6 to `T₃`; existence of a model companion still requires
the bounded-amalgamation-obstruction hypothesis furnished by the paper's main theorem.

The power-term and theory definitions and the finite-closure proof reuse earlier
formalization by Yawara Ishida, with the current paper's free group
and finiteness theorem.

Paper-ID: preliminaries.exponent_three, main.model_companion
TeX: T3_modelcompanion_v4.tex, lines 136–142 and 742–745.
-/

@[expose] public section

open scoped FirstOrder

namespace FirstOrder.Group

open Language

variable {α : Type*}

/-- The group-language term for the natural power of a term.

Paper-ID: preliminaries.exponent_three
TeX: T3_modelcompanion_v4.tex, the sentence defining `Tₙ`, lines 138–141.
-/
def powerTerm (n : ℕ) (t : Language.group.Term α) : Language.group.Term α :=
  match n with
  | 0 => 1
  | n + 1 => powerTerm n t * t

/-- Realizing the power term gives the corresponding group power.

Paper-ID: preliminaries.exponent_three
TeX: T3_modelcompanion_v4.tex, the exponent law, lines 138–142.
-/
@[simp]
theorem realize_powerTerm {G : Type*} [Group G] [CompatibleGroup G]
    (n : ℕ) (t : Language.group.Term α) (a : α → G) :
    Term.realize a (powerTerm n t) = Term.realize a t ^ n := by
  induction n with
  | zero => simp [powerTerm]
  | succ n ih => simp [powerTerm, ih, pow_succ]

/-- The universal sentence saying that every element has `n`-th power equal to one.

Paper-ID: preliminaries.exponent_three
TeX: T3_modelcompanion_v4.tex, the definition of `Tₙ`, lines 138–141.
-/
def exponentSentence (n : ℕ) : Language.group.Sentence :=
  ∀' ((powerTerm n &0) =' (1 : Language.group.Term _))

/-- The exponent sentence has exactly the paper's exponent-dividing interpretation.

Paper-ID: preliminaries.exponent_three
TeX: T3_modelcompanion_v4.tex, the convention including the trivial group, line 142.
-/
theorem realize_exponentSentence_iff {G : Type*} [Group G] [CompatibleGroup G] (n : ℕ) :
    G ⊨ exponentSentence n ↔ ∀ x : G, x ^ n = 1 := by
  simp [exponentSentence, Sentence.Realize, Formula.Realize, Fin.snoc]

/-- The exponent law is a universal sentence.

Paper-ID: preliminaries.exponent_three
TeX: T3_modelcompanion_v4.tex, lines 138–141.
-/
theorem exponentSentence_isUniversal (n : ℕ) : (exponentSentence n).IsUniversal :=
  (BoundedFormula.IsAtomic.equal _ _).isUniversal.all

end FirstOrder.Group

namespace T3

open FirstOrder FirstOrder.Language

/-- The group theory together with `∀ x, xⁿ = 1`. For `n > 1` this is the paper's `Tₙ`.

Paper-ID: preliminaries.exponent_three
TeX: T3_modelcompanion_v4.tex, definition of `Tₙ`, lines 136–142.
-/
def exponentGroupTheory (n : ℕ) : Language.group.Theory :=
  insert (FirstOrder.Group.exponentSentence n) Language.Theory.group

/-- The theory `Tₙ` is universally axiomatized.

Paper-ID: preliminaries.exponent_three
TeX: T3_modelcompanion_v4.tex, group and exponent laws, lines 136–142.
-/
instance (n : ℕ) : (exponentGroupTheory n).IsUniversal :=
  Theory.IsUniversal.insert (FirstOrder.Group.exponentSentence_isUniversal n)

/-- A compatible group models `Tₙ` precisely when every element has `n`-th power one.

Paper-ID: preliminaries.exponent_three
TeX: T3_modelcompanion_v4.tex, the exponent convention, line 142.
-/
theorem exponentGroupTheory_model_iff {G : Type*} [Group G]
    [FirstOrder.Group.CompatibleGroup G] (n : ℕ) :
    G ⊨ exponentGroupTheory n ↔ ∀ x : G, x ^ n = 1 := by
  rw [exponentGroupTheory, Theory.model_insert_iff, FirstOrder.Group.realize_exponentSentence_iff]
  exact ⟨And.left, fun h => ⟨h, inferInstance⟩⟩

/-- The first-order theory `T₃` from the paper.

Paper-ID: preliminaries.exponent_three
TeX: T3_modelcompanion_v4.tex, lines 136–142.
-/
abbrev exponentThreeTheory : Language.group.Theory := exponentGroupTheory 3

/-- The first-order and algebraic formulations of exponent three agree, including the
trivial group and groups of arbitrary cardinality.

Paper-ID: preliminaries.exponent_three
TeX: T3_modelcompanion_v4.tex, line 142 and Notation 2.1, item 4.
-/
theorem exponentThreeTheory_model_iff {G : Type*} [Group G]
    [FirstOrder.Group.CompatibleGroup G] : G ⊨ exponentThreeTheory ↔ HasExponentThree G :=
  exponentGroupTheory_model_iff 3

/-- The universal axiomatization of `T₃` supplies the Pi-two hypothesis of Fact 2.6.

Paper-ID: preliminaries.exponent_three, main.model_companion
TeX: T3_modelcompanion_v4.tex, applying Fact 2.6 on line 742.
-/
theorem exponentThreeTheory_isPiTwo : exponentThreeTheory.IsPiTwo :=
  Theory.IsUniversal.isPiTwo

/-- Finitely many free exponent-three generators give a finite group, regardless of the
choice of an order on the generator type.

Paper-ID: preliminaries.finite_normal_form, model_theory.local_finiteness
TeX: T3_modelcompanion_v4.tex, Fact 2.27 and its application to local finiteness.
-/
theorem finite_free_of_finite (I : Type*) [Finite I] : Finite (Free I) := by
  classical
  letI : LinearOrder I := linearOrderOfSTO WellOrderingRel
  exact Free.finite

/-- Every finitely generated subgroup of an exponent-three group is finite, via the image
of the free group on its given finite generating set.

Paper-ID: model_theory.local_finiteness, preliminaries.finite_normal_form
TeX: T3_modelcompanion_v4.tex, Definition 2.4 and the finite free-group theorem, Fact 2.27.
-/
theorem finite_closure_of_exponent_three {G : Type*} [Group G] (hG : HasExponentThree G)
    {s : Set G} (hs : s.Finite) : Finite (Subgroup.closure s) := by
  letI : Finite s := hs.to_subtype
  letI : Finite (Free s) := finite_free_of_finite s
  let f : Free s →* G := Free.lift hG Subtype.val
  have hcoe : f ∘ Free.of = (Subtype.val : s → G) :=
    funext fun z => Free.lift_of hG Subtype.val z
  have hrange : f.range = Subgroup.closure s := by
    rw [MonoidHom.range_eq_map, ← Free.closure_range_of (I := s),
      MonoidHom.map_closure, ← Set.range_comp, hcoe, Subtype.range_coe]
  have hfin : Finite f.range := Finite.of_surjective f.rangeRestrict f.rangeRestrict_surjective
  rwa [hrange] at hfin

/-- In every universe, a finite set in a first-order model of `T₃` generates a finite
substructure. The group structure is recovered from the model's given operations.

Paper-ID: model_theory.local_finiteness, main.model_companion
TeX: T3_modelcompanion_v4.tex, Definition 2.4 and the application of Fact 2.6, line 742.
-/
theorem finite_substructure_closure_of_model_exponentThreeTheory
    {M : Type*} [Language.group.Structure M] [hM : M ⊨ exponentThreeTheory]
    {s : Set M} (hs : s.Finite) : Finite (Substructure.closure Language.group s) := by
  letI : M ⊨ Theory.group := hM.mono (fun _ h => Set.mem_insert_of_mem _ h)
  letI : Group M := FirstOrder.Group.groupOfModelGroup M
  letI : FirstOrder.Group.CompatibleGroup M := FirstOrder.Group.compatibleGroupOfGroupStructure M
  have hpow : HasExponentThree M := exponentThreeTheory_model_iff.mp hM
  letI : Finite (Subgroup.closure s) := finite_closure_of_exponent_three hpow hs
  exact Finite.of_equiv (Subgroup.closure s)
    (Equiv.setCongr (FirstOrder.Group.coe_substructure_closure_eq s)).symm

/-- The theory `T₃` is locally finite in the first-order sense. This provides the remaining
hypothesis for applying the general bounded-amalgamation criterion.

Paper-ID: model_theory.local_finiteness, main.model_companion
TeX: T3_modelcompanion_v4.tex, Definition 2.4 and the application of Fact 2.6, line 742.
-/
theorem exponentThreeTheory_isLocallyFinite : exponentThreeTheory.IsLocallyFinite :=
  fun _ _ hs => finite_substructure_closure_of_model_exponentThreeTheory hs

/-- The general bounded-amalgamation criterion specialized to the paper's theory `T₃`.
The model-companion conclusion still requires the bounded obstruction condition.

Paper-ID: main.model_companion
TeX: T3_modelcompanion_v4.tex, the deduction from Fact 2.6, lines 742–745.
-/
theorem exponentThreeTheory_hasModelCompanion_iff :
    exponentThreeTheory.HasModelCompanion ↔ exponentThreeTheory.BoundedAmalgamationObstructions :=
  Theory.hasModelCompanion_iff_boundedAmalgamationObstructions
    exponentThreeTheory_isPiTwo exponentThreeTheory_isLocallyFinite

/-- Bounded amalgamation obstructions imply the existence of a model companion of `T₃`.
This is the final model-theoretic implication, conditional on the paper's group-theoretic bound.

Paper-ID: main.model_companion
TeX: T3_modelcompanion_v4.tex, lines 742–745.
-/
theorem exponentThreeTheory_hasModelCompanion_of_boundedAmalgamationObstructions
    (h : exponentThreeTheory.BoundedAmalgamationObstructions) :
    exponentThreeTheory.HasModelCompanion :=
  exponentThreeTheory_hasModelCompanion_iff.mpr h

end T3
