/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
module

public import T3.ModelTheory.LocallyFinite
public import Mathlib.SetTheory.Cardinal.Finite

/-!
# Uniform bounds for locally finite theories

Every finite tuple in a model of a locally finite theory has a finite generated substructure.
In a finite language its quantifier-free diagram is represented by one formula. Compactness
chooses finitely many such formulas covering all tuples of a fixed length in all models.
Taking the maximum of the sizes of their generated substructures gives a uniform bound.

The same finite family of types gives finitely many truth vectors for quantifier-free formulas.
This yields a finite set of representatives up to equivalence over the theory, including a
finite representative subset of any tuple's full quantifier-free diagram.

The finite substructures need not be models of the theory. As in `Theory.IsLocallyFinite`,
the models quantified over are in the canonical semantic universe `max u v`.

Paper-ID: model_theory.uniform_local_finiteness
TeX: T3_modelcompanion_v4.tex, Fact 2.5, lines 209–212; no label.
The finite-representative consequence is Definition 2.2, item 6, lines 192–193.
-/

@[expose] public section

open scoped FirstOrder

universe u v w w'

namespace FirstOrder.Language

variable {L : Language.{u, v}}

/-- The substructure generated by a tuple in the image of a finite structure has cardinality
at most that of the finite structure.

Paper-ID: model_theory.uniform_local_finiteness
TeX: T3_modelcompanion_v4.tex, supporting Fact 2.5; no label.
-/
theorem Substructure.card_closure_range_le_of_embedding {A : Type w} {N : Type w'}
    [L.Structure A] [L.Structure N] [Finite A] {α : Type*} (a : α → A) (f : A ↪[L] N) :
    Nat.card (Substructure.closure L (Set.range (f ∘ a))) ≤ Nat.card A := by
  letI : Finite f.toHom.range := Finite.of_equiv A f.equivRange.toEquiv
  have hle : Substructure.closure L (Set.range (f ∘ a)) ≤ f.toHom.range := by
    apply Substructure.closure_le.mpr
    rintro _ ⟨i, rfl⟩
    exact f.toHom.mem_range_self (a i)
  let g : Substructure.closure L (Set.range (f ∘ a)) → f.toHom.range :=
    fun x => ⟨x, hle x.property⟩
  have hg : Function.Injective g := fun _ _ h =>
    Subtype.ext (congrArg (fun z : f.toHom.range => (z : N)) h)
  exact (Nat.card_le_card_of_injective g hg).trans_eq (Nat.card_congr f.equivRange.toEquiv).symm

/-- A tuple with the same quantifier-free type as one generating a finite substructure
generates a substructure of at most the same cardinality.

Paper-ID: model_theory.uniform_local_finiteness
TeX: T3_modelcompanion_v4.tex, supporting Fact 2.5; no label.
-/
theorem Substructure.card_closure_range_le_of_qfType [Finite L.Symbols]
    {M : Type w} {N : Type w'} [L.Structure M] [L.Structure N]
    {α : Type*} [Finite α] (a : α → M) (b : α → N)
    [Finite (Substructure.closure L (Set.range a))]
    (h : ∀ φ : L.Formula α, φ.IsQF → (φ.Realize b ↔ φ.Realize a)) :
    Nat.card (Substructure.closure L (Set.range b)) ≤
      Nat.card (Substructure.closure L (Set.range a)) := by
  have hδ : (finiteGeneratedDiagram (L := L) a).Realize b :=
    (h _ (finiteGeneratedDiagram_isQF a)).mpr (finiteGeneratedDiagram_mem_tupleQfDiagram a).2
  obtain ⟨f, rfl⟩ := (realize_finiteGeneratedDiagram_iff a b).mp hδ
  exact Substructure.card_closure_range_le_of_embedding (closureTuple a) f

namespace Theory

variable {T : L.Theory}

/-- Finitely many tuples represent all quantifier-free types of `n`-tuples in models of a
locally finite theory in a finite language. Compactness selects them from the finite diagrams.

Paper-ID: model_theory.uniform_local_finiteness
TeX: T3_modelcompanion_v4.tex, Fact 2.5, lines 209–212; no label.
-/
theorem IsLocallyFinite.exists_finite_qfType_cover [Finite L.Symbols]
    (hT : T.IsLocallyFinite) (n : ℕ) :
    ∃ S : Finset (Σ M : T.ModelType.{u, v, max u v}, Fin n → M),
      ∀ (N : T.ModelType.{u, v, max u v}) (b : Fin n → N),
        ∃ p ∈ S, ∀ φ : L.Formula (Fin n), φ.IsQF → (φ.Realize b ↔ φ.Realize p.2) := by
  classical
  let diagram (M : T.ModelType.{u, v, max u v}) (a : Fin n → M) : L.Formula (Fin n) :=
    letI := hT.finite_closure_range M a
    finiteGeneratedDiagram a
  have hdiagram (M : T.ModelType.{u, v, max u v}) (a : Fin n → M) :
      (diagram M a).Realize a := by
    letI := hT.finite_closure_range M a
    exact (finiteGeneratedDiagram_mem_tupleQfDiagram a).2
  let negs : L[[Fin n]].Theory := {σ | ∃ (M : T.ModelType.{u, v, max u v}) (a : Fin n → M),
    σ = (Formula.equivSentence (diagram M a)).not}
  have hfalse : (L.lhomWithConstants (Fin n)).onTheory T ∪ negs ⊨ᵇ (⊥ : L[[Fin n]].Sentence) := by
    apply models_sentence_iff.mpr
    intro M
    letI : L.Structure M := (L.lhomWithConstants (Fin n)).reduct M
    haveI : M ⊨ T := (LHom.onTheory_model _ _).mp
      (M.is_model.mono Set.subset_union_left)
    let a : Fin n → M := fun i => (L.con i : M)
    have hmem : (Formula.equivSentence (diagram (ModelType.of T M) a)).not ∈
        (L.lhomWithConstants (Fin n)).onTheory T ∪ negs :=
      Set.mem_union_right _ ⟨ModelType.of T M, a, rfl⟩
    have hn := M.is_model.realize_of_mem _ hmem
    rw [Sentence.realize_not, Formula.realize_equivSentence] at hn
    exact (hn (hdiagram (ModelType.of T M) a)).elim
  obtain ⟨Ω, hΩ, hforces⟩ := models_iff_finset_models.mp hfalse
  let Δ := Ω.filter (· ∈ negs)
  have hdata : ∀ δ : Δ, ∃ (M : T.ModelType.{u, v, max u v}) (a : Fin n → M),
      δ.val = (Formula.equivSentence (diagram M a)).not :=
    fun δ => (Finset.mem_filter.mp δ.property).2
  choose models tuples heq using hdata
  refine ⟨Finset.univ.image (fun δ : Δ =>
    (⟨models δ, tuples δ⟩ : Σ M : T.ModelType.{u, v, max u v}, Fin n → M)), ?_⟩
  intro N b
  have hcover : ∃ δ : Δ, (diagram (models δ) (tuples δ)).Realize b := by
    by_contra hn
    letI : (constantsOn (Fin n)).Structure N := constantsOn.structure b
    haveI hNT : N ⊨ (L.lhomWithConstants (Fin n)).onTheory T :=
      (LHom.onTheory_model _ _).mpr N.is_model
    haveI : N ⊨ (Ω : L[[Fin n]].Theory) := by
      apply (Theory.model_iff _).mpr
      intro σ hσ
      rcases hΩ hσ with hσT | hσneg
      · exact hNT.realize_of_mem _ hσT
      · have hσΔ : σ ∈ Δ := Finset.mem_filter.mpr ⟨hσ, hσneg⟩
        have hσeq : σ = (Formula.equivSentence
            (diagram (models ⟨σ, hσΔ⟩) (tuples ⟨σ, hσΔ⟩))).not := heq ⟨σ, hσΔ⟩
        rw [hσeq, Sentence.realize_not, Formula.realize_equivSentence]
        exact fun h => hn ⟨⟨σ, hσΔ⟩, h⟩
    exact Sentence.not_realize_bot N (hforces.realize_sentence N)
  obtain ⟨δ, hδ⟩ := hcover
  letI := hT.finite_closure_range (models δ) (tuples δ)
  refine ⟨⟨models δ, tuples δ⟩, Finset.mem_image.mpr ⟨δ, Finset.mem_univ δ, rfl⟩, ?_⟩
  have hall := (realize_finiteGeneratedDiagram_iff_tupleQfDiagram (tuples δ) b).mp hδ
  intro φ hφ
  constructor
  · intro hb
    by_contra hs
    exact hall φ.not ⟨hφ.not, hs⟩ hb
  · exact fun hs => hall φ ⟨hφ, hs⟩

/-- The finite cover of quantifier-free types gives a uniform cardinal bound for generated
substructures of `n`-tuples, by taking the maximum size among the representative tuples.

Paper-ID: model_theory.uniform_local_finiteness
TeX: T3_modelcompanion_v4.tex, Fact 2.5, lines 209–212; no label.
-/
theorem IsLocallyFinite.exists_card_closure_range_le [Finite L.Symbols]
    (hT : T.IsLocallyFinite) (n : ℕ) :
    ∃ m : ℕ, ∀ (M : T.ModelType.{u, v, max u v}) (a : Fin n → M),
      Nat.card (Substructure.closure L (Set.range a)) ≤ m := by
  classical
  obtain ⟨S, hS⟩ := hT.exists_finite_qfType_cover n
  let size (p : Σ M : T.ModelType.{u, v, max u v}, Fin n → M) : ℕ :=
    Nat.card (Substructure.closure L (Set.range p.2))
  refine ⟨S.sup size, ?_⟩
  intro N b
  obtain ⟨⟨M, a⟩, hp, hpb⟩ := hS N b
  letI := hT.finite_closure_range M a
  have hb : Nat.card (Substructure.closure L (Set.range b)) ≤ size ⟨M, a⟩ :=
    Substructure.card_closure_range_le_of_qfType a b hpb
  exact hb.trans (Finset.le_sup (f := size) hp)

/-- For every `n`, one cardinal bound applies to the substructure generated by any subset
of at most `n` elements in any model of a locally finite theory in a finite language.
The finite generated substructure is not assumed to be a model of the theory.

Paper-ID: model_theory.uniform_local_finiteness
TeX: T3_modelcompanion_v4.tex, Fact 2.5, lines 209–212; no label.
-/
theorem exists_card_closure_le_of_isLocallyFinite [Finite L.Symbols]
    (hT : T.IsLocallyFinite) (n : ℕ) :
    ∃ m : ℕ, ∀ (M : T.ModelType.{u, v, max u v}) (s : Finset M),
      s.card ≤ n → Nat.card (Substructure.closure L (s : Set M)) ≤ m := by
  classical
  obtain ⟨m, hm⟩ := hT.exists_card_closure_range_le n
  refine ⟨m, ?_⟩
  intro M s hs
  have hc : Fintype.card s ≤ Fintype.card (Fin n) := by simpa using hs
  obtain ⟨e⟩ := Function.Embedding.nonempty_of_card_le hc
  let b : Fin n → M := Function.extend e ((↑) : s → M) (fun _ => Classical.choice M.nonempty')
  have hsrange : (s : Set M) ⊆ Set.range b := by
    intro x hx
    exact ⟨e ⟨x, hx⟩, e.injective.extend_apply ((↑) : s → M)
      (fun _ => Classical.choice M.nonempty') ⟨x, hx⟩⟩
  letI := hT.finite_closure_range M b
  let f := Substructure.inclusion (Substructure.closure_mono (L := L) hsrange)
  exact (Nat.card_le_card_of_injective f f.injective).trans (hm M b)

/-- There are only finitely many quantifier-free formulas in `n` variables up to equivalence
over a locally finite theory in a finite language. This gives finite representatives for
the equivalence classes, not merely one finite conjunction generating a given diagram.

Paper-ID: model_theory.basic_definitions
TeX: T3_modelcompanion_v4.tex, Definition 2.2, item 6, lines 192–193; no label.
-/
theorem IsLocallyFinite.exists_finite_qf_representatives [Finite L.Symbols]
    (hT : T.IsLocallyFinite) (n : ℕ) :
    ∃ R : Finset (L.Formula (Fin n)), (∀ ψ ∈ R, ψ.IsQF) ∧
      ∀ φ : L.Formula (Fin n), φ.IsQF → ∃ ψ ∈ R, φ ⇔[T] ψ := by
  classical
  obtain ⟨S, hS⟩ := hT.exists_finite_qfType_cover n
  let truth (φ : L.Formula (Fin n)) : S → Bool := fun p => decide (φ.Realize p.val.2)
  let values : Set (S → Bool) := {v | ∃ φ : L.Formula (Fin n), φ.IsQF ∧ truth φ = v}
  have hdata : ∀ v : values, ∃ φ : L.Formula (Fin n), φ.IsQF ∧ truth φ = v.val :=
    fun v => v.property
  choose representative hqf htruth using hdata
  refine ⟨Finset.univ.image representative, ?_, ?_⟩
  · intro ψ hψ
    obtain ⟨v, _, rfl⟩ := Finset.mem_image.mp hψ
    exact hqf v
  · intro φ hφ
    let v : values := ⟨truth φ, φ, hφ, rfl⟩
    refine ⟨representative v, Finset.mem_image.mpr ⟨v, Finset.mem_univ v, rfl⟩, ?_⟩
    intro N a xs
    rw [BoundedFormula.realize_iff]
    obtain ⟨p, hp, hpa⟩ := hS N a
    have he : φ.Realize p.2 ↔ (representative v).Realize p.2 :=
      decide_eq_decide.mp (congrFun (htruth v).symm ⟨p, hp⟩)
    have h := (hpa φ hφ).trans (he.trans (hpa _ (hqf v)).symm)
    simpa only [Formula.Realize, Unique.eq_default xs] using h

/-- The full quantifier-free diagram of a finite tuple is finite modulo the theory in the
sense that every one of its formulas is equivalent over the theory to a member of a fixed
finite subset of that diagram.

Paper-ID: model_theory.basic_definitions
TeX: T3_modelcompanion_v4.tex, Definition 2.2, item 6, lines 185–193; no label.
-/
theorem IsLocallyFinite.exists_finite_tupleQfDiagram_representatives [Finite L.Symbols]
    (hT : T.IsLocallyFinite) (M : T.ModelType.{u, v, max u v}) {n : ℕ} (a : Fin n → M) :
    ∃ Δ : Finset (L.Formula (Fin n)), (Δ : Set (L.Formula (Fin n))) ⊆ tupleQfDiagram (L := L) a ∧
      ∀ φ ∈ tupleQfDiagram (L := L) a, ∃ ψ ∈ Δ, φ ⇔[T] ψ := by
  classical
  obtain ⟨R, hR, hrepresentative⟩ := hT.exists_finite_qf_representatives n
  refine ⟨R.filter (fun ψ => ψ.Realize a), ?_, ?_⟩
  · intro ψ hψ
    have h := Finset.mem_filter.mp hψ
    exact ⟨hR ψ h.1, h.2⟩
  · intro φ hφ
    obtain ⟨ψ, hψ, heq⟩ := hrepresentative φ hφ.1
    exact ⟨ψ, Finset.mem_filter.mpr ⟨hψ, heq.realize_iff.mp hφ.2⟩, heq⟩

end Theory

end FirstOrder.Language
