/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
module

public import T3.GroupTheory.Basic
public import Mathlib.GroupTheory.FreeGroup.Basic

/-!
# Free groups of exponent three

The paper constructs the free exponent-three group on a set as the ordinary free group
modulo the normal subgroup generated by cubes. The power quotient construction below makes
this description explicit and supplies its universal property, including uniqueness and
functoriality. The collected normal form and order formula are proved in later modules.

Paper-ID: preliminaries.notation
TeX: T3_modelcompanion_v4.tex, v4 Notation 2.1, item 9.
-/

@[expose] public section

universe u v

namespace T3

variable (G : Type u) [Group G] (n : ℕ)

/-- The normal subgroup generated by all `n`-th powers in `G`. -/
def powerSubgroup : Subgroup G :=
  Subgroup.normalClosure (Set.range fun g : G ↦ g ^ n)

instance powerSubgroup_normal : (powerSubgroup G n).Normal := by
  unfold powerSubgroup
  infer_instance

/-- Every `n`-th power belongs to `powerSubgroup G n`. -/
theorem pow_mem_powerSubgroup (g : G) : g ^ n ∈ powerSubgroup G n :=
  Subgroup.subset_normalClosure ⟨g, rfl⟩

/-- A normal subgroup contains `powerSubgroup G n` exactly when it contains every `n`-th power. -/
theorem powerSubgroup_le_iff {N : Subgroup G} [N.Normal] :
    powerSubgroup G n ≤ N ↔ ∀ g : G, g ^ n ∈ N := by
  constructor
  · exact fun h g ↦ h (pow_mem_powerSubgroup G n g)
  · exact fun h ↦ Subgroup.normalClosure_le_normal fun _ ⟨g, hg⟩ ↦ hg ▸ h g

variable {G n}

/-- A homomorphism kills `powerSubgroup G n` exactly when all images have `n`-th power one. -/
theorem powerSubgroup_le_ker_iff {H : Type v} [Group H] (f : G →* H) :
    powerSubgroup G n ≤ f.ker ↔ ∀ g : G, f g ^ n = 1 := by
  rw [powerSubgroup_le_iff]
  simp

/-- The quotient of `G` by the normal subgroup generated by its `n`-th powers. -/
abbrev PowerQuotient (G : Type u) [Group G] (n : ℕ) :=
  G ⧸ powerSubgroup G n

/-- The canonical homomorphism to the quotient by `n`-th powers. -/
def powerQuotientMk : G →* PowerQuotient G n :=
  QuotientGroup.mk' (powerSubgroup G n)

/-- The canonical homomorphism to `PowerQuotient G n` is surjective. -/
theorem powerQuotientMk_surjective : Function.Surjective (powerQuotientMk (G := G) (n := n)) :=
  QuotientGroup.mk'_surjective _

/-- The image of every `n`-th power is one in `PowerQuotient G n`. -/
@[simp]
theorem powerQuotientMk_pow_eq_one (g : G) : powerQuotientMk (G := G) (n := n) g ^ n = 1 := by
  rw [← map_pow]
  exact (QuotientGroup.eq_one_iff (g ^ n)).2 (pow_mem_powerSubgroup G n g)

/-- The quotient by `n`-th powers has exponent dividing `n`. -/
theorem powerQuotient_hasExponent : ∀ q : PowerQuotient G n, q ^ n = 1 := by
  intro q
  obtain ⟨g, rfl⟩ := powerQuotientMk_surjective (G := G) (n := n) q
  exact powerQuotientMk_pow_eq_one g

/-- A homomorphism that kills all `n`-th powers descends to `PowerQuotient G n`. -/
def powerQuotientLift {H : Type v} [Group H] (f : G →* H) (h : ∀ g : G, f g ^ n = 1) :
    PowerQuotient G n →* H :=
  QuotientGroup.lift (powerSubgroup G n) f ((powerSubgroup_le_ker_iff f).2 h)

/-- The lift to `PowerQuotient G n` agrees with the original map on `G`. -/
@[simp]
theorem powerQuotientLift_mk {H : Type v} [Group H] (f : G →* H)
    (h : ∀ g : G, f g ^ n = 1) (g : G) :
    powerQuotientLift f h (powerQuotientMk (G := G) (n := n) g) = f g :=
  rfl

/--
If `Q` is a retract of `G` and has exponent dividing `n`, then `Q` embeds in the quotient of `G`
by `n`-th powers.
-/
theorem powerQuotientMk_comp_injective_of_retraction {Q : Type v} [Group Q]
    (i : Q →* G) (r : G →* Q) (hri : r.comp i = MonoidHom.id Q)
    (hQ : ∀ q : Q, q ^ n = 1) :
    Function.Injective ((powerQuotientMk (G := G) (n := n)).comp i) := by
  let rbar : PowerQuotient G n →* Q := powerQuotientLift r fun g ↦ hQ (r g)
  apply
    (show Function.LeftInverse rbar ((powerQuotientMk (G := G) (n := n)).comp i) from
      ?_).injective
  intro q
  change r (i q) = q
  exact DFunLike.congr_fun hri q


variable {X : Type*}

/-- The free group of exponent three on `X`.

Paper-ID: preliminaries.notation
TeX: T3_modelcompanion_v4.tex, v4 Notation 2.1, item 9.
-/
abbrev Free (X : Type*) : Type _ :=
  PowerQuotient (FreeGroup X) 3

namespace Free

/-- The canonical map from the generating set.

Paper-ID: preliminaries.notation
TeX: T3_modelcompanion_v4.tex, v4 Notation 2.1, item 9.
-/
def of (x : X) : Free X :=
  powerQuotientMk (FreeGroup.of x)

/-- The free group of exponent three does have exponent dividing three.

Paper-ID: preliminaries.notation
TeX: T3_modelcompanion_v4.tex, v4 Notation 2.1, item 9.
-/
theorem pow_three (g : Free X) : g ^ 3 = 1 :=
  by apply powerQuotient_hasExponent

/-- The exponent-three fact used by the canonical scalar actions on free-group layers.

Paper-ID: preliminaries.notation
TeX: T3_modelcompanion_v4.tex, v4 Notation 2.1, item 9.
-/
instance hasExponentThree : Fact (HasExponentThree (Free X)) := ⟨pow_three⟩

variable {H : Type*} [Group H]

/-- The universal property: a map into a group of exponent three lifts to a homomorphism.

Paper-ID: preliminaries.notation
TeX: T3_modelcompanion_v4.tex, v4 Notation 2.1, item 9.
-/
def lift (hH : ∀ h : H, h ^ 3 = 1) (f : X → H) : Free X →* H :=
  powerQuotientLift (FreeGroup.lift f) fun _ => hH _

@[simp]
theorem lift_of (hH : ∀ h : H, h ^ 3 = 1) (f : X → H) (x : X) :
    lift hH f (of x) = f x := by
  rw [of, lift, powerQuotientLift_mk, FreeGroup.lift_apply_of]

/-- Two homomorphisms out of the free group of exponent three agreeing on generators are equal.

Paper-ID: preliminaries.notation
TeX: T3_modelcompanion_v4.tex, v4 Notation 2.1, item 9.
-/
theorem hom_ext {φ ψ : Free X →* H} (h : ∀ x : X, φ (of x) = ψ (of x)) : φ = ψ := by
  have hcomp : φ.comp (powerQuotientMk (G := FreeGroup X) (n := 3))
      = ψ.comp (powerQuotientMk (G := FreeGroup X) (n := 3)) :=
    FreeGroup.ext_hom _ _ h
  refine MonoidHom.ext fun g => ?_
  obtain ⟨g, rfl⟩ := powerQuotientMk_surjective (G := FreeGroup X) (n := 3) g
  exact congrArg (fun k : FreeGroup X →* H => k g) hcomp

variable {Y Z : Type*}

/-- Functoriality: a map of generating sets induces a homomorphism of free groups.

Paper-ID: preliminaries.notation
TeX: T3_modelcompanion_v4.tex, v4 Notation 2.1, item 9.
-/
def map (f : X → Y) : Free X →* Free Y :=
  lift pow_three fun x => of (f x)

@[simp]
theorem map_of (f : X → Y) (x : X) : map f (of x) = of (f x) :=
  lift_of _ _ x

theorem map_id : map (id : X → X) = MonoidHom.id (Free X) :=
  hom_ext fun x => map_of _ x

theorem map_comp (f : X → Y) (g : Y → Z) : (map g).comp (map f) = map (g ∘ f) :=
  hom_ext fun x => by
    rw [MonoidHom.comp_apply, map_of, map_of, map_of, Function.comp_apply]

/--
A generator map with a left inverse induces an injective homomorphism: the free group functor
preserves split injections, including the inclusions used to compare finite generating subsets.

Paper-ID: preliminaries.notation
TeX: T3_modelcompanion_v4.tex, v4 Notation 2.1, item 9.
-/
theorem map_injective_of_leftInverse {f : X → Y} {r : Y → X}
    (hr : Function.LeftInverse r f) : Function.Injective (map f) := by
  have hcomp : ∀ g : Free X, map r (map f g) = g := by
    intro g
    have h : (map r).comp (map f) = MonoidHom.id (Free X) := by
      rw [map_comp, show r ∘ f = id from funext hr, map_id]
    exact congrArg (fun k : Free X →* Free X => k g) h
  intro a b hab
  rw [← hcomp a, hab, hcomp b]

end Free

end T3
