/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
module

public import T3.GroupTheory.Free.Basic
public import Mathlib.GroupTheory.Finiteness

/-!
# Free Burnside groups and local finiteness

For an arbitrary exponent, the relatively free group is the quotient of the ordinary free
group by all exponent relations. Its universal property shows that finiteness of all finite-rank
free Burnside groups implies finiteness of every finitely generated group of that exponent.
This is the group-theoretic equivalence used in the archived v7 Section 6 and the v9
introduction's interpretation of Conjecture 1.1. It makes no model-companion existence claim.
The detailed source below remains in the archive because Section 6 is removed from v9.

Paper-ID: questions.burnside_local_finiteness
TeX: archives/T3_modelcompanion_v7.tex, Section 6, lines 1520–1525.
-/

@[expose] public section

universe u v

namespace T3

/-- The relatively free group of exponent dividing `n` on the generator type `I`.

Paper-ID: questions.burnside_local_finiteness
TeX: archives/T3_modelcompanion_v7.tex, Section 6, `B(r,n)`, lines 1520–1525.
-/
abbrev Burnside (n : ℕ) (I : Type u) := PowerQuotient (FreeGroup I) n

namespace Burnside

variable {n : ℕ} {I : Type u} {G : Type v} [Group G]

/-- The canonical generator of a free Burnside group.

Paper-ID: questions.burnside_local_finiteness
TeX: archives/T3_modelcompanion_v7.tex, Section 6, the relatively free generators, lines 1520–1525.
-/
def of (i : I) : Burnside n I := powerQuotientMk (FreeGroup.of i)

/-- Every element of the free Burnside group satisfies the exponent law.

Paper-ID: questions.burnside_local_finiteness
TeX: archives/T3_modelcompanion_v7.tex, Section 6, the variety defined by `xⁿ = 1`, line 1520.
-/
theorem pow_exponent (x : Burnside n I) : x ^ n = 1 := powerQuotient_hasExponent x

/-- A map of generators extends to a homomorphism into any group of the specified exponent.

Paper-ID: questions.burnside_local_finiteness
TeX: archives/T3_modelcompanion_v7.tex, Section 6, universal property, lines 1522–1523.
-/
def lift (hG : ∀ x : G, x ^ n = 1) (a : I → G) : Burnside n I →* G :=
  powerQuotientLift (FreeGroup.lift a) fun _ => hG _

/-- The extension has the prescribed values on the free generators.

Paper-ID: questions.burnside_local_finiteness
TeX: archives/T3_modelcompanion_v7.tex, Section 6, universal property, lines 1522–1523.
-/
@[simp]
theorem lift_of (hG : ∀ x : G, x ^ n = 1) (a : I → G) (i : I) :
    lift hG a (of i) = a i := by
  simp [lift, of]

/-- The canonical generators generate the whole free Burnside group, in any rank.

Paper-ID: questions.burnside_local_finiteness
TeX: archives/T3_modelcompanion_v7.tex, Section 6, `B(r,n)` is generated by its `r` generators.
-/
theorem closure_range_of : Subgroup.closure (Set.range (of : I → Burnside n I)) = ⊤ := by
  let q := powerQuotientMk (G := FreeGroup I) (n := n)
  have h := congrArg (Subgroup.map q) (FreeGroup.closure_range_of I)
  rw [MonoidHom.map_closure, ← MonoidHom.range_eq_map,
    MonoidHom.range_eq_top.mpr (powerQuotientMk_surjective (G := FreeGroup I) (n := n))] at h
  change Subgroup.closure (Set.range fun x : I => q (FreeGroup.of x)) = ⊤
  simpa only [← Set.range_comp, Function.comp_def] using h

/-- A generating family gives a surjective map from the free Burnside group on its indices.

Paper-ID: questions.burnside_local_finiteness
TeX: archives/T3_modelcompanion_v7.tex, Section 6, `r`-generated groups are quotients of `B(r,n)`.
-/
theorem lift_surjective (hG : ∀ x : G, x ^ n = 1) (a : I → G)
    (ha : Subgroup.closure (Set.range a) = ⊤) : Function.Surjective (lift hG a) := by
  apply MonoidHom.range_eq_top.mp
  apply top_unique
  rw [← ha]
  apply (Subgroup.closure_le _).mpr
  rintro _ ⟨i, rfl⟩
  exact ⟨of i, lift_of hG a i⟩

/-- Free Burnside groups on finitely many generators are finitely generated.

Paper-ID: questions.burnside_local_finiteness
TeX: archives/T3_modelcompanion_v7.tex, Section 6, the finite-rank relatively free groups.
-/
instance fg [Finite I] : Group.FG (Burnside n I) :=
  Group.fg_iff.mpr ⟨Set.range of, closure_range_of, Set.finite_range of⟩

/-- Finiteness of all positive finite ranks implies finiteness of every group with a finite
generating family. The extra generator sent to the identity handles the empty family as well.

Paper-ID: questions.burnside_local_finiteness
TeX: archives/T3_modelcompanion_v7.tex, Section 6, the quotient argument, lines 1522–1525.
-/
theorem finite_of_generating_family [Finite I]
    (hfree : ∀ r : ℕ, 0 < r → Finite (Burnside n (Fin r)))
    (hG : ∀ x : G, x ^ n = 1) (a : I → G)
    (ha : Subgroup.closure (Set.range a) = ⊤) : Finite G := by
  classical
  let := Fintype.ofFinite I
  let e := Fintype.equivFin I
  let b : Fin (Fintype.card I + 1) → G := fun i =>
    if h : i.val < Fintype.card I then a (e.symm ⟨i.val, h⟩) else 1
  have hb : Subgroup.closure (Set.range b) = ⊤ := by
    apply top_unique
    rw [← ha]
    apply Subgroup.closure_mono
    rintro _ ⟨i, rfl⟩
    refine ⟨⟨(e i).val, Nat.lt_succ_of_lt (e i).isLt⟩, ?_⟩
    simp [b]
  let := hfree (Fintype.card I + 1) (Nat.succ_pos _)
  exact Finite.of_surjective (lift hG b) (lift_surjective hG b hb)

/-- Finiteness of all finite-rank Burnside groups implies that every finitely generated group
of the exponent is finite, with no bound on the universe of the target group.

Paper-ID: questions.burnside_local_finiteness
TeX: archives/T3_modelcompanion_v7.tex, Section 6, local finiteness from finite Burnside groups.
-/
theorem finite_of_fg [Group.FG G]
    (hfree : ∀ r : ℕ, 0 < r → Finite (Burnside n (Fin r)))
    (hG : ∀ x : G, x ^ n = 1) : Finite G := by
  obtain ⟨s, hs, hfin⟩ := Group.fg_iff.mp (inferInstance : Group.FG G)
  let := hfin.to_subtype
  exact finite_of_generating_family hfree hG (Subtype.val : s → G) (by simpa using hs)

end Burnside

end T3
