/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
module

public import T3.GroupTheory.Free.Basic
public import T3.GroupTheory.Identities
public import Mathlib.Data.ZMod.QuotientGroup
public import Mathlib.GroupTheory.Coset.Card
public import Mathlib.GroupTheory.NoncommPiCoprod
public import Mathlib.GroupTheory.QuotientGroup.Finite
public import Mathlib.Order.Hom.PowersetCard

/-!
# Foundations for collecting words in an exponent-three group

This file proves the order upper bound for a finite-rank free exponent-three group through
its three successive commutative layers: the abelianization, the derived subgroup modulo `γ₃`,
and `γ₃`. It identifies generating families for each layer and bounds their cardinalities.

The canonical generators are proved to generate `Free I`. A homomorphism can therefore
transport generation to the closure of the images. Triple commutation is packaged as a
homomorphism in its right argument, which is the first collection operator. Finally, a generic
cardinality lemma bounds any commutative exponent-three group generated by a finite family by
`3 ^ Nat.card J`. Applying it to the abelianization closes the degree-one layer of the upper
bound.

The increasing pairs and triples index the generators of the last two layers. Combining
the three layer bounds gives `Free.natCard_le`; the matching lower bound and the actual
normal-word bijection are proved in `NormalForm.lean`.

## Main results

* `Free.closure_range_of`: the canonical generators generate the free group;
* `mem_closure_range_of_closure_range_eq_top`: generation is transported through a homomorphism;
* `closure_range_comp_of_surjective`: a surjective homomorphism transports a generating family;
* `commutatorTripleRightHom`: a triple commutator is multiplicative in its third entry;
* `finite_of_commuting_generators`: a finitely generated commutative exponent-three group is
  finite;
* `natCard_le_three_pow_of_commuting_generators`: its cardinality is at most `3 ^ Nat.card J`;
* `finite_abelianization` and `natCard_abelianization_le_three_pow`: the degree-one layer;
* `Free.lowerCentralSeries_two_eq_increasingTripleClosure`: `γ₃` is generated by the
  increasing triple commutators;
* `Free.natCard_pairQuotient_le`: `|F' / γ₃| ≤ 3 ^ choose n 2`;
* `Free.natCard_lowerCentralSeries_two_le`: `|γ₃| ≤ 3 ^ choose n 3`;
* `Free.natCard_le`: the complete collected-form upper bound.
-/

@[expose] public section

open scoped commutatorElement

namespace T3

namespace Free

variable {I : Type*}

/-- The canonical generators generate the free exponent-three group.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem closure_range_of :
    Subgroup.closure (Set.range (of : I → Free I)) = ⊤ := by
  let q := T3.powerQuotientMk (G := FreeGroup I) (n := 3)
  have h := congrArg (Subgroup.map q) (FreeGroup.closure_range_of I)
  rw [MonoidHom.map_closure, ← MonoidHom.range_eq_map,
    MonoidHom.range_eq_top.mpr (T3.powerQuotientMk_surjective
      (G := FreeGroup I) (n := 3))] at h
  have hrange :
      Set.range (of : I → Free I) = q '' Set.range (FreeGroup.of : I → FreeGroup I) := by
    ext y
    constructor
    · rintro ⟨i, rfl⟩
      exact ⟨FreeGroup.of i, ⟨i, rfl⟩, rfl⟩
    · rintro ⟨_, ⟨i, rfl⟩, rfl⟩
      exact ⟨i, rfl⟩
  rw [hrange]
  exact h

end Free

variable {G H I J : Type*} [Group G] [Group H]

/--
If `x : I → G` generates `G`, the value of a homomorphism at every element lies in the subgroup
generated by the values on `x`.


Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem mem_closure_range_of_closure_range_eq_top
    (x : I → G) (hgen : Subgroup.closure (Set.range x) = ⊤)
    (f : G →* H) (g : G) :
    f g ∈ Subgroup.closure (Set.range fun i => f (x i)) := by
  have hg : g ∈ Subgroup.closure (Set.range x) := by
    rw [hgen]
    trivial
  induction hg using Subgroup.closure_induction with
  | mem y hy =>
      obtain ⟨i, rfl⟩ := hy
      exact Subgroup.subset_closure ⟨i, rfl⟩
  | one => simp
  | mul a b _ _ ha hb => simpa using Subgroup.mul_mem _ ha hb
  | inv a _ ha => simpa using Subgroup.inv_mem _ ha

/-- A surjective homomorphism transports a generating family to a generating family.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem closure_range_comp_of_surjective
    (x : I → G) (hgen : Subgroup.closure (Set.range x) = ⊤)
    (f : G →* H) (hf : Function.Surjective f) :
    Subgroup.closure (Set.range fun i => f (x i)) = ⊤ := by
  apply top_unique
  intro y _
  obtain ⟨g, rfl⟩ := hf y
  exact mem_closure_range_of_closure_range_eq_top x hgen f g

/-- For fixed first two entries, the triple commutator is a homomorphism in the third entry.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
def commutatorTripleRightHom (hG : ∀ x : G, x ^ 3 = 1) (x y : G) : G →* G where
  toFun z := ⁅⁅x, y⁆, z⁆
  map_one' := commutatorElement_one_right _
  map_mul' := commutator_commutator_mul_right hG x y

section Cardinality

variable [Finite J]

/-- A commutative exponent-three group generated by a finite family is finite.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem finite_of_commuting_generators
    (x : J → G) (hpow : ∀ j, x j ^ 3 = 1)
    (hcomm : IsMulCommutative G)
    (hgen : Subgroup.closure (Set.range x) = ⊤) : Finite G := by
  let := Fintype.ofFinite J
  let : IsMulCommutative G := hcomm
  let K : J → Subgroup G := fun j => Subgroup.zpowers (x j)
  have hfin (j : J) : (K j : Set G).Finite := by
    apply IsOfFinOrder.finite_zpowers
    exact isOfFinOrder_iff_pow_eq_one.mpr ⟨3, by omega, hpow j⟩
  let (j : J) : Finite (K j) := hfin j
  have hcommK : Pairwise fun i j => ∀ a b : G, a ∈ K i → b ∈ K j → Commute a b := by
    intro i j hij a b ha hb
    exact (commute_iff_eq a b).2 (mul_comm' a b)
  let φ : (∀ j, K j) →* G := Subgroup.noncommPiCoprod hcommK
  apply Finite.of_surjective φ
  rw [← MonoidHom.range_eq_top]
  dsimp only [φ]
  rw [Subgroup.noncommPiCoprod_range]
  change (⨆ j, Subgroup.zpowers (x j)) = ⊤
  simp_rw [Subgroup.zpowers_eq_closure, ← Subgroup.closure_iUnion]
  simpa only [Set.iUnion_singleton_eq_range] using hgen

/--
If a commutative exponent-three group is generated by `J`, its cardinality is at most
`3 ^ Nat.card J`.


Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem natCard_le_three_pow_of_commuting_generators
    (x : J → G) (hpow : ∀ j, x j ^ 3 = 1)
    (hcomm : IsMulCommutative G)
    (hgen : Subgroup.closure (Set.range x) = ⊤) :
    Nat.card G ≤ 3 ^ Nat.card J := by
  let := Fintype.ofFinite J
  let : IsMulCommutative G := hcomm
  let K : J → Subgroup G := fun j => Subgroup.zpowers (x j)
  have hfin (j : J) : (K j : Set G).Finite := by
    apply IsOfFinOrder.finite_zpowers
    exact isOfFinOrder_iff_pow_eq_one.mpr ⟨3, by omega, hpow j⟩
  let (j : J) : Finite (K j) := hfin j
  have hcommK : Pairwise fun i j => ∀ a b : G, a ∈ K i → b ∈ K j → Commute a b := by
    intro i j hij a b ha hb
    exact (commute_iff_eq a b).2 (mul_comm' a b)
  let φ : (∀ j, K j) →* G := Subgroup.noncommPiCoprod hcommK
  have hφ : Function.Surjective φ := by
    rw [← MonoidHom.range_eq_top]
    dsimp only [φ]
    rw [Subgroup.noncommPiCoprod_range]
    change (⨆ j, Subgroup.zpowers (x j)) = ⊤
    simp_rw [Subgroup.zpowers_eq_closure, ← Subgroup.closure_iUnion]
    simpa only [Set.iUnion_singleton_eq_range] using hgen
  calc
    Nat.card G ≤ Nat.card (∀ j, K j) :=
      Nat.card_le_card_of_surjective φ hφ
    _ = ∏ j, Nat.card (K j) := Nat.card_pi
    _ ≤ ∏ _j : J, 3 := by
      gcongr with j
      rw [Nat.card_zpowers]
      exact orderOf_le_of_pow_eq_one (by omega) (hpow j)
    _ = 3 ^ Nat.card J := by
      rw [Finset.prod_const, Finset.card_univ, Nat.card_eq_fintype_card]

end Cardinality

section Abelianization

variable [Finite J]

/-- An exponent-three law descends to every quotient.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem pow_three_quotient (N : Subgroup G) [N.Normal]
    (hG : ∀ g : G, g ^ 3 = 1) (x : G ⧸ N) :
    x ^ 3 = 1 := by
  obtain ⟨g, rfl⟩ := QuotientGroup.mk'_surjective N x
  rw [← map_pow, hG, map_one]

/-- The abelianization of a finitely generated exponent-three group is finite.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem finite_abelianization
    (x : J → G) (hpow : ∀ g : G, g ^ 3 = 1)
    (hgen : Subgroup.closure (Set.range x) = ⊤) :
    Finite (G ⧸ commutator G) := by
  let q : G →* G ⧸ commutator G := QuotientGroup.mk' (commutator G)
  apply finite_of_commuting_generators (x := fun j => q (x j))
  · exact fun _ => pow_three_quotient (commutator G) hpow _
  · exact Subgroup.Normal.quotient_commutative_iff_commutator_le.mpr le_rfl
  · exact closure_range_comp_of_surjective x hgen q
      (QuotientGroup.mk'_surjective (commutator G))

/-- The abelianization has order at most three to the number of generators.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem natCard_abelianization_le_three_pow
    (x : J → G) (hpow : ∀ g : G, g ^ 3 = 1)
    (hgen : Subgroup.closure (Set.range x) = ⊤) :
    Nat.card (G ⧸ commutator G) ≤ 3 ^ Nat.card J := by
  let q : G →* G ⧸ commutator G := QuotientGroup.mk' (commutator G)
  apply natCard_le_three_pow_of_commuting_generators (x := fun j => q (x j))
  · exact fun _ => pow_three_quotient (commutator G) hpow _
  · exact Subgroup.Normal.quotient_commutative_iff_commutator_le.mpr le_rfl
  · exact closure_range_comp_of_surjective x hgen q
      (QuotientGroup.mk'_surjective (commutator G))

end Abelianization

/-- The distinguished family generates its own closure as a subgroup type.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem closure_range_subtype (x : I → G) :
    Subgroup.closure
        (Set.range fun i =>
          (⟨x i, Subgroup.subset_closure ⟨i, rfl⟩⟩ :
            Subgroup.closure (Set.range x))) =
      ⊤ := by
  let K := Subgroup.closure (Set.range x)
  let y : I → K := fun i => ⟨x i, Subgroup.subset_closure ⟨i, rfl⟩⟩
  change Subgroup.closure (Set.range y) = ⊤
  rw [← Subgroup.map_subtype_inj, MonoidHom.map_closure]
  have himage : K.subtype '' Set.range y = Set.range x := by
    ext g
    constructor
    · rintro ⟨_, ⟨i, rfl⟩, rfl⟩
      exact ⟨i, rfl⟩
    · rintro ⟨i, rfl⟩
      exact ⟨y i, ⟨i, rfl⟩, rfl⟩
  rw [himage, ← MonoidHom.range_eq_map, K.range_subtype]

/-- A strictly increasing pair of indices.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
structure IncreasingPair (I : Type*) [LT I] where
  /-- The smaller index. -/
  first : I
  /-- The larger index. -/
  second : I
  first_lt_second : first < second

namespace IncreasingPair

variable [LinearOrder I]

/-- Two increasing pairs with the same components are equal.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
@[ext]
theorem ext {p q : IncreasingPair I} (h₁ : p.first = q.first) (h₂ : p.second = q.second) :
    p = q := by
  cases p
  cases q
  subst h₁ h₂
  rfl

instance [DecidableEq I] : DecidableEq (IncreasingPair I) := fun p q =>
  decidable_of_iff (p.first = q.first ∧ p.second = q.second)
    ⟨fun h => ext h.1 h.2, fun h => by rw [h]; exact ⟨rfl, rfl⟩⟩

/-- A strictly increasing pair as an order embedding of `Fin 2`.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
def toOrderEmbedding (p : IncreasingPair I) : Fin 2 ↪o I :=
  OrderEmbedding.ofStrictMono ![p.first, p.second] <| by
    rw [Fin.strictMono_iff_lt_succ]
    intro i
    fin_cases i
    exact p.first_lt_second

/-- Supporting declaration `toOrderEmbedding_apply_zero` for the finite-rank collection theorem.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
@[simp]
theorem toOrderEmbedding_apply_zero (p : IncreasingPair I) : p.toOrderEmbedding 0 = p.first :=
  rfl

/-- Supporting declaration `toOrderEmbedding_apply_one` for the finite-rank collection theorem.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
@[simp]
theorem toOrderEmbedding_apply_one (p : IncreasingPair I) : p.toOrderEmbedding 1 = p.second :=
  rfl

/-- Strictly increasing pairs are the same as order embeddings of `Fin 2`.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
def equivOrderEmbedding : IncreasingPair I ≃ (Fin 2 ↪o I) where
  toFun := toOrderEmbedding
  invFun f :=
    { first := f 0
      second := f 1
      first_lt_second := f.strictMono (by decide) }
  left_inv p := by
    rcases p with ⟨a, b, hab⟩
    rfl
  right_inv f := by
    ext i
    fin_cases i <;> rfl

/-- Strictly increasing pairs are the same as two-element subsets.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
def equivPowersetCard : IncreasingPair I ≃ Set.powersetCard I 2 :=
  equivOrderEmbedding.trans Set.powersetCard.ofFinEmbEquiv

/-- Supporting declaration `equivPowersetCard_symm_first` for the finite-rank collection theorem.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem equivPowersetCard_symm_first (s : Set.powersetCard I 2) :
    (equivPowersetCard.symm s).first = Set.powersetCard.ofFinEmbEquiv.symm s 0 :=
  rfl

/-- Supporting declaration `equivPowersetCard_symm_second` for the finite-rank collection theorem.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem equivPowersetCard_symm_second (s : Set.powersetCard I 2) :
    (equivPowersetCard.symm s).second = Set.powersetCard.ofFinEmbEquiv.symm s 1 :=
  rfl

/-- The powerset correspondence preserves the increasing embedding.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem ofFinEmbEquiv_symm_equivPowersetCard (p : IncreasingPair I) :
    Set.powersetCard.ofFinEmbEquiv.symm (equivPowersetCard p) = p.toOrderEmbedding :=
  Set.powersetCard.ofFinEmbEquiv.symm_apply_apply _

/-- A two-element subset is a given increasing pair exactly when its components match.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem eq_equivPowersetCard_iff {s : Set.powersetCard I 2} {a b : I} {hab : a < b} :
    s = equivPowersetCard ⟨a, b, hab⟩ ↔
      Set.powersetCard.ofFinEmbEquiv.symm s 0 = a ∧
        Set.powersetCard.ofFinEmbEquiv.symm s 1 = b := by
  rw [← Equiv.symm_apply_eq, IncreasingPair.ext_iff, equivPowersetCard_symm_first,
    equivPowersetCard_symm_second]

instance [Finite I] : Finite (IncreasingPair I) :=
  Finite.of_equiv _ equivPowersetCard.symm

/-- The number of increasing pairs is the binomial coefficient `choose n 2`.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem natCard_eq_choose :
    Nat.card (IncreasingPair I) = (Nat.card I).choose 2 := by
  rw [Nat.card_congr equivPowersetCard, Set.powersetCard.card]

end IncreasingPair

/-- A strictly increasing triple of indices.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
structure IncreasingTriple (I : Type*) [LT I] where
  /-- The smallest index. -/
  first : I
  /-- The middle index. -/
  second : I
  /-- The largest index. -/
  third : I
  first_lt_second : first < second
  second_lt_third : second < third

namespace IncreasingTriple

variable [LinearOrder I]

/-- Two increasing triples with the same components are equal.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
@[ext]
theorem ext {s t : IncreasingTriple I} (h₁ : s.first = t.first) (h₂ : s.second = t.second)
    (h₃ : s.third = t.third) : s = t := by
  cases s
  cases t
  subst h₁ h₂ h₃
  rfl

instance [DecidableEq I] : DecidableEq (IncreasingTriple I) := fun s t =>
  decidable_of_iff (s.first = t.first ∧ s.second = t.second ∧ s.third = t.third)
    ⟨fun h => ext h.1 h.2.1 h.2.2, fun h => by rw [h]; exact ⟨rfl, rfl, rfl⟩⟩

/-- A strictly increasing triple as an order embedding of `Fin 3`.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
def toOrderEmbedding (t : IncreasingTriple I) : Fin 3 ↪o I :=
  OrderEmbedding.ofStrictMono ![t.first, t.second, t.third] <| by
    rw [Fin.strictMono_iff_lt_succ]
    intro i
    fin_cases i
    · exact t.first_lt_second
    · exact t.second_lt_third

/-- Supporting declaration `toOrderEmbedding_apply_zero` for the finite-rank collection theorem.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
@[simp]
theorem toOrderEmbedding_apply_zero (t : IncreasingTriple I) : t.toOrderEmbedding 0 = t.first :=
  rfl

/-- Supporting declaration `toOrderEmbedding_apply_one` for the finite-rank collection theorem.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
@[simp]
theorem toOrderEmbedding_apply_one (t : IncreasingTriple I) : t.toOrderEmbedding 1 = t.second :=
  rfl

/-- Supporting declaration `toOrderEmbedding_apply_two` for the finite-rank collection theorem.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
@[simp]
theorem toOrderEmbedding_apply_two (t : IncreasingTriple I) : t.toOrderEmbedding 2 = t.third :=
  rfl

/-- Strictly increasing triples are the same as order embeddings of `Fin 3`.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
def equivOrderEmbedding : IncreasingTriple I ≃ (Fin 3 ↪o I) where
  toFun := toOrderEmbedding
  invFun f :=
    { first := f 0
      second := f 1
      third := f 2
      first_lt_second := f.strictMono (by decide)
      second_lt_third := f.strictMono (by decide) }
  left_inv t := by
    rcases t with ⟨a, b, c, hab, hbc⟩
    rfl
  right_inv f := by
    ext i
    fin_cases i <;> rfl

/-- Strictly increasing triples are the same as three-element subsets.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
def equivPowersetCard : IncreasingTriple I ≃ Set.powersetCard I 3 :=
  equivOrderEmbedding.trans Set.powersetCard.ofFinEmbEquiv

/-- Supporting declaration `equivPowersetCard_symm_first` for the finite-rank collection theorem.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem equivPowersetCard_symm_first (s : Set.powersetCard I 3) :
    (equivPowersetCard.symm s).first = Set.powersetCard.ofFinEmbEquiv.symm s 0 :=
  rfl

/-- Supporting declaration `equivPowersetCard_symm_second` for the finite-rank collection theorem.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem equivPowersetCard_symm_second (s : Set.powersetCard I 3) :
    (equivPowersetCard.symm s).second = Set.powersetCard.ofFinEmbEquiv.symm s 1 :=
  rfl

/-- Supporting declaration `equivPowersetCard_symm_third` for the finite-rank collection theorem.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem equivPowersetCard_symm_third (s : Set.powersetCard I 3) :
    (equivPowersetCard.symm s).third = Set.powersetCard.ofFinEmbEquiv.symm s 2 :=
  rfl

/-- The powerset correspondence preserves the increasing embedding.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem ofFinEmbEquiv_symm_equivPowersetCard (t : IncreasingTriple I) :
    Set.powersetCard.ofFinEmbEquiv.symm (equivPowersetCard t) = t.toOrderEmbedding :=
  Set.powersetCard.ofFinEmbEquiv.symm_apply_apply _

instance [Finite I] : Finite (IncreasingTriple I) :=
  Finite.of_equiv _ equivPowersetCard.symm

/-- The number of increasing triples is the binomial coefficient `choose n 3`.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem natCard_eq_choose :
    Nat.card (IncreasingTriple I) = (Nat.card I).choose 3 := by
  rw [Nat.card_congr equivPowersetCard, Set.powersetCard.card]

end IncreasingTriple

namespace Free

variable {I : Type*}

/-- The derived subgroup of the free exponent-three group.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
abbrev Derived : Subgroup (Free I) :=
  commutator (Free I)

/-- `γ₃` regarded as a subgroup of the derived subgroup.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
abbrev GammaThreeInDerived : Subgroup (Derived (I := I)) :=
  ((⊤ : Subgroup (Free I)).lowerCentralSeries 2).subgroupOf
    (commutator (Free I))

/-- The degree-two quotient `F' / γ₃`.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
abbrev PairQuotient :=
  Derived (I := I) ⧸ GammaThreeInDerived (I := I)

/-- A commutator, regarded as an element of the derived subgroup.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
def derivedCommutator (a b : Free I) : Derived (I := I) :=
  ⟨⁅a, b⁆, Subgroup.commutator_mem_commutator (Subgroup.mem_top a) (Subgroup.mem_top b)⟩

/-- A triple commutator belongs to `γ₃` inside the derived subgroup.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem derivedCommutator_mem_gammaThree (a b c : Free I) :
    derivedCommutator ⁅a, b⁆ c ∈ GammaThreeInDerived (I := I) := by
  change ⁅⁅a, b⁆, c⁆ ∈ (⊤ : Subgroup (Free I)).lowerCentralSeries 2
  rw [show 2 = 1 + 1 by omega, Subgroup.lowerCentralSeries_succ,
    Subgroup.top_lowerCentralSeries_one]
  exact Subgroup.commutator_mem_commutator
    (Subgroup.commutator_mem_commutator (Subgroup.mem_top a) (Subgroup.mem_top b))
    (Subgroup.mem_top c)

/-- Modulo `γ₃`, commutation with a fixed left argument is a homomorphism on the right.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
def commutatorPairQuotientRightHom (a : Free I) :
    Free I →* PairQuotient (I := I) where
  toFun b := QuotientGroup.mk' (GammaThreeInDerived (I := I)) (derivedCommutator a b)
  map_one' := by
    rw [show derivedCommutator a 1 = 1 by
      apply Subtype.ext
      exact commutatorElement_one_right a]
    exact map_one _
  map_mul' b c := by
    let q : Derived (I := I) →* PairQuotient (I := I) :=
      QuotientGroup.mk' (GammaThreeInDerived (I := I))
    change q (derivedCommutator a (b * c)) =
      q (derivedCommutator a b) * q (derivedCommutator a c)
    have h :
        derivedCommutator a (b * c) =
          derivedCommutator a b * derivedCommutator a c *
            (derivedCommutator ⁅a, c⁆ b)⁻¹ := by
      apply Subtype.ext
      exact commutator_mul_right_aux pow_three a b c
    rw [h, map_mul, map_mul, map_inv]
    have ht : q (derivedCommutator ⁅a, c⁆ b) = 1 :=
      (QuotientGroup.eq_one_iff _).mpr (derivedCommutator_mem_gammaThree a c b)
    rw [ht, inv_one, mul_one]

variable [LinearOrder I]

/-- The image of an increasing generator commutator in `F' / γ₃`.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
def increasingPairQuotient (p : IncreasingPair I) : PairQuotient (I := I) :=
  QuotientGroup.mk' (GammaThreeInDerived (I := I))
    (derivedCommutator (of p.first) (of p.second))

/-- The subgroup of `F' / γ₃` generated by increasing generator commutators.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
def increasingPairQuotientClosure : Subgroup (PairQuotient (I := I)) :=
  Subgroup.closure (Set.range (increasingPairQuotient (I := I)))

/-- Every pair of free generators maps into the increasing-pair closure.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem generatorPair_mem_increasingPairQuotientClosure (i j : I) :
    QuotientGroup.mk' (GammaThreeInDerived (I := I))
        (derivedCommutator (of i) (of j)) ∈
      increasingPairQuotientClosure (I := I) := by
  let K := increasingPairQuotientClosure (I := I)
  let q : Derived (I := I) →* PairQuotient (I := I) :=
    QuotientGroup.mk' (GammaThreeInDerived (I := I))
  by_cases hij : i = j
  · subst j
    change q (derivedCommutator (of i) (of i)) ∈ K
    rw [show derivedCommutator (of i) (of i) = 1 by
      apply Subtype.ext
      exact commutatorElement_self (of i), map_one]
    exact K.one_mem
  rcases lt_or_gt_of_ne hij with hij | hji
  · exact Subgroup.subset_closure ⟨⟨i, j, hij⟩, rfl⟩
  · have h :
        derivedCommutator (of i) (of j) =
          (derivedCommutator (of j) (of i))⁻¹ := by
      apply Subtype.ext
      exact (commutatorElement_inv (of j) (of i)).symm
    rw [h, map_inv]
    exact K.inv_mem (Subgroup.subset_closure ⟨⟨j, i, hji⟩, rfl⟩)

/-- Every commutator maps into the closure of the increasing generator commutators.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem commutator_mem_increasingPairQuotientClosure (a b : Free I) :
    QuotientGroup.mk' (GammaThreeInDerived (I := I)) (derivedCommutator a b) ∈
      increasingPairQuotientClosure (I := I) := by
  let K := increasingPairQuotientClosure (I := I)
  let q : Derived (I := I) →* PairQuotient (I := I) :=
    QuotientGroup.mk' (GammaThreeInDerived (I := I))
  have extend_right (x y : Free I)
      (hbase : ∀ j : I, q (derivedCommutator x (of j)) ∈ K) :
      q (derivedCommutator x y) ∈ K := by
    have hmem := mem_closure_range_of_closure_range_eq_top
      (of : I → Free I) (closure_range_of (I := I))
      (commutatorPairQuotientRightHom x) y
    exact (Subgroup.closure_le K).2 (by
      rintro _ ⟨j, rfl⟩
      exact hbase j) hmem
  have h₁ (i : I) (y : Free I) : q (derivedCommutator (of i) y) ∈ K :=
    extend_right (of i) y fun j => generatorPair_mem_increasingPairQuotientClosure i j
  apply extend_right a b
  intro j
  have h := h₁ j a
  have heq :
      derivedCommutator a (of j) = (derivedCommutator (of j) a)⁻¹ := by
    apply Subtype.ext
    exact (commutatorElement_inv (of j) a).symm
  rw [heq, map_inv]
  exact K.inv_mem h

/-- The increasing generator commutators generate the full quotient `F' / γ₃`.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem closure_range_increasingPairQuotient :
    Subgroup.closure (Set.range (increasingPairQuotient (I := I))) = ⊤ := by
  let K := increasingPairQuotientClosure (I := I)
  let q : Derived (I := I) →* PairQuotient (I := I) :=
    QuotientGroup.mk' (GammaThreeInDerived (I := I))
  apply top_unique
  intro y _
  obtain ⟨d, rfl⟩ := QuotientGroup.mk'_surjective (GammaThreeInDerived (I := I)) y
  have lift_mem {g : Free I} (hg : g ∈ commutator (Free I)) :
      q ⟨g, hg⟩ ∈ K := by
    induction hg using Subgroup.closure_induction with
    | mem u hu =>
        obtain ⟨a, -, b, -, rfl⟩ := hu
        exact commutator_mem_increasingPairQuotientClosure a b
    | one =>
        change q 1 ∈ K
        rw [map_one]
        exact K.one_mem
    | mul u v huD hvD hu hv =>
        rw [show (⟨u * v, Subgroup.mul_mem _ huD hvD⟩ : Derived (I := I)) =
          (⟨u, huD⟩ : Derived (I := I)) * ⟨v, hvD⟩ by rfl, map_mul]
        exact K.mul_mem hu hv
    | inv u huD hu =>
        rw [show (⟨u⁻¹, Subgroup.inv_mem _ huD⟩ : Derived (I := I)) =
          (⟨u, huD⟩ : Derived (I := I))⁻¹ by rfl, map_inv]
        exact K.inv_mem hu
  exact lift_mem d.2

/-- The triple commutator attached to a strictly increasing triple of free generators.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
def increasingTripleCommutator (t : IncreasingTriple I) : Free I :=
  ⁅⁅of t.first, of t.second⁆, of t.third⁆

/-- The subgroup generated by the increasing triple commutators.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
def increasingTripleClosure : Subgroup (Free I) :=
  Subgroup.closure (Set.range (increasingTripleCommutator (I := I)))

/-- Every triple commutator of free generators belongs to `increasingTripleClosure`.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem tripleCommutator_of_mem_increasingTripleClosure (i j k : I) :
    ⁅⁅of i, of j⁆, of k⁆ ∈ increasingTripleClosure (I := I) := by
  let K := increasingTripleClosure (I := I)
  have hG : ∀ x : Free I, x ^ 3 = 1 := pow_three
  have hcanonical {a b c : I} (hab : a < b) (hbc : b < c) :
      ⁅⁅of a, of b⁆, of c⁆ ∈ K := by
    apply Subgroup.subset_closure
    exact ⟨⟨a, b, c, hab, hbc⟩, rfl⟩
  have hcyclic {a b c : I} (h : ⁅⁅of a, of b⁆, of c⁆ ∈ K) :
      ⁅⁅of b, of c⁆, of a⁆ ∈ K := by
    rw [← commutator_triple_cyclic hG (of a) (of b) (of c)]
    exact h
  have hswap {a b c : I} (h : ⁅⁅of a, of b⁆, of c⁆ ∈ K) :
      ⁅⁅of b, of a⁆, of c⁆ ∈ K := by
    rw [commutator_triple_swap hG (of b) (of a) (of c)]
    exact K.inv_mem h
  by_cases hij : i = j
  · subst j
    simp
  by_cases hjk : j = k
  · subst k
    rw [commutator_self_right hG]
    exact K.one_mem
  by_cases hik : i = k
  · subst k
    rw [commutator_triple_cyclic hG, commutator_self_right hG]
    exact K.one_mem
  rcases lt_or_gt_of_ne hij with hij | hji
  · rcases lt_or_gt_of_ne hjk with hjk | hkj
    · exact hcanonical hij hjk
    · rcases lt_or_gt_of_ne hik with hik | hki
      · exact hcyclic (hswap (hcanonical hik hkj))
      · exact hcyclic (hcanonical hki hij)
  · rcases lt_or_gt_of_ne hjk with hjk | hkj
    · rcases lt_or_gt_of_ne hik with hik | hki
      · exact hswap (hcanonical hji hik)
      · exact hcyclic (hcyclic (hcanonical hjk hki))
    · exact hswap (hcyclic (hcanonical hkj hji))

/-- Every triple commutator belongs to the closure of the increasing generator triples.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem commutator_triple_mem_increasingTripleClosure (a b c : Free I) :
    ⁅⁅a, b⁆, c⁆ ∈ increasingTripleClosure (I := I) := by
  let K := increasingTripleClosure (I := I)
  have hG : ∀ x : Free I, x ^ 3 = 1 := pow_three
  have extend_right (x y z : Free I)
      (hbase : ∀ k : I, ⁅⁅x, y⁆, of k⁆ ∈ K) :
      ⁅⁅x, y⁆, z⁆ ∈ K := by
    have hmem := mem_closure_range_of_closure_range_eq_top
      (of : I → Free I) (closure_range_of (I := I))
      (commutatorTripleRightHom hG x y) z
    exact (Subgroup.closure_le K).2 (by
      rintro _ ⟨k, rfl⟩
      exact hbase k) hmem
  have h₁ (i j : I) (z : Free I) : ⁅⁅of i, of j⁆, z⁆ ∈ K :=
    extend_right (of i) (of j) z fun k =>
      tripleCommutator_of_mem_increasingTripleClosure i j k
  have h₂ (i : I) (y z : Free I) : ⁅⁅of i, y⁆, z⁆ ∈ K := by
    apply extend_right (of i) y z
    intro k
    have h := h₁ i k y
    have heq : ⁅⁅of i, y⁆, of k⁆ = ⁅⁅of i, of k⁆, y⁆⁻¹ :=
      mul_eq_one_iff_eq_inv.mp (commutator_triple_antisymm hG (of i) (of k) y)
    rw [heq]
    exact K.inv_mem h
  apply extend_right a b c
  intro k
  have h := h₂ k a b
  rw [commutator_triple_cyclic hG (of k) a b] at h
  exact h

/--
For a free exponent-three group, mathlib's `lowerCentralSeries 2` (that is, `γ₃`) is generated by
the triple commutators with strictly increasing generator indices.


Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem lowerCentralSeries_two_eq_increasingTripleClosure :
    (⊤ : Subgroup (Free I)).lowerCentralSeries 2 =
      increasingTripleClosure (I := I) := by
  let K := increasingTripleClosure (I := I)
  have hG : ∀ x : Free I, x ^ 3 = 1 := pow_three
  have hKcenter : K ≤ Subgroup.center (Free I) := by
    change Subgroup.closure (Set.range (increasingTripleCommutator (I := I))) ≤
      Subgroup.center (Free I)
    refine (Subgroup.closure_le _).2 ?_
    rintro _ ⟨t, rfl⟩
    exact commutator_triple_mem_center hG (of t.first) (of t.second) (of t.third)
  apply le_antisymm
  · rw [show 2 = 1 + 1 by omega, Subgroup.lowerCentralSeries_succ,
      Subgroup.top_lowerCentralSeries_one]
    refine Subgroup.commutator_le.mpr fun d hd g _ => ?_
    induction hd using Subgroup.closure_induction with
    | mem u hu =>
        obtain ⟨p, -, q, -, rfl⟩ := hu
        exact commutator_triple_mem_increasingTripleClosure p q g
    | one => simp
    | mul u v _ _ hu hv =>
        have h : ⁅u * v, g⁆ = ⁅v, g⁆ * ⁅u, g⁆ := by
          rw [commutatorElement_mul_left_eq_conj_mul,
            Subgroup.mem_center_iff.mp (hKcenter hv) u]
          group
        rw [h]
        exact K.mul_mem hv hu
    | inv u _ hu =>
        have hc : ⁅g, u⁆ ∈ K := by
          rw [← commutatorElement_inv]
          exact K.inv_mem hu
        have h : ⁅u⁻¹, g⁆ = ⁅g, u⁆ := by
          rw [commutatorElement_inv_left,
            Subgroup.mem_center_iff.mp (hKcenter hc) u⁻¹]
          group
        rw [h]
        exact hc
  · rw [show 2 = 1 + 1 by omega, Subgroup.lowerCentralSeries_succ,
      Subgroup.top_lowerCentralSeries_one]
    change Subgroup.closure (Set.range (increasingTripleCommutator (I := I))) ≤
      ⁅commutator (Free I), ⊤⁆
    refine (Subgroup.closure_le _).2 ?_
    rintro _ ⟨t, rfl⟩
    exact Subgroup.commutator_mem_commutator
      (Subgroup.commutator_mem_commutator
        (Subgroup.mem_top (of t.first)) (Subgroup.mem_top (of t.second)))
      (Subgroup.mem_top (of t.third))

section Finite

variable [Finite I]

/-- The degree-two quotient of a finite-rank free exponent-three group is finite.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem finite_pairQuotient : Finite (PairQuotient (I := I)) := by
  let : Finite (IncreasingPair I) :=
    Finite.of_equiv (Set.powersetCard I 2) IncreasingPair.equivPowersetCard.symm
  apply finite_of_commuting_generators (x := increasingPairQuotient (I := I))
  · intro p
    exact pow_three_quotient (GammaThreeInDerived (I := I))
      (fun d : Derived (I := I) => Subtype.ext (pow_three d.1)) _
  · exact Function.Surjective.isMulCommutative
      (f := QuotientGroup.mk' (GammaThreeInDerived (I := I)))
      (QuotientGroup.mk'_surjective (GammaThreeInDerived (I := I)))
      (isMulCommutative_commutator (G := Free I) pow_three)
  · exact closure_range_increasingPairQuotient

/-- The degree-two quotient has order at most `3 ^ choose n 2`.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem natCard_pairQuotient_le :
    Nat.card (PairQuotient (I := I)) ≤ 3 ^ (Nat.card I).choose 2 := by
  let : Finite (IncreasingPair I) :=
    Finite.of_equiv (Set.powersetCard I 2) IncreasingPair.equivPowersetCard.symm
  calc
    Nat.card (PairQuotient (I := I)) ≤ 3 ^ Nat.card (IncreasingPair I) := by
      apply natCard_le_three_pow_of_commuting_generators
          (x := increasingPairQuotient (I := I))
      · intro p
        exact pow_three_quotient (GammaThreeInDerived (I := I))
          (fun d : Derived (I := I) => Subtype.ext (pow_three d.1)) _
      · exact Function.Surjective.isMulCommutative
          (f := QuotientGroup.mk' (GammaThreeInDerived (I := I)))
          (QuotientGroup.mk'_surjective (GammaThreeInDerived (I := I)))
          (isMulCommutative_commutator (G := Free I) pow_three)
      · exact closure_range_increasingPairQuotient
    _ = 3 ^ (Nat.card I).choose 2 := by
      rw [IncreasingPair.natCard_eq_choose]

/-- The third lower-central layer of a finite-rank free exponent-three group is finite.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem finite_lowerCentralSeries_two :
    Finite ((⊤ : Subgroup (Free I)).lowerCentralSeries 2) := by
  let K := increasingTripleClosure (I := I)
  let : Finite (IncreasingTriple I) :=
    Finite.of_equiv (Set.powersetCard I 3) IncreasingTriple.equivPowersetCard.symm
  rw [lowerCentralSeries_two_eq_increasingTripleClosure]
  apply finite_of_commuting_generators
      (x := fun t : IncreasingTriple I =>
        (⟨increasingTripleCommutator t, Subgroup.subset_closure ⟨t, rfl⟩⟩ : K))
  · intro t
    exact Subtype.ext (pow_three (increasingTripleCommutator t))
  · have hKle : K ≤ commutator (Free I) := by
      change increasingTripleClosure (I := I) ≤ commutator (Free I)
      rw [← lowerCentralSeries_two_eq_increasingTripleClosure]
      exact (⊤ : Subgroup (Free I)).lowerCentralSeries_antitone
        (show 1 ≤ 2 by omega)
    exact ⟨⟨fun a b => Subtype.ext
      (commute_of_mem_commutator pow_three (hKle a.2) (hKle b.2)).eq⟩⟩
  · exact closure_range_subtype (increasingTripleCommutator (I := I))

/-- The third lower-central layer has order at most `3 ^ choose n 3`.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem natCard_lowerCentralSeries_two_le :
    Nat.card ((⊤ : Subgroup (Free I)).lowerCentralSeries 2) ≤
      3 ^ (Nat.card I).choose 3 := by
  let K := increasingTripleClosure (I := I)
  let : Finite (IncreasingTriple I) :=
    Finite.of_equiv (Set.powersetCard I 3) IncreasingTriple.equivPowersetCard.symm
  rw [lowerCentralSeries_two_eq_increasingTripleClosure]
  calc
    Nat.card K ≤ 3 ^ Nat.card (IncreasingTriple I) := by
      apply natCard_le_three_pow_of_commuting_generators
          (x := fun t : IncreasingTriple I =>
            (⟨increasingTripleCommutator t, Subgroup.subset_closure ⟨t, rfl⟩⟩ : K))
      · intro t
        exact Subtype.ext (pow_three (increasingTripleCommutator t))
      · have hKle : K ≤ commutator (Free I) := by
          change increasingTripleClosure (I := I) ≤ commutator (Free I)
          rw [← lowerCentralSeries_two_eq_increasingTripleClosure]
          exact (⊤ : Subgroup (Free I)).lowerCentralSeries_antitone
            (show 1 ≤ 2 by omega)
        exact ⟨⟨fun a b => Subtype.ext
          (commute_of_mem_commutator pow_three (hKle a.2) (hKle b.2)).eq⟩⟩
      · exact closure_range_subtype (increasingTripleCommutator (I := I))
    _ = 3 ^ (Nat.card I).choose 3 := by
      rw [IncreasingTriple.natCard_eq_choose]

/-- `γ₃`, regarded as a subgroup of the derived subgroup, is finite.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem finite_gammaThreeInDerived : Finite (GammaThreeInDerived (I := I)) := by
  have hle :
      (⊤ : Subgroup (Free I)).lowerCentralSeries 2 ≤
        commutator (Free I) :=
    (⊤ : Subgroup (Free I)).lowerCentralSeries_antitone
      (show 1 ≤ 2 by omega)
  let : Finite ((⊤ : Subgroup (Free I)).lowerCentralSeries 2) :=
    finite_lowerCentralSeries_two
  exact Finite.of_equiv
    ((⊤ : Subgroup (Free I)).lowerCentralSeries 2)
    (Subgroup.subgroupOfEquivOfLe hle).symm.toEquiv

/-- The derived subgroup of a finite-rank free exponent-three group is finite.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem finite_derived : Finite (Derived (I := I)) := by
  let : Finite (GammaThreeInDerived (I := I)) := finite_gammaThreeInDerived
  let : Finite (PairQuotient (I := I)) := finite_pairQuotient
  exact Finite.of_subgroup_quotient (GammaThreeInDerived (I := I))

/-- The derived subgroup has the expected collected-form upper bound.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem natCard_derived_le :
    Nat.card (Derived (I := I)) ≤
      3 ^ ((Nat.card I).choose 2 + (Nat.card I).choose 3) := by
  have hle :
      (⊤ : Subgroup (Free I)).lowerCentralSeries 2 ≤
        commutator (Free I) :=
    (⊤ : Subgroup (Free I)).lowerCentralSeries_antitone
      (show 1 ≤ 2 by omega)
  have hcard :
      Nat.card (GammaThreeInDerived (I := I)) =
        Nat.card ((⊤ : Subgroup (Free I)).lowerCentralSeries 2) :=
    Nat.card_congr (Subgroup.subgroupOfEquivOfLe hle).toEquiv
  rw [Subgroup.card_eq_card_quotient_mul_card_subgroup]
  calc
    Nat.card (PairQuotient (I := I)) * Nat.card (GammaThreeInDerived (I := I)) ≤
        3 ^ (Nat.card I).choose 2 * 3 ^ (Nat.card I).choose 3 := by
      rw [hcard]
      exact Nat.mul_le_mul natCard_pairQuotient_le natCard_lowerCentralSeries_two_le
    _ = 3 ^ ((Nat.card I).choose 2 + (Nat.card I).choose 3) := by
      rw [pow_add]

/-- A finite-rank free exponent-three group is finite.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem finite : Finite (Free I) := by
  let : Finite (Derived (I := I)) := finite_derived
  let : Finite (Free I ⧸ commutator (Free I)) :=
    finite_abelianization (of : I → Free I) pow_three closure_range_of
  exact Finite.of_subgroup_quotient (commutator (Free I))

/-- The full collected-form upper bound for a finite-rank free exponent-three group.

Paper-ID: preliminaries.finite_normal_form
TeX: T3_modelcompanion_v7.tex, `fact:Levi and van der Waerden`, v7 Fact 2.27.
-/
theorem natCard_le :
    Nat.card (Free I) ≤
      3 ^ (Nat.card I + (Nat.card I).choose 2 + (Nat.card I).choose 3) := by
  rw [Subgroup.card_eq_card_quotient_mul_card_subgroup
    (commutator (Free I))]
  calc
    Nat.card (Free I ⧸ commutator (Free I)) *
          Nat.card (commutator (Free I)) ≤
        3 ^ Nat.card I * 3 ^ ((Nat.card I).choose 2 + (Nat.card I).choose 3) := by
      exact Nat.mul_le_mul
        (natCard_abelianization_le_three_pow
          (of : I → Free I) pow_three closure_range_of)
        natCard_derived_le
    _ = 3 ^ (Nat.card I + (Nat.card I).choose 2 + (Nat.card I).choose 3) := by
      rw [← pow_add, add_assoc]

end Finite

end Free

end T3
