/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
module

public import T3.GroupTheory.Amalgamation.Cyclic
public import T3.GroupTheory.AssociatedGradedExamples
public import T3.GroupTheory.Coproduct.CentralSeries

/-!
# A non-strict free subgroup and failure of coproduct injectivity

In the free exponent-three group on `x,y,z`, the subgroup generated by `[x,y]` and `z`
is free of rank two but is not lower-central strict. Its coproduct with another rank-two
free group cannot amalgamate with the ambient group, and the induced coproduct map has a
nontrivial triple commutator in its kernel. The injectivity of the rank-two presentation
is proved from the Levi--van der Waerden collected normal form.

Paper-ID: examples.non_strict_coproduct, examples.strictness_necessity
TeX: T3_modelcompanion_v9.tex, Example 5.1 and Remark 5.2.
-/

@[expose] public section

open scoped commutatorElement

namespace T3.Free

private theorem generatorWord_two (l : Fin 2 → ZMod 3) :
    generatorWord l = of 0 ^ (l 0).val * of 1 ^ (l 1).val := by
  classical
  let := Fintype.ofFinite (Fin 2)
  have hu : (Finset.univ : Finset (Fin 2)) = {0, 1} := by
    ext i
    simp only [Finset.mem_univ, Finset.mem_insert, Finset.mem_singleton, true_iff]
    omega
  simp [generatorWord, hu, Finset.sort_insert]

private theorem pairWord_two (m : IncreasingPair (Fin 2) → ZMod 3) :
    (pairWord m : Free (Fin 2)) = ⁅of (0 : Fin 2), of 1⁆ ^ (m FreeTwo.pairIndex).val := by
  classical
  let := Fintype.ofFinite (IncreasingPair (Fin 2))
  have hu : (Finset.univ : Finset (IncreasingPair (Fin 2))) = {FreeTwo.pairIndex} := by
    ext p
    simp [FreeTwo.pair_eq p]
  simp [pairWord, hu, FreeTwo.pairIndex]

private theorem tripleWord_two (n : IncreasingTriple (Fin 2) → ZMod 3) :
    ((tripleWord n : (genReadout (I := Fin 2)).ker) : Free (Fin 2)) = 1 := by
  classical
  have : IsEmpty (IncreasingTriple (Fin 2)) := ⟨fun t => by
    have h1 := t.first_lt_second
    have h2 := t.second_lt_third
    have h3 := t.third.isLt
    simp only [Fin.lt_def] at h1 h2
    omega⟩
  simp [tripleWord, Finset.univ_eq_empty]

private theorem exists_normalForm_two (g : Free (Fin 2)) :
    ∃ i j k : Fin 3, g = of 0 ^ i.val * of 1 ^ j.val * ⁅of (0 : Fin 2), of 1⁆ ^ k.val := by
  obtain ⟨⟨l, m, n⟩, rfl⟩ := normalWord_bijective.surjective g
  refine ⟨⟨(l 0).val, (l 0).val_lt⟩, ⟨(l 1).val, (l 1).val_lt⟩,
    ⟨(m FreeTwo.pairIndex).val, (m FreeTwo.pairIndex).val_lt⟩, ?_⟩
  simp only [normalWord, generatorWord_two, pairWord_two, tripleWord_two, mul_one]

/-- The paper's map of the free rank-two group sending its generators to `[x,y]` and `z`.

Paper-ID: examples.non_strict_coproduct
TeX: T3_modelcompanion_v9.tex, Example 5.1.
-/
def nonStrictLift : Free (Fin 2) →* Free (Fin 3) :=
  lift pow_three (fun i => if i = 0 then ⁅of (0 : Fin 3), of 1⁆ else of 2)

@[simp]
private theorem nonStrictLift_zero : nonStrictLift (of 0) = ⁅of (0 : Fin 3), of 1⁆ := by
  simp [nonStrictLift]

@[simp]
private theorem nonStrictLift_one : nonStrictLift (of 1) = of 2 := by simp [nonStrictLift]

/-- The normal form proves that the subgroup generated by `[x,y]` and `z` is free of rank two.

Paper-ID: examples.non_strict_coproduct
TeX: T3_modelcompanion_v9.tex, Example 5.1.
-/
theorem nonStrictLift_injective : Function.Injective nonStrictLift := by
  apply (MonoidHom.ker_eq_bot_iff nonStrictLift).mp
  refine le_antisymm ?_ bot_le
  intro g hg
  rw [MonoidHom.mem_ker] at hg
  obtain ⟨i, j, k, rfl⟩ := exists_normalForm_two g
  simp only [map_mul, map_pow, map_commutatorElement,
    nonStrictLift_zero, nonStrictLift_one] at hg
  have h := congrArg toLvdW hg
  simp only [map_mul, map_pow, map_commutatorElement, toLvdW_of, map_one] at h
  have hgen := congrArg (fun c : LvdW (Fin 3) => c.gen 2) h
  have hpair := congrArg (fun c : LvdW (Fin 3) => c.pair 0 1) h
  have htriple := congrArg (fun c : LvdW (Fin 3) => c.triple 0 1 2) h
  fin_cases i <;> fin_cases j <;> fin_cases k
  all_goals
    simp only [pow_succ, pow_zero, one_mul,
      LvdW.mul_gen, LvdW.mul_pair, LvdW.mul_triple, LvdW.one_gen, LvdW.one_pair,
      LvdW.one_triple, LvdW.commutator_gen, LvdW.commutator_pair,
      LvdW.triple_commutator_triple, LvdW.of_gen, LvdW.of_pair, LvdW.of_triple,
      Fin.isValue, ↓reduceIte] at hgen hpair htriple
    solve
    | exfalso; revert hgen; decide
    | exfalso; revert hpair; decide
    | exfalso; revert htriple; decide
    | simp

/-- The subgroup `A = ⟨[x,y],z⟩` in the paper's example.

Paper-ID: examples.non_strict_coproduct
TeX: T3_modelcompanion_v9.tex, Example 5.1.
-/
def nonStrictSubgroup : Subgroup (Free (Fin 3)) := nonStrictLift.range

/-- The subgroup in the example is precisely the closure of the two prescribed elements.

Paper-ID: examples.non_strict_coproduct
TeX: T3_modelcompanion_v9.tex, Example 5.1.
-/
theorem nonStrictSubgroup_eq_closure :
    nonStrictSubgroup = Subgroup.closure {⁅of (0 : Fin 3), of 1⁆, of 2} := by
  rw [nonStrictSubgroup, MonoidHom.range_eq_map, ← closure_range_of,
    MonoidHom.map_closure, ← Set.range_comp]
  congr 1
  ext g
  constructor
  · rintro ⟨i, rfl⟩
    fin_cases i <;> simp
  · simp only [Set.mem_insert_iff, Set.mem_singleton_iff]
    rintro (rfl | rfl)
    · exact ⟨0, nonStrictLift_zero⟩
    · exact ⟨1, nonStrictLift_one⟩

/-- The specified rank-two free presentation of `A` is an isomorphism.

Paper-ID: examples.non_strict_coproduct
TeX: T3_modelcompanion_v9.tex, Example 5.1.
-/
noncomputable def nonStrictEquiv : Free (Fin 2) ≃* nonStrictSubgroup :=
  MonoidHom.ofInjective nonStrictLift_injective

/-- The element `a=[x,y]`, regarded as an element of `A`.

Paper-ID: examples.non_strict_coproduct
TeX: T3_modelcompanion_v9.tex, Example 5.1.
-/
noncomputable def nonStrictGenerator : nonStrictSubgroup := nonStrictEquiv (of 0)

@[simp]
private theorem nonStrictGenerator_coe :
    (nonStrictGenerator : Free (Fin 3)) = ⁅of (0 : Fin 3), of 1⁆ := nonStrictLift_zero

private theorem free_generator_not_mem_commutator {I : Type*} [LinearOrder I] (i : I) :
    of i ∉ commutator (Free I) := by
  classical
  intro hi
  have h := toLvdW_gen_eq_zero_of_mem_commutator hi i
  exact one_ne_zero (by simpa only [toLvdW_of, LvdW.of_gen_self] using h)

/-- The free rank-three group has the coincidence of central series asserted in the example.

Paper-ID: examples.non_strict_coproduct
TeX: T3_modelcompanion_v9.tex, Example 5.1, the opening calculation.
-/
theorem centralSeriesCoincide_fin_three : CentralSeriesCoincide (Free (Fin 3)) := by
  let : Nontrivial (Free (Fin 1)) := nontrivial_of_ne (of 0) 1 (fun h =>
    free_generator_not_mem_commutator (0 : Fin 1) (h ▸ (commutator _).one_mem))
  let e : Fin 1 ⊕ Fin 2 ≃ Fin 3 := finSumFinEquiv
  let eF : Free (Fin 1 ⊕ Fin 2) ≃* Free (Fin 3) :=
    MonoidHom.toMulEquiv (map e) (map e.symm)
      (hom_ext fun i => by simp) (hom_ext fun i => by simp)
  exact (Coproduct.centralSeriesCoincide_freeTwo (G := Free (Fin 1))).mulEquiv
    (sumEquivCoproduct.symm.trans eF)

/-- The second specified generator of `A`, namely `z`.

Paper-ID: examples.non_strict_coproduct
TeX: T3_modelcompanion_v9.tex, Example 5.1.
-/
noncomputable def nonStrictSecondGenerator : nonStrictSubgroup := nonStrictEquiv (of 1)

@[simp]
private theorem nonStrictSecondGenerator_coe :
    (nonStrictSecondGenerator : Free (Fin 3)) = of 2 := nonStrictLift_one

/-- The derived subgroup of `A` consists of the three powers of `[a,z]`.
The residues in `Fin 3` are the representatives of the coefficients in `𝔽₃`.

Paper-ID: examples.non_strict_coproduct
TeX: T3_modelcompanion_v9.tex, Example 5.1.
-/
theorem nonStrictSubgroup_mem_commutator_iff (g : nonStrictSubgroup) :
    g ∈ commutator nonStrictSubgroup ↔
      ∃ k : Fin 3, g = ⁅nonStrictGenerator, nonStrictSecondGenerator⁆ ^ k.val := by
  constructor
  · intro hg
    have hm : (commutator nonStrictSubgroup).map nonStrictEquiv.symm.toMonoidHom ≤
        commutator (Free (Fin 2)) := by
      rw [commutator_def, Subgroup.map_commutator, commutator_def]
      exact Subgroup.commutator_mono le_top le_top
    have hi : nonStrictEquiv.symm g ∈ AssociatedGraded.term (Free (Fin 2)) 2 :=
      hm (Subgroup.mem_map_of_mem _ hg)
    obtain ⟨k, hk⟩ := (FreeTwo.mem_term_two_iff _).mp hi
    refine ⟨k, ?_⟩
    apply nonStrictEquiv.symm.injective
    simpa only [map_pow, map_commutatorElement, nonStrictGenerator,
      nonStrictSecondGenerator, MulEquiv.symm_apply_apply] using hk
  · rintro ⟨k, rfl⟩
    exact Subgroup.pow_mem _
      (Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _)) _

/-- The element `a` survives the abelianization of `A`.

Paper-ID: examples.non_strict_coproduct
TeX: T3_modelcompanion_v9.tex, Example 5.1.
-/
theorem nonStrictGenerator_not_mem_commutator :
    nonStrictGenerator ∉ commutator nonStrictSubgroup := by
  intro h
  apply free_generator_not_mem_commutator (0 : Fin 2)
  have hm : (commutator nonStrictSubgroup).map nonStrictEquiv.symm.toMonoidHom ≤
      commutator (Free (Fin 2)) := by
    rw [commutator_def, Subgroup.map_commutator, commutator_def]
    exact Subgroup.commutator_mono le_top le_top
  simpa only [nonStrictGenerator, MulEquiv.coe_toMonoidHom, MulEquiv.symm_apply_apply] using
    hm (Subgroup.mem_map_of_mem _ h)

/-- The subgroup `⟨[x,y],z⟩` is not lower-central strict in the free rank-three group.

Paper-ID: examples.non_strict_coproduct
TeX: T3_modelcompanion_v9.tex, Example 5.1, item 1.
-/
theorem nonStrictSubgroup_not_isStrict : ¬ IsStrict nonStrictSubgroup := by
  intro h
  apply nonStrictGenerator_not_mem_commutator
  have hc := (isStrict_iff_comap_subtype nonStrictSubgroup).mp h
  rw [Subgroup.top_lowerCentralSeries_one] at hc
  rw [hc.1]
  change (nonStrictGenerator : Free (Fin 3)) ∈ (⊤ : Subgroup (Free (Fin 3))).lowerCentralSeries 1
  rw [nonStrictGenerator_coe, Subgroup.top_lowerCentralSeries_one]
  exact Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _)

/-- The triple commutator that witnesses both failures in the example.

Paper-ID: examples.non_strict_coproduct
TeX: T3_modelcompanion_v9.tex, Example 5.1.
-/
noncomputable def nonStrictWitness : Coproduct nonStrictSubgroup (Free (Fin 2)) :=
  ⁅⁅(Coproduct.inl nonStrictGenerator : Coproduct nonStrictSubgroup (Free (Fin 2))),
    Coproduct.inr (G := nonStrictSubgroup) (of (0 : Fin 2))⁆,
    Coproduct.inr (G := nonStrictSubgroup) (of (1 : Fin 2))⁆

/-- The witness is nontrivial in `A ∐ F₂`.

Paper-ID: examples.non_strict_coproduct
TeX: T3_modelcompanion_v9.tex, Example 5.1, items 2 and 3.
-/
theorem nonStrictWitness_ne_one : nonStrictWitness ≠ 1 := by
  let p : nonStrictSubgroup →* Free (Fin 3) :=
    (lift pow_three (fun _ : Fin 2 => of (0 : Fin 3))).comp nonStrictEquiv.symm.toMonoidHom
  let q : Free (Fin 2) →* Free (Fin 3) :=
    lift pow_three (fun i => if i = 0 then of 1 else of 2)
  intro h
  have hh := congrArg (Coproduct.lift pow_three p q) h
  have hp : p nonStrictGenerator = of 0 := by simp [p, nonStrictGenerator]
  have hq0 : q (of 0) = of 1 := by simp [q]
  have hq1 : q (of 1) = of 2 := by simp [q]
  simp only [nonStrictWitness, map_commutatorElement, map_one] at hh
  change ⁅⁅p nonStrictGenerator, q (of 0)⁆, q (of 1)⁆ = 1 at hh
  rw [hp, hq0, hq1] at hh
  exact triple_commutator_of_ne_one (by decide : (0 : Fin 3) ≠ 1)
    (by decide : (0 : Fin 3) ≠ 2) (by decide : (1 : Fin 3) ≠ 2) hh

/-- The induced coproduct comparison kills the specified nontrivial witness.

Paper-ID: examples.non_strict_coproduct
TeX: T3_modelcompanion_v9.tex, Example 5.1, item 3.
-/
theorem map_nonStrictWitness :
    Coproduct.map nonStrictSubgroup.subtype (MonoidHom.id (Free (Fin 2))) nonStrictWitness = 1 := by
  simp only [nonStrictWitness, map_commutatorElement, Coproduct.map_inl, Coproduct.map_inr,
    MonoidHom.id_apply, Subgroup.subtype_apply, nonStrictGenerator_coe,
    map_commutatorElement]
  exact commutator_quadruple Coproduct.pow_three _ _ _ _

/-- Coproduct comparison can fail to be injective when lower-central strictness is omitted.

Paper-ID: examples.non_strict_coproduct, examples.strictness_necessity
TeX: T3_modelcompanion_v9.tex, Example 5.1, item 3, and Remark 5.2.
-/
theorem nonStrict_coproduct_map_not_injective :
    ¬ Function.Injective (Coproduct.map nonStrictSubgroup.subtype
      (MonoidHom.id (Free (Fin 2)))) := by
  intro h
  exact nonStrictWitness_ne_one (h (map_nonStrictWitness.trans (map_one _).symm))

/-- `A ∐ F₂` and the ambient free rank-three group do not amalgamate over `A`.

Paper-ID: examples.non_strict_coproduct
TeX: T3_modelcompanion_v9.tex, Example 5.1, item 2.
-/
theorem nonStrict_not_amalgamable :
    ¬ Amalgamation.AmalgamableOver nonStrictSubgroup.subtype
      (Coproduct.inl (H := Free (Fin 2))) := by
  rintro ⟨K, hK, hpow, i, j, hi, hj, hij⟩
  let : Group K := hK
  have ha : i (nonStrictGenerator : Free (Fin 3)) = j (Coproduct.inl nonStrictGenerator) :=
    DFunLike.congr_fun hij nonStrictGenerator
  have hw : j nonStrictWitness = 1 := by
    simp only [nonStrictWitness, map_commutatorElement, ← ha, nonStrictGenerator_coe]
    exact commutator_quadruple hpow _ _ _ _
  exact nonStrictWitness_ne_one (hj (hw.trans (map_one j).symm))

end T3.Free
