/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
module

public import T3.GroupTheory.Free.CommutatorRank
public import T3.GroupTheory.Amalgamation.Cyclic

/-!
# Failure of uniform bounds without existential closedness

The cyclic subgroup generated by the product of `n` disjoint commutators in the countably
generated free exponent-three group needs `2n` generators in every strict envelope. The same
lower bound holds in every subgroup witnessing its non-amalgamation with the fixed free group
of rank three. Thus neither uniform bound in the paper extends to arbitrary exponent-three
groups. The base is always finite cyclic of rank one and the other factor always has rank three.

Paper-ID: examples.unbounded_witness_rank
TeX: T3_modelcompanion_v7.tex, Proposition 5.5 and the surrounding paragraphs, lines 1434–1457.
-/

@[expose] public noncomputable section

namespace T3.Free

open Amalgamation

/-- The cyclic base generated by the paired commutator product.

Paper-ID: examples.unbounded_witness_rank
TeX: T3_modelcompanion_v7.tex, the subgroup `Aₙ` preceding Proposition 5.5.
-/
abbrev pairedCyclic (n : ℕ) : Subgroup (Free ℕ) := Subgroup.zpowers (pairedCommutator n)

/-- The cyclic bases are finitely generated, including the trivial base at `n = 0`.

Paper-ID: examples.unbounded_witness_rank
TeX: T3_modelcompanion_v7.tex, the cyclic subgroup `Aₙ` preceding Proposition 5.5.
-/
instance pairedCyclic_fg (n : ℕ) : Group.FG (pairedCyclic n) := by
  classical
  apply Group.fg_iff'.mpr
  refine ⟨1, {cyclicGenerator (pairedCommutator n)}, by simp, ?_⟩
  rw [Finset.coe_singleton, ← Subgroup.zpowers_eq_closure]
  exact top_unique fun x _ => cyclicGenerator_generates (pairedCommutator n) x

/-- Every nontrivial cyclic base has precisely three elements.

Paper-ID: examples.unbounded_witness_rank
TeX: T3_modelcompanion_v7.tex, `Aₙ` is nontrivial of exponent three, line 1435.
-/
theorem natCard_pairedCyclic {n : ℕ} (hn : 0 < n) : Nat.card (pairedCyclic n) = 3 := by
  rw [pairedCyclic, Nat.card_zpowers]
  exact orderOf_eq_three pow_three (pairedCommutator_ne_one hn)

/-- The cyclic bases are finite.

Paper-ID: examples.unbounded_witness_rank
TeX: T3_modelcompanion_v7.tex, the finite cyclic bases preceding Proposition 5.5.
-/
theorem finite_pairedCyclic {n : ℕ} (hn : 0 < n) : Finite (pairedCyclic n) :=
  Nat.finite_of_card_ne_zero (by rw [natCard_pairedCyclic hn]; decide)

/-- All positive members of the family of cyclic bases are isomorphic.

Paper-ID: examples.unbounded_witness_rank
TeX: T3_modelcompanion_v7.tex, `Aₙ ≅ Aₘ` for positive `n,m`, line 1435.
-/
def pairedCyclicEquiv {n m : ℕ} (hn : 0 < n) (hm : 0 < m) :
    pairedCyclic n ≃* pairedCyclic m :=
  (zmodMulEquivOfGenerator (cyclicGenerator_generates (pairedCommutator n))
    (natCard_pairedCyclic hn)).symm.trans
      (zmodMulEquivOfGenerator (cyclicGenerator_generates (pairedCommutator m))
        (natCard_pairedCyclic hm))

/-- Each positive cyclic base has generator rank exactly one.

Paper-ID: examples.unbounded_witness_rank
TeX: T3_modelcompanion_v7.tex, `d(Aₙ) = 1` after Proposition 5.5, line 1453.
-/
theorem rank_pairedCyclic {n : ℕ} (hn : 0 < n) : Group.rank (pairedCyclic n) = 1 := by
  classical
  let : Nontrivial (pairedCyclic n) :=
    ⟨⟨cyclicGenerator (pairedCommutator n), 1,
      fun h => pairedCommutator_ne_one hn (congrArg Subtype.val h)⟩⟩
  apply Nat.le_antisymm _ (Group.rank_pos (pairedCyclic n))
  have hgen : Subgroup.closure
      (↑({cyclicGenerator (pairedCommutator n)} : Finset (pairedCyclic n)) :
        Set (pairedCyclic n)) = ⊤ := by
    rw [Finset.coe_singleton, ← Subgroup.zpowers_eq_closure]
    exact top_unique fun x _ => cyclicGenerator_generates (pairedCommutator n) x
  simpa using Group.rank_le hgen

/-- The fixed other factor in all obstruction examples has generator rank exactly three.

Paper-ID: examples.unbounded_witness_rank
TeX: T3_modelcompanion_v7.tex, `d(F₃) = 3` after Proposition 5.5, line 1453.
-/
theorem rank_free_three : Group.rank (Free (Fin 3)) = 3 := by
  apply Nat.le_antisymm
  · simpa using (rank_le_card (I := Fin 3))
  · simpa only [finrank_layerOne, Nat.card_fin] using
      (AssociatedGraded.finrank_layerOne_le_rank (G := Free (Fin 3)))

/-- The prescribed map identifying the generator of the base with the first free generator.

Paper-ID: examples.unbounded_witness_rank
TeX: T3_modelcompanion_v7.tex, the identification `aₙ ↦ s` preceding Proposition 5.5.
-/
def pairedCyclicToFreeThree {n : ℕ} (hn : 0 < n) : pairedCyclic n →* Free (Fin 3) :=
  cyclicToFreeThree pow_three (pairedCommutator n) (pairedCommutator_ne_one hn)

/-- The specified identification of the cyclic base with a subgroup of the fixed free factor
is injective.

Paper-ID: examples.unbounded_witness_rank
TeX: T3_modelcompanion_v7.tex, the identification `aₙ ↦ s` preceding Proposition 5.5.
-/
theorem pairedCyclicToFreeThree_injective {n : ℕ} (hn : 0 < n) :
    Function.Injective (pairedCyclicToFreeThree hn) :=
  cyclicToFreeThree_injective pow_three (pairedCommutator n) (pairedCommutator_ne_one hn)

/-- The fixed free factor and the ambient countably generated free group do not amalgamate
over any positive member of the family of cyclic bases.

Paper-ID: examples.unbounded_witness_rank
TeX: T3_modelcompanion_v7.tex, non-amalgamation preceding Proposition 5.5, line 1436.
-/
theorem not_amalgamableOver_pairedCyclic {n : ℕ} (hn : 0 < n) :
    ¬ AmalgamableOver (pairedCyclic n).subtype (pairedCyclicToFreeThree hn) := by
  intro h
  exact ((cyclicToFreeThree_amalgamableOver_iff pow_three (pairedCommutator n)
    (pairedCommutator_ne_one hn)).mp h) (pairedCommutator_mem_commutator n)

/-- Every lower-central-strict subgroup containing the cyclic base needs at least `2n`
generators. The cardinal form includes subgroups which are not finitely generated.

Paper-ID: examples.unbounded_witness_rank
TeX: T3_modelcompanion_v7.tex, Proposition 5.5, item 1.
-/
theorem pairedCyclic_strict_cardinalRank_le (n : ℕ) (D : Subgroup (Free ℕ))
    (hAD : pairedCyclic n ≤ D) (hD : IsStrict D) :
    ((2 * n : ℕ) : Cardinal) ≤ Group.cardinalRank D := by
  apply pairedCommutator_cardinalRank_le
  rw [hD.1]
  exact ⟨pairedCommutator_mem_commutator n, hAD (Subgroup.mem_zpowers _)⟩

/-- Every subgroup witnessing non-amalgamation over the fixed cyclic base needs at least
`2n` generators. Both base maps are the specified maps from the same ambient subgroup `Aₙ`.

Paper-ID: examples.unbounded_witness_rank
TeX: T3_modelcompanion_v7.tex, Proposition 5.5, item 2.
-/
theorem pairedCyclic_obstruction_cardinalRank_le {n : ℕ} (hn : 0 < n)
    (D : Subgroup (Free ℕ)) (hAD : pairedCyclic n ≤ D)
    (hbad : ¬ AmalgamableOver (Subgroup.inclusion hAD) (pairedCyclicToFreeThree hn)) :
    ((2 * n : ℕ) : Cardinal) ≤ Group.cardinalRank D := by
  have haD : pairedCommutator n ∈ D := hAD (Subgroup.mem_zpowers _)
  have hder : (⟨pairedCommutator n, haD⟩ : D) ∈ commutator D := by
    have hiff := cyclic_subgroup_amalgamableOver_iff pow_three (pairedCommutator n) D haD
      (pairedCyclicToFreeThree hn)
      (cyclicToFreeThree_generator pow_three (pairedCommutator n) (pairedCommutator_ne_one hn))
    exact not_not.mp (hbad ∘ hiff.mpr)
  apply pairedCommutator_cardinalRank_le
  have hm := Subgroup.mem_map_of_mem D.subtype hder
  rwa [← Subgroup.top_lowerCentralSeries_one, Subgroup.top_subtype_lowerCentralSeries] at hm

/-- No fixed bound suffices for strict envelopes of finite cyclic subgroups, even in the
single ambient group `Fω`. Every counterexample base has exactly one generator.

Paper-ID: examples.unbounded_witness_rank
TeX: T3_modelcompanion_v7.tex, the failure of the finite-envelope bound after Proposition 5.5.
-/
theorem exists_cyclic_without_bounded_strict_envelope (k : ℕ) :
    ∃ n : ℕ, 0 < n ∧ Group.rank (pairedCyclic n) = 1 ∧
      ∀ D : Subgroup (Free ℕ), pairedCyclic n ≤ D → IsStrict D →
        (k : Cardinal) < Group.cardinalRank D := by
  refine ⟨k + 1, Nat.succ_pos _, rank_pairedCyclic (Nat.succ_pos _), ?_⟩
  intro D hAD hD
  have hlt : (k : Cardinal) < ((2 * (k + 1) : ℕ) : Cardinal) := by
    exact_mod_cast (show k < 2 * (k + 1) by omega)
  exact hlt.trans_le (pairedCyclic_strict_cardinalRank_le _ D hAD hD)

/-- With a rank-one finite base and a fixed rank-three other factor, non-amalgamation inside
the single ambient group `Fω` has no uniform bound on the number of witness generators.

Paper-ID: examples.unbounded_witness_rank
TeX: T3_modelcompanion_v7.tex, the failure of the bounded-obstruction bound after Proposition 5.5.
-/
theorem exists_cyclic_without_bounded_obstruction (k : ℕ) :
    ∃ (n : ℕ) (hn : 0 < n), Group.rank (pairedCyclic n) = 1 ∧
      ¬ AmalgamableOver (pairedCyclic n).subtype (pairedCyclicToFreeThree hn) ∧
      ∀ (D : Subgroup (Free ℕ)) (hAD : pairedCyclic n ≤ D),
        ¬ AmalgamableOver (Subgroup.inclusion hAD) (pairedCyclicToFreeThree hn) →
          (k : Cardinal) < Group.cardinalRank D := by
  refine ⟨k + 1, Nat.succ_pos _, rank_pairedCyclic (Nat.succ_pos _),
    not_amalgamableOver_pairedCyclic (Nat.succ_pos _), ?_⟩
  intro D hAD hbad
  have hlt : (k : Cardinal) < ((2 * (k + 1) : ℕ) : Cardinal) := by
    exact_mod_cast (show k < 2 * (k + 1) by omega)
  exact hlt.trans_le (pairedCyclic_obstruction_cardinalRank_le _ D hAD hbad)

end T3.Free
